AddCSLuaFile()

function SWEP:doSuppressorStats()
    self.Primary.Sound = Sound("mw19.mike14.fire.s")
    self.Reverb = {
        RoomScale = 50000,
        Sounds = {
            Outside = {
                Layer = Sound("Atmo_DMR_Sup.Outside"),
                Reflection = Sound("Reflection_Sniper.Outside")
            },
    
            Inside = { 
                Layer = Sound("Atmo_DMR_Sup.Inside"),
                Reflection = Sound("Reflection_Sniper.Inside")
            }
        }
    }
    self.ParticleEffects.MuzzleFlash = "mw_fas2_muzzleflash_suppressed"
end

SWEP.Customization = {
    {"att_perk", "attachment_vm_sn_mike14_perk_soh", "att_perk_fmj", "attachment_vm_sn_mike14_perk_fullauto", "att_perk_ricochet"}, 

    {"att_stock", "attachment_vm_sn_mike14_stockcqb_alt", 
    "attachment_vm_sn_mike14_stock_v2_alt", "attachment_vm_sn_mike14_stock_tactical", 
    --[["attachment_vm_sn_mike14_stock_heavy", "attachment_vm_sn_mike14_stock_v3",]] "attachment_vm_sn_mike14_stock_heavy01", "attachment_vm_sn_mike14_stock_heavy02",
    "attachment_vm_sn_mike14_stock_light01", "attachment_vm_sn_mike14_stock_medium01", "attachment_vm_sn_mike14_stock_no"},

    {"attachment_vm_sn_mike14_mag", "attachment_vm_sn_mike14_xmags", "attachment_vm_sn_mike14_xmags2"},
   
    {"attachment_vm_sn_mike14_barrel", "attachment_vm_sn_mike14_barlong2", 
    "attachment_vm_sn_mike14_barlong", "attachment_vm_sn_mike14_barlight"},

    {"att_muzzle", "att_vm_breacher01", "att_vm_breacher02", "att_vm_compensator01", 
    "att_vm_compensator02", "att_vm_flashhider01", "att_vm_flashhider02", 
    "att_vm_flashhider03", "att_vm_flashhider04", "att_vm_muzzlebrake01",
    "att_vm_muzzlebrake02", "att_vm_muzzlebrake03",
    "att_vm_silencer01", "att_vm_silencer02", "att_vm_silencer03",
    "att_vm_silencer04", "att_vm_silencer05", "att_vm_silencer06"},

    {"att_sight", "att_vm_2x_west02_holo", "att_vm_2x_west02", "att_vm_reflex_02", "att_vm_minireddot01_tall", "att_vm_minireddot02_tall", "att_vm_minireddot03_tall",
    "att_vm_holo_west01", "att_vm_holo_west02", "att_vm_holo_east01", "att_vm_reflex_east01",
    "att_vm_reflex_east02_tall", "att_vm_reflex_west02_tall", "att_vm_reflex_west03",
    "att_vm_thermal_east01", "att_vm_thermal_west01", "att_vm_thermal_east01_hybrid",
    "att_vm_hybrid_west01", "att_vm_hybrid_west03", "att_vm_4x_east01_tall", "att_vm_2x_west01",
    "att_vm_4x_west01_tall", "att_vm_4x_west02_tall", "att_vm_reflex_west04",
    "att_vm_scope_mike14", "att_vm_scope_vz"},

    {"att_laser", "attachment_vm_sn_mike14_laser01", "attachment_vm_sn_mike14_laser02", 
    "attachment_vm_sn_mike14_laser03"},

    {"att_grip", "attachment_vm_sn_mike14_bipodgrip", "attachment_vm_sn_mike14_angledgrip01", "attachment_vm_sn_mike14_angledgrip02", "attachment_vm_sn_mike14_stubbygrip01", 
    "attachment_vm_sn_mike14_stubbygrip02", "attachment_vm_sn_mike14_vertgrip01", "attachment_vm_sn_mike14_vertgrip02", 
    "attachment_vm_sn_mike14_vertgrip03"},
}

--NECESSARY: it loads custom attachments from other authors
require("mw_utils")
mw_utils.LoadInjectors(SWEP)   


-- SWEP.Customization = {
--     ["Perk"] = {
--         Slot = 1,
--         {
--             Key = "no_perk",
--         },
--         {
--             Key = "perk_soh",
--             Stats = function(self)
--                 self.Animations.Reload = self.Animations.Reload_Fast
--                 self.Animations.Reload_Empty = self.Animations.Reload_Empty_Fast
--                 self.Animations.Reload_Xmag = self.Animations.Reload_Xmag_Fast
--                 self.Animations.Reload_Empty_Xmag = self.Animations.Reload_Empty_Xmag_Fast
--                 self.Animations.Reload_Xmag2 = self.Animations.Reload_Xmag2_Fast
--                 self.Animations.Reload_Empty_Xmag2 = self.Animations.Reload_Empty_Xmag2_Fast
--             end
--         },
--         {
--             Key = "perk_fastmelee",
--             Stats = function(self)
--             end
--         },
--         {
--             Key = "perk_heavymelee",
--             Stats = function(self)
--             end
--         },
--         {
--             Key = "perk_fmj",
--             Stats = function(self)
--             end
--         }
--     },

--     ["Barrel"] = {
--         Slot = 2,
--         {
--             Key = "attachment_vm_sn_mike14_barrel",
--             Stats = function(self)
--             end
--         },
--         {
--             Key = "attachment_vm_sn_mike14_barlight",
--             Stats = function(self)
--             end
--         },
--         {
--             Key = "attachment_vm_sn_mike14_barlong",
--             Bodygroups = {
--                 ["tag_tip"] = 2,
--             },
--             Stats = function(self)
--             end
--         },
--         {
--             Key = "attachment_vm_sn_mike14_barlong2",
--             Bodygroups = {
--                 ["tag_tip"] = 4,
--             },
--             Stats = function(self)
--             end
--         },
--     },

--     ["Muzzle"] = {
--         Slot = 3,
--         {
--             Key = "no_muzzle"
--         },
--         {
--             Key = "attachment_vm_flashhider01",
--             Bodygroups = {
--                 ["tag_tip"] = 1,
--             },
--             VElement = {
--                 Bone = "tag_silencer",
--                 Position = Vector(0, 0, 0),
--                 Angles = Angle(),
--                 Offsets = { 
--                     ["Barrel"] = {
--                         [1] = {Vector(0, 0, 0), Angle()},
--                         [2] = {Vector(0, 0, 0), Angle()},
--                         [3] = {Vector(0, 1.9, 0), Angle()},
--                         [4] = {Vector(0, 3.25, 0), Angle()},
--                     }
--                 }
--             },
--             Stats = function(self)
--                 self.ParticleEffects.MuzzleFlash = "mw_fas2_muzzleflash_suppressed"
--             end 
--         },               
--         {
--             Key = "attachment_vm_flashhider02",
--             Bodygroups = {
--                 ["tag_tip"] = 1,
--             },
--             VElement = {
--                 Bone = "tag_silencer",
--                 Position = Vector(0, 0, 0),
--                 Angles = Angle(),
--                 Offsets = { 
--                     ["Barrel"] = {
--                         [1] = {Vector(0, 0, 0), Angle()},
--                         [2] = {Vector(0, 0, 0), Angle()},
--                         [3] = {Vector(0, 1.9, 0), Angle()},
--                         [4] = {Vector(0, 3.25, 0), Angle()},
--                     }
--                 }
--             },
--             Stats = function(self)
--                 self.ParticleEffects.MuzzleFlash = "mw_fas2_muzzleflash_suppressed"
--             end 
--         },                         
--         {
--             Key = "attachment_vm_flashhider05",
--             Bodygroups = {
--                 ["tag_tip"] = 1,
--             },
--             VElement = {
--                 Bone = "tag_silencer",
--                 Position = Vector(0, 0, 0),
--                 Angles = Angle(),
--                 Offsets = { 
--                     ["Barrel"] = {
--                         [1] = {Vector(0, 0, 0), Angle()},
--                         [2] = {Vector(0, 0, 0), Angle()},
--                         [3] = {Vector(0, 1.9, 0), Angle()},
--                         [4] = {Vector(0, 3.25, 0), Angle()},
--                     }
--                 }
--             },
--             Stats = function(self)
--                 self.ParticleEffects.MuzzleFlash = "mw_fas2_muzzleflash_suppressed"
--             end 
--         },                          
--         {
--             Key = "attachment_vm_muzzlebrake01",
--             Bodygroups = {
--                 ["tag_tip"] = 1,
--             },
--             VElement = {
--                 Bone = "tag_silencer",
--                 Position = Vector(0, 0, 0),
--                 Angles = Angle(),
--                 Offsets = { 
--                     ["Barrel"] = {
--                         [1] = {Vector(0, 0, 0), Angle()},
--                         [2] = {Vector(0, 0, 0), Angle()},
--                         [3] = {Vector(0, 1.9, 0), Angle()},
--                         [4] = {Vector(0, 3.25, 0), Angle()},
--                     }
--                 }
--             },
--             Stats = function(self)
--             end 
--         },         
--         {
--             Key = "attachment_vm_muzzlebrake02",
--             Bodygroups = {
--                 ["tag_tip"] = 1,
--             },
--             VElement = {
--                 Bone = "tag_silencer",
--                 Position = Vector(0, 0, 0),
--                 Angles = Angle(),
--                 Offsets = { 
--                     ["Barrel"] = {
--                         [1] = {Vector(0, 0, 0), Angle()},
--                         [2] = {Vector(0, 0, 0), Angle()},
--                         [3] = {Vector(0, 1.9, 0), Angle()},
--                         [4] = {Vector(0, 3.25, 0), Angle()},
--                     }
--                 }
--             },
--             Stats = function(self)
--             end 
--         },         
--         {
--             Key = "attachment_vm_muzzlebrake03",
--             Bodygroups = {
--                 ["tag_tip"] = 1,
--             },
--             VElement = {
--                 Bone = "tag_silencer",
--                 Position = Vector(0, 0, 0),
--                 Angles = Angle(),
--                 Offsets = { 
--                     ["Barrel"] = {
--                         [1] = {Vector(0, 0, 0), Angle()},
--                         [2] = {Vector(0, 0, 0), Angle()},
--                         [3] = {Vector(0, 1.9, 0), Angle()},
--                         [4] = {Vector(0, 3.25, 0), Angle()},
--                     }
--                 }
--             },
--             Stats = function(self)
--             end 
--         },         
--         {
--             Key = "attachment_vm_muzzlebrake04",
--             Bodygroups = {
--                 ["tag_tip"] = 1,
--             },
--             VElement = {
--                 Bone = "tag_silencer",
--                 Position = Vector(0, 0, 0),
--                 Angles = Angle(),
--                 Offsets = { 
--                     ["Barrel"] = {
--                         [1] = {Vector(0, 0, 0), Angle()},
--                         [2] = {Vector(0, 0, 0), Angle()},
--                         [3] = {Vector(0, 1.9, 0), Angle()},
--                         [4] = {Vector(0, 3.25, 0), Angle()},
--                     }
--                 }
--             },
--             Stats = function(self)
--             end 
--         },         
--         {
--             Key = "attachment_vm_compensator01",
--             Bodygroups = {
--                 ["tag_tip"] = 1,
--             },
--             VElement = {
--                 Bone = "tag_silencer",
--                 Position = Vector(0, 0, 0),
--                 Angles = Angle(),
--                 Offsets = { 
--                     ["Barrel"] = {
--                         [1] = {Vector(0, 0, 0), Angle()},
--                         [2] = {Vector(0, 0, 0), Angle()},
--                         [3] = {Vector(0, 1.9, 0), Angle()},
--                         [4] = {Vector(0, 3.25, 0), Angle()},
--                     }
--                 }
--             },
--             Stats = function(self)
--             end 
--         },   
--         {
--             Key = "attachment_vm_compensator02",
--             Bodygroups = {
--                 ["tag_tip"] = 1,
--             },
--             VElement = {
--                 Bone = "tag_silencer",
--                 Position = Vector(0, 0, 0),
--                 Angles = Angle(),
--                 Offsets = { 
--                     ["Barrel"] = {
--                         [1] = {Vector(0, 0, 0), Angle()},
--                         [2] = {Vector(0, 0, 0), Angle()},
--                         [3] = {Vector(0, 1.9, 0), Angle()},
--                         [4] = {Vector(0, 3.25, 0), Angle()},
--                     }
--                 }
--             },
--             Stats = function(self)
--             end 
--         },          
--         {
--             Key = "attachment_vm_muzzlemelee01",
--             Bodygroups = {
--                 ["tag_tip"] = 1,
--             },
--             VElement = {
--                 Bone = "tag_silencer",
--                 Position = Vector(0, 0, 0),
--                 Angles = Angle(),
--                 Offsets = { 
--                     ["Barrel"] = {
--                         [1] = {Vector(0, 0, 0), Angle()},
--                         [2] = {Vector(0, 0, 0), Angle()},
--                         [3] = {Vector(0, 1.9, 0), Angle()},
--                         [4] = {Vector(0, 3.25, 0), Angle()},
--                     }
--                 }
--             },
--             Stats = function(self)
--             end 
--         },   
--         {
--             Key = "attachment_vm_muzzlemelee02",
--             Bodygroups = {
--                 ["tag_tip"] = 1,
--             },
--             VElement = {
--                 Bone = "tag_silencer",
--                 Position = Vector(0, 0, 0),
--                 Angles = Angle(),
--                 Offsets = { 
--                     ["Barrel"] = {
--                         [1] = {Vector(0, 0, 0), Angle()},
--                         [2] = {Vector(0, 0, 0), Angle()},
--                         [3] = {Vector(0, 1.9, 0), Angle()},
--                         [4] = {Vector(0, 3.25, 0), Angle()},
--                     }
--                 }
--             },
--             Stats = function(self)
--             end 
--         },      
--         {
--             Key = "attachment_vm_silencer_east01",
--             Bodygroups = {
--                 ["tag_tip"] = 1,
--             },
--             VElement = {
--                 Bone = "tag_silencer",
--                 Position = Vector(0, 0, 0),
--                 Angles = Angle(),
--                 Offsets = { 
--                     ["Barrel"] = {
--                         [1] = {Vector(0, 0, 0), Angle()},
--                         [2] = {Vector(0, 0, 0), Angle()},
--                         [3] = {Vector(0, 1.9, 0), Angle()},
--                         [4] = {Vector(0, 3.25, 0), Angle()},
--                     }
--                 }
--             },
--             Stats = function(self)
--                 doSuppressorStats(self)
--             end 
--         },        
--         {
--             Key = "attachment_vm_silencer02",
--             Bodygroups = {
--                 ["tag_tip"] = 1,
--             },
--             VElement = {
--                 Bone = "tag_silencer",
--                 Position = Vector(0, 0, 0),
--                 Angles = Angle(),
--                 Offsets = { 
--                     ["Barrel"] = {
--                         [1] = {Vector(0, 0, 0), Angle()},
--                         [2] = {Vector(0, 0, 0), Angle()},
--                         [3] = {Vector(0, 1.9, 0), Angle()},
--                         [4] = {Vector(0, 3.25, 0), Angle()},
--                     }
--                 }
--             },
--             Stats = function(self)
--                 doSuppressorStats(self)
--             end 
--         },
--         {
--             Key = "attachment_vm_silencer03",
--             Bodygroups = {
--                 ["tag_tip"] = 1,
--             },
--             VElement = {
--                 Bone = "tag_silencer",
--                 Position = Vector(0, 0, 0),
--                 Angles = Angle(),
--                 Offsets = { 
--                     ["Barrel"] = {
--                         [1] = {Vector(0, 0, 0), Angle()},
--                         [2] = {Vector(0, 0, 0), Angle()},
--                         [3] = {Vector(0, 1.9, 0), Angle()},
--                         [4] = {Vector(0, 3.25, 0), Angle()},
--                     }
--                 }
--             },
--             Stats = function(self)
--                 doSuppressorStats(self)
--             end 
--         },
--         {
--             Key = "attachment_vm_silencer04",
--             Bodygroups = {
--                 ["tag_tip"] = 1,
--             },
--             VElement = {
--                 Bone = "tag_silencer",
--                 Position = Vector(0, 0, 0),
--                 Angles = Angle(),
--                 Offsets = { 
--                     ["Barrel"] = {
--                         [1] = {Vector(0, 0, 0), Angle()},
--                         [2] = {Vector(0, 0, 0), Angle()},
--                         [3] = {Vector(0, 1.9, 0), Angle()},
--                         [4] = {Vector(0, 3.25, 0), Angle()},
--                     }
--                 }
--             },
--             Stats = function(self)
--                 doSuppressorStats(self)
--             end 
--         },
--     },

--     ["Optic"] = {
--         Slot = 4,
--         {
--             Key = "no_sight",
--         },
--         {
--             Key = "attachment_vm_minireddot_tall",
--             Stats = function(self)
--                 self.ViewModelOffsets.Aim.Pos = self.ViewModelOffsets.Aim.Pos + Vector(0, 3, -0.9)
--                 self.ViewModelOffsets.Aim.Angles = self.ViewModelOffsets.Aim.Angles + Angle(0, 0.05, 0) --i know you tell me not to fuck with this but the dot being actually centered on the glass demands it xoxo
--             end
--         },
--         {
--             Key = "attachment_vm_minireddot02_tall",
--             Stats = function(self)
--                 self.ViewModelOffsets.Aim.Pos = self.ViewModelOffsets.Aim.Pos + Vector(0, 3, -0.85)
--                 self.ViewModelOffsets.Aim.Angles = self.ViewModelOffsets.Aim.Angles + Angle(0,0,0)
--             end
--         },      
--         {
--             Key = "attachment_vm_minireddot03_tall",
--             Stats = function(self)
--                 self.ViewModelOffsets.Aim.Pos = self.ViewModelOffsets.Aim.Pos + Vector(0, 3, -0.85)
--                 self.ViewModelOffsets.Aim.Angles = self.ViewModelOffsets.Aim.Angles + Angle(0,0,0)
--             end
--         },  
--         {
--             Key = "attachment_vm_holo_west02",
--             Stats = function(self)
--                 self.ViewModelOffsets.Aim.Pos = self.ViewModelOffsets.Aim.Pos + Vector(0, 3, -1)
--                 self.ViewModelOffsets.Aim.Angles = self.ViewModelOffsets.Aim.Angles + Angle(0,0,0)
--             end
--         },  
--         {
--             Key = "attachment_vm_holo_east",
--             Stats = function(self)
--                 self.ViewModelOffsets.Aim.Pos = self.ViewModelOffsets.Aim.Pos + Vector(-0.02, 5, -0.9)
--                 self.ViewModelOffsets.Aim.Angles = self.ViewModelOffsets.Aim.Angles + Angle(0,0,0)
--                 self.Zoom.FovMultiplier = 0.8
--                 self.Zoom.ViewModelFovMultiplier = 0.8
--             end
--         }, 
--         {
--             Key = "attachment_vm_reflex_east02_tall",
--             Stats = function(self)
--                 self.ViewModelOffsets.Aim.Pos = self.ViewModelOffsets.Aim.Pos + Vector(0, 3, -1.2)
--                 self.ViewModelOffsets.Aim.Angles = self.ViewModelOffsets.Aim.Angles + Angle(0,0,0)
--             end
--         },  
--         {
--             Key = "attachment_vm_reflex_west03",
--             Stats = function(self)
--                 self.ViewModelOffsets.Aim.Pos = self.ViewModelOffsets.Aim.Pos + Vector(0, 3, -1.1)
--                 self.ViewModelOffsets.Aim.Angles = self.ViewModelOffsets.Aim.Angles + Angle(0,0,0)
--             end
--         },  
--         {
--             Key = "attachment_vm_reflex_west04",
--             Stats = function(self)
--                 self.ViewModelOffsets.Aim.Pos = self.ViewModelOffsets.Aim.Pos + Vector(-0.015, 3, -1.05)
--                 self.ViewModelOffsets.Aim.Angles = self.ViewModelOffsets.Aim.Angles + Angle(0,0,0)
--             end
--         },  
--         {
--             Key = "attachment_vm_holo_west_lod0",
--             Stats = function(self)
--                 self.ViewModelOffsets.Aim.Pos = self.ViewModelOffsets.Aim.Pos + Vector(0, 3, -1.15)
--                 self.ViewModelOffsets.Aim.Angles = self.ViewModelOffsets.Aim.Angles + Angle(-0.05,0.05,0)
--             end
--         },  
--         {
--             Key = "attachment_vm_reflex_east",
--             Stats = function(self)
--                 self.ViewModelOffsets.Aim.Pos = self.ViewModelOffsets.Aim.Pos + Vector(0, 3, -1)
--                 self.ViewModelOffsets.Aim.Angles = self.ViewModelOffsets.Aim.Angles + Angle(-0.15,0,0)
--             end
--         }, 
--         {
--             Key = "attachment_vm_4x_east_tall",
--             Stats = function(self)
--                 self.ViewModelOffsets.Aim.Pos = self.ViewModelOffsets.Aim.Pos + Vector(0.11, 4, -1.23)
--                 self.ViewModelOffsets.Aim.Angles = self.ViewModelOffsets.Aim.Angles + Angle(0,0,0)
--                 self.Zoom.FovMultiplier = 0.8
--                 self.Zoom.ViewModelFovMultiplier = 0.8
--             end
--         },        
--         {
--             Key = "attachment_vm_4x_west_tall",
--             Stats = function(self)
--                 self.ViewModelOffsets.Aim.Pos = self.ViewModelOffsets.Aim.Pos + Vector(-0, 4, -1.34)
--                 self.ViewModelOffsets.Aim.Angles = self.ViewModelOffsets.Aim.Angles + Angle(0,0,0)
--                 self.Zoom.FovMultiplier = 0.8
--                 self.Zoom.ViewModelFovMultiplier = 0.8
--             end
--         },        
--         {
--             Key = "attachment_vm_4x_west02_tall",
--             Stats = function(self)
--                 self.ViewModelOffsets.Aim.Pos = self.ViewModelOffsets.Aim.Pos + Vector(-0.01, 4, -1.23)
--                 self.ViewModelOffsets.Aim.Angles = self.ViewModelOffsets.Aim.Angles + Angle(0,0,0)
--                 self.Zoom.FovMultiplier = 0.8
--                 self.Zoom.ViewModelFovMultiplier = 0.8
--             end
--         },
--         {
--             Key = "attachment_vm_thermal_east_tall",
--             VElement = {
--                 Bone = "tag_reflex",
--                 Position = Vector(0, 0, 0),
--                 Angles = Angle(),
--                 Offsets = { 
--                     ["Barrel"] = {
--                         [2] = {Vector(0, 0, 0), Angle()},
--                         [3] = {Vector(0, 0, 0), Angle()},
--                         [4] = {Vector(0, 0, 0), Angle()}
--                     }
--                 }
--             },
--             Stats = function(self)
--                 self.ViewModelOffsets.Aim.Pos = self.ViewModelOffsets.Aim.Pos + Vector(-0.0015, 4, -1.165)
--                 self.ViewModelOffsets.Aim.Angles = self.ViewModelOffsets.Aim.Angles + Angle(0,0,0)
--                 self.Zoom.FovMultiplier = 0.8
--                 self.Zoom.ViewModelFovMultiplier = 0.8
--             end
--         }, 
--         {
--             Key = "attachment_vm_thermal_hybrid",
--             VElement = {
--                 Bone = "tag_reflex",
--                 Position = Vector(0, 0, 0),
--                 Angles = Angle(),
--                 Offsets = { 
--                     ["Barrel"] = {
--                         [2] = {Vector(0, 0, 0), Angle()},
--                         [3] = {Vector(0, 0, 0), Angle()},
--                         [4] = {Vector(0, 0, 0), Angle()}
--                     }
--                 }
--             },
--             Stats = function(self)
--                 self.ViewModelOffsets.Aim.Pos = self.ViewModelOffsets.Aim.Pos + Vector(0, 4, -0.74)
--                 self.ViewModelOffsets.Aim.Angles = self.ViewModelOffsets.Aim.Angles + Angle(0,0,0)
--                 self.HybridAimAngles = Angle(0, 0, -45)
--                 self.HybridAimPos = Vector(-1.75, 10.5, -0.25)
--                 self.Zoom.FovMultiplier = 0.8
--                 self.Zoom.ViewModelFovMultiplier = 0.8
--             end
--         }, 
--         {
--             Key = "attachment_vm_thermal_west_01",
--             VElement = {
--                 Bone = "tag_reflex",
--                 Position = Vector(0, 0, 0),
--                 Angles = Angle(),
--                 Offsets = { 
--                     ["Barrel"] = {
--                         [2] = {Vector(0, 0, 0), Angle()},
--                         [3] = {Vector(0, 0, 0), Angle()},
--                         [4] = {Vector(0, 0, 0), Angle()}
--                     }
--                 }
--             },
--             Stats = function(self)
--                 self.ViewModelOffsets.Aim.Pos = self.ViewModelOffsets.Aim.Pos + Vector(-0.005, 4, -0.725)
--                 self.ViewModelOffsets.Aim.Angles = self.ViewModelOffsets.Aim.Angles + Angle(0,0,0)
--                 self.Zoom.FovMultiplier = 0.8
--                 self.Zoom.ViewModelFovMultiplier = 0.8
--             end
--         }, 
--         {
--             Key = "weapon_vm_scope_mike14_alt",
--             Stats = function(self)
--                 self.ViewModelOffsets.Aim.Pos = self.ViewModelOffsets.Aim.Pos + Vector(-0.01,6,-1.16)
--                 self.Zoom.Blur.EyeFocusDistance = 3.5
--             end
--         }, 
--         {
--             Key = "attachment_vm_scope_vz",
--             Stats = function(self)
--                 self.ViewModelOffsets.Aim.Pos = self.ViewModelOffsets.Aim.Pos + Vector(-0.0035,6,-1.095)
--                 self.Zoom.Blur.EyeFocusDistance = 3.5
--             end
--         }, 
--         {
--             Key = "attachment_vm_hybrid_west",
--             VElement = {
--                 Bone = "tag_reflex",
--                 Position = Vector(0, 0, 0),
--                 Angles = Angle(),
--                 Offsets = { 
--                     ["Barrel"] = {
--                         [2] = {Vector(0, 0, 0), Angle()},
--                         [3] = {Vector(0, 0, 0), Angle()},
--                         [4] = {Vector(0, 0, 0), Angle()}
--                     }
--                 }
--             },
--             Stats = function(self)
--                 self.ViewModelOffsets.Aim.Pos = self.ViewModelOffsets.Aim.Pos + Vector(0.005, 4, -0.88)
--                 self.ViewModelOffsets.Aim.Angles = self.ViewModelOffsets.Aim.Angles + Angle(0,0,0)
--                 self.HybridAimAngles = Angle(-0.01, 0.02, 0)
--                 self.HybridAimPos = Vector(0,3.5,-2.05)
--                 self.Zoom.FovMultiplier = 0.8
--                 self.Zoom.ViewModelFovMultiplier = 0.8
--             end
--         }, 
--         {
--             Key = "attachment_vm_hybrid_west02",
--             Bodygroups = {
--                 ["tag_rail"] = 1
--             },
--             Stats = function(self)
--                 self.ViewModelOffsets.Aim.Pos = self.ViewModelOffsets.Aim.Pos + Vector(-0.025, 4, -1.145)
--                 self.ViewModelOffsets.Aim.Angles = self.ViewModelOffsets.Aim.Angles + Angle(0,0,0)
--                 self.HybridAimAngles = Angle(-0, 0.025, 0)
--                 self.HybridAimPos = Vector(-0.015, 4, -1.15)
--                 self.Zoom.Blur.EyeFocusDistance = 3.5
--                 self.Zoom.FovMultiplier = 0.8
--                 self.Zoom.ViewModelFovMultiplier = 0.85
--             end
--         },
--         {
--             Key = "attachment_vm_hybrid_west02_thermal",
--             Stats = function(self)
--                 self.ViewModelOffsets.Aim.Pos = self.ViewModelOffsets.Aim.Pos + Vector(-0.025, 4, -1.145)
--                 self.ViewModelOffsets.Aim.Angles = self.ViewModelOffsets.Aim.Angles + Angle(0,0,0)
--                 self.HybridAimAngles = Angle(-0, 0.025, 0)
--                 self.HybridAimPos = Vector(-0.015, 4, -1.15)
--                 self.Zoom.Blur.EyeFocusDistance = 3.5
--                 self.Zoom.FovMultiplier = 0.8
--                 self.Zoom.ViewModelFovMultiplier = 0.85
--             end
--         }, 
--         {
--             Key = "attachment_vm_hybrid_west03",
--             VElement = {
--                 Bone = "tag_reflex",
--                 Position = Vector(0, 0, 0),
--                 Angles = Angle(),
--                 Offsets = { 
--                     ["Barrel"] = {
--                         [2] = {Vector(0, 0, 0), Angle()},
--                         [3] = {Vector(0, 0, 0), Angle()},
--                         [4] = {Vector(0, 0, 0), Angle()}
--                     }
--                 }
--             },
--             Stats = function(self)
--                 self.ViewModelOffsets.Aim.Pos = self.ViewModelOffsets.Aim.Pos + Vector(-0.005, 4, -0.81)
--                 self.ViewModelOffsets.Aim.Angles = self.ViewModelOffsets.Aim.Angles + Angle(0,0,0)
--                 self.Zoom.Blur.EyeFocusDistance = 1.5
--                 self.HybridAimAngles = Angle(0, 0, -45)
--                 self.HybridAimPos = Vector(-1.55, 4.5, -0)
--                 self.Zoom.FovMultiplier = 0.8
--                 self.Zoom.ViewModelFovMultiplier = 0.85
--             end
--         }, 
--     },
    
--     ["Laser"] = {
--         Slot = 5,
--         {
--             Key = "no_laser"
--         },
--         {
--             Key = "attachment_vm_laser_cylinder01",
--             Bodygroups = {
--                 ["tag_laser"] = 1,
--             },
--             VElement = {
--                 Bone = "tag_laser_attach",
--                 Position = Vector(0, 0, 0),
--                 Angles = Angle(),
--                 Offsets = { 
--                     ["Barrel"] = {
--                     }
--                 }
--             },
--             Stats = function(self)
--             end
--         },
--         {
--             Key = "attachment_vm_laser_cylinder02",
--             Bodygroups = {
--                 ["tag_laser"] = 1,
--             },
--             VElement = {
--                 Bone = "tag_laser_attach",
--                 Position = Vector(0, 0, 0),
--                 Angles = Angle(),
--                 Offsets = { 
--                     ["Barrel"] = {
--                     }
--                 }
--             },
--             Stats = function(self)
--             end
--         },       
--         {
--             Key = "attachment_vm_laser_cylinder03",
--             Bodygroups = {
--                 ["tag_laser"] = 1,
--             },
--             VElement = {
--                 Bone = "tag_laser_attach",
--                 Position = Vector(0, 0, 0),
--                 Angles = Angle(),
--                 Offsets = { 
--                     ["Barrel"] = {
--                     }
--                 }
--             },
--             Stats = function(self)
--             end
--         }
--     },

--     ["Stock"] = {
--         Slot = 6,
--         {
--             Key = "no_attachment",
--         },
--         {
--             Key = "attachment_vm_sn_mike14_stock_v2_alt",
--             Bodygroups = {
--                 ["tag_stock"] = 1,
--             },
--             Stats = function(self)
--             end
--         },
--         {
--             Key = "attachment_vm_stock_heavy",
--             Bodygroups = {
--                 ["tag_stock"] = 2,
--             },
--             Stats = function(self)
--                 self:SetGripPoseParameter2("grip_pistolgrip_offset")
--             end
--         },
--         {
--             Key = "attachment_vm_sn_mike14_stockcqb_alt",
--             Bodygroups = {
--                 ["tag_stock"] = 3,
--             },
--             Stats = function(self)
--                 self:SetGripPoseParameter2("grip_pistolgrip_offset")
--             end
--         },
--         {
--             Key = "attachment_vm_sn_mike14_stock_tactical",
--             Bodygroups = {
--                 ["tag_stock"] = 1,
--             },
--             Stats = function(self)
--             end
--         },
--     },

--     ["Magazine"] = {
--         Slot = 7,
--         {
--             Key = "attachment_vm_sn_mike14_mag"
--         },
--         {
--             Key = "attachment_vm_sn_mike14_xmags",
--             Stats = function(self)
--             end
--         },
--         {
--             Key = "attachment_vm_sn_mike14_xmags2",
--             Stats = function(self)
--             end
--         }
--     },

--     ["Underbarrel"] = {
--         Slot = 8,
--         {
--             Key = "no_underbarrel",
--         },
--         {
--             Key = "attachment_vm_angledgrip_lod0",
--             VElement = {
--                 Bone = "tag_grip_attach",
--                 Position = Vector(0, 0, 0),
--                 Angles = Angle(),
--                 Offsets = { 
--                     ["Barrel"] = {
--                     }
--                 }
--             },
--             Stats = function(self)
--                 self:SetGripPoseParameter("grip_ang_offset")
--             end
--         },
--         {
--             Key = "attachment_vm_angledgrip04",
--             VElement = {
--                 Bone = "tag_grip_attach",
--                 Position = Vector(0, 0, 0),
--                 Angles = Angle(),
--                 Offsets = { 
--                     ["Barrel"] = {
--                     }
--                 }
--             },
--             Stats = function(self)
--                 self:SetGripPoseParameter("grip_ang_offset")
--             end
--         },
--         {
--             Key = "attachment_vm_vertgrip02_lod0",
--             VElement = {
--                 Bone = "tag_folding_grip",
--                 Position = Vector(0, 0, 0),
--                 Angles = Angle(),
--                 Offsets = { 
--                     ["Barrel"] = {
--                     }
--                 }
--             },
--             Stats = function(self)
--                 self:SetGripPoseParameter("grip_vert_offset")
--             end
--         },
--         {
--             Key = "attachment_vm_vertgrip03",
--             VElement = {
--                 Bone = "tag_folding_grip",
--                 Position = Vector(0, 0, 0),
--                 Angles = Angle(),
--                 Offsets = { 
--                     ["Barrel"] = {
--                     }
--                 }
--             },
--             Stats = function(self)
--                 self:SetGripPoseParameter("grip_vert_offset")
--             end
--         },
--         {
--             Key = "attachment_vm_vertgrip_stubby02",
--             VElement = {
--                 Bone = "tag_folding_grip",
--                 Position = Vector(0, 0, 0),
--                 Angles = Angle(),
--                 Offsets = { 
--                     ["Barrel"] = {
--                     }
--                 }
--             },
--             Stats = function(self)
--                 self:SetGripPoseParameter("grip_vert_offset")
--             end
--         },
--         {
--             Key = "attachment_vm_vertgrip_stubby01",
--             VElement = {
--                 Bone = "tag_folding_grip",
--                 Position = Vector(0, 0, 0),
--                 Angles = Angle(),
--                 Offsets = { 
--                     ["Barrel"] = {
--                     }
--                 }
--             },
--             Stats = function(self)
--                 self:SetGripPoseParameter("grip_vert_offset")
--             end
--         },
--         {
--             Key = "attachment_vm_vertgrip_stubby04",
--             VElement = {
--                 Bone = "tag_folding_grip",
--                 Position = Vector(0, 0, 0),
--                 Angles = Angle(),
--                 Offsets = { 
--                     ["Barrel"] = {
--                     }
--                 }
--             },
--             Stats = function(self)
--                 self:SetGripPoseParameter("grip_vert_offset")
--             end
--         },
--     }
-- }