-- Generated by GmodSoundGen

-- File: D:\Downloads\important_stuff_v2\Tools\GmodSoundGen_0519\weapon_sn_crossbow.all.lua
-- Total length: 31

-- Sound: 1
sound.Add({
	name = "weap_crossbow_fire_plr",
	channel = CHAN_WPNFOLEY + 2,
	level = 140,
	volume = 1,
	pitch = {100,107},
	sound = {
		"weapons/crossbow/shot_00.ogg",
		}
})
-- Sound: 8
sound.Add({
	name = "wfoly_plr_sn_crossbow_drop_01",
	channel = CHAN_WPNFOLEY + 5,
	level = 140,
	volume = 1,
	pitch = {100,107},
	sound = {
		"reloads/iw8_crossbow/wfoly_sn_crossbow_drop.ogg",
		}
})
-- Sound: 9
sound.Add({
	name = "wfoly_plr_sn_crossbow_drop_quick_01",
	channel = CHAN_WPNFOLEY + 6,
	level = 140,
	volume = 1,
	pitch = {100,107},
	sound = {
		"reloads/iw8_crossbow/wfoly_sn_crossbow_drop_quick.ogg",
		}
})
-- Sound: 10
sound.Add({
	name = "wfoly_plr_sn_crossbow_inspect_01",
	channel = CHAN_WPNFOLEY + 7,
	level = 140,
	volume = 1,
	pitch = {100,107},
	sound = {
		"reloads/iw8_crossbow/wfoly_sn_crossbow_inspect_01.ogg",
		}
})
-- Sound: 11
sound.Add({
	name = "wfoly_plr_sn_crossbow_inspect_02",
	channel = CHAN_WPNFOLEY + 8,
	level = 140,
	volume = 1,
	pitch = {100,107},
	sound = {
		"reloads/iw8_crossbow/wfoly_sn_crossbow_inspect_02.ogg",
		}
})
-- Sound: 12
sound.Add({
	name = "wfoly_plr_sn_crossbow_inspect_03",
	channel = CHAN_WPNFOLEY + 9,
	level = 140,
	volume = 1,
	pitch = {100,107},
	sound = {
		"reloads/iw8_crossbow/wfoly_sn_crossbow_inspect_03.ogg",
		}
})
-- Sound: 13
sound.Add({
	name = "wfoly_plr_sn_crossbow_inspect_04",
	channel = CHAN_WPNFOLEY + 10,
	level = 140,
	volume = 1,
	pitch = {100,107},
	sound = {
		"reloads/iw8_crossbow/wfoly_sn_crossbow_inspect_04.ogg",
		}
})
-- Sound: 14
sound.Add({
	name = "wfoly_plr_sn_crossbow_inspect_05",
	channel = CHAN_WPNFOLEY + 1,
	level = 140,
	volume = 1,
	pitch = {100,107},
	sound = {
		"reloads/iw8_crossbow/wfoly_sn_crossbow_inspect_05.ogg",
		}
})
-- Sound: 15
sound.Add({
	name = "wfoly_plr_sn_crossbow_raise_01",
	channel = CHAN_WPNFOLEY + 2,
	level = 140,
	volume = 1,
	pitch = {100,107},
	sound = {
		"reloads/iw8_crossbow/wfoly_sn_crossbow_raise.ogg",
		}
})
-- Sound: 16
sound.Add({
	name = "wfoly_plr_sn_crossbow_raise_first_01",
	channel = CHAN_WPNFOLEY + 3,
	level = 140,
	volume = 1,
	pitch = {100,107},
	sound = {
		"reloads/iw8_crossbow/wfoly_sn_crossbow_raise_first_safety_off.ogg",
		}
})
-- Sound: 17
sound.Add({
	name = "wfoly_plr_sn_crossbow_raise_first_02",
	channel = CHAN_WPNFOLEY + 4,
	level = 140,
	volume = 1,
	pitch = {100,107},
	sound = {
		"reloads/iw8_crossbow/wfoly_sn_crossbow_raise_first_end.ogg",
		}
})
-- Sound: 18
sound.Add({
	name = "wfoly_plr_sn_crossbow_raise_quick_01",
	channel = CHAN_WPNFOLEY + 5,
	level = 140,
	volume = 1,
	pitch = {100,107},
	sound = {
		"reloads/iw8_crossbow/wfoly_sn_crossbow_raise_quick.ogg",
		}
})
-- Sound: 19
sound.Add({
	name = "wfoly_plr_sn_crossbow_reload_01",
	channel = CHAN_WPNFOLEY + 6,
	level = 140,
	volume = 1,
	pitch = {100,107},
	sound = {
		"reloads/iw8_crossbow/wfoly_sn_crossbow_reload_rotate.ogg",
		}
})
-- Sound: 20
sound.Add({
	name = "wfoly_plr_sn_crossbow_reload_02",
	channel = CHAN_WPNFOLEY + 7,
	level = 140,
	volume = 1,
	pitch = {100,107},
	sound = {
		"reloads/iw8_crossbow/wfoly_sn_crossbow_reload_pull_string.ogg",
		}
})
-- Sound: 21
sound.Add({
	name = "wfoly_plr_sn_crossbow_reload_03",
	channel = CHAN_WPNFOLEY + 8,
	level = 140,
	volume = 1,
	pitch = {100,107},
	sound = {
		"reloads/iw8_crossbow/wfoly_sn_crossbow_reload_load_arrow.ogg",
		}
})
-- Sound: 22
sound.Add({
	name = "wfoly_plr_sn_crossbow_reload_04",
	channel = CHAN_WPNFOLEY + 9,
	level = 140,
	volume = 1,
	pitch = {100,107},
	sound = {
		"reloads/iw8_crossbow/wfoly_sn_crossbow_reload_lock_arrow_01.ogg",
		}
})
-- Sound: 23
sound.Add({
	name = "wfoly_plr_sn_crossbow_reload_045",
	channel = CHAN_WPNFOLEY + 10,
	level = 140,
	volume = 1,
	pitch = {100,107},
	sound = {
		"reloads/iw8_crossbow/wfoly_sn_crossbow_reload_lock_arrow_02.ogg",
		}
})
-- Sound: 24
sound.Add({
	name = "wfoly_plr_sn_crossbow_reload_05",
	channel = CHAN_WPNFOLEY + 1,
	level = 140,
	volume = 1,
	pitch = {100,107},
	sound = {
		"reloads/iw8_crossbow/wfoly_sn_crossbow_reload_end.ogg",
		}
})
-- Sound: 25
sound.Add({
	name = "wfoly_plr_sn_crossbow_reload_fast_01",
	channel = CHAN_WPNFOLEY + 2,
	level = 140,
	volume = 1,
	pitch = {100,107},
	sound = {
		"reloads/iw8_crossbow/wfoly_sn_crossbow_reload_fast_rotate.ogg",
		}
})
-- Sound: 26
sound.Add({
	name = "wfoly_plr_sn_crossbow_reload_fast_02",
	channel = CHAN_WPNFOLEY + 3,
	level = 140,
	volume = 1,
	pitch = {100,107},
	sound = {
		"reloads/iw8_crossbow/wfoly_sn_crossbow_reload_fast_pull_string.ogg",
		}
})
-- Sound: 27
sound.Add({
	name = "wfoly_plr_sn_crossbow_reload_fast_03",
	channel = CHAN_WPNFOLEY + 4,
	level = 140,
	volume = 1,
	pitch = {100,107},
	sound = {
		"reloads/iw8_crossbow/wfoly_sn_crossbow_reload_fast_arrow_up.ogg",
		}
})
-- Sound: 28
sound.Add({
	name = "wfoly_plr_sn_crossbow_reload_fast_04",
	channel = CHAN_WPNFOLEY + 5,
	level = 140,
	volume = 1,
	pitch = {100,107},
	sound = {
		"reloads/iw8_crossbow/wfoly_sn_crossbow_reload_fast_load_arrow_01.ogg",
		}
})
-- Sound: 29
sound.Add({
	name = "wfoly_plr_sn_crossbow_reload_fast_045",
	channel = CHAN_WPNFOLEY + 6,
	level = 140,
	volume = 1,
	pitch = {100,107},
	sound = {
		"reloads/iw8_crossbow/wfoly_sn_crossbow_reload_fast_load_arrow_02.ogg",
		}
})
-- Sound: 30
sound.Add({
	name = "wfoly_plr_sn_crossbow_reload_fast_05",
	channel = CHAN_WPNFOLEY + 7,
	level = 140,
	volume = 1,
	pitch = {100,107},
	sound = {
		"reloads/iw8_crossbow/wfoly_sn_crossbow_reload_fast_end.ogg",
		}
})
