-- Generated by GmodSoundGen

-- File: D:\Downloads\important_stuff_v2\Tools\GmodSoundGen_0519\weapon_sh_charlie725.all.lua
-- Total length: 77
sound.Add({
    name =           "wfoly_plr_sh_charlie725_raise_first_01",
    channel =        CHAN_WPNFOLEY +1,
    volume =         1,
    sound = {"reloads/iw8_charlie725/wfoly_plr_sh_charlie725_raise_first_start.ogg"}              
})
sound.Add({
    name =           "wfoly_plr_sh_charlie725_raise_first_02",
    channel =        CHAN_WPNFOLEY +2,
    volume =         1,
    sound = {"reloads/iw8_charlie725/wfoly_plr_sh_charlie725_raise_first_close_01.ogg"}              
})
sound.Add({
    name =           "wfoly_plr_sh_charlie725_raise_first_03",
    channel =        CHAN_WPNFOLEY +3,
    volume =         1,
    sound = {"reloads/iw8_charlie725/wfoly_plr_sh_charlie725_raise_first_end.ogg"}              
})


sound.Add({
    name =           "mw19.charlie725.fire",
    channel =        CHAN_WEAPON,
    level = 140,
    volume =         1,
    pitch = {80,110},
    sound = "^weapons/charlie725/weap_romeo870_fire_plr_01.wav"
})
sound.Add({
    name =           "mw19.charlie725.fire.s",
    channel =        CHAN_WEAPON,
    level = 140,
    volume =         1,
    pitch = {80,110},
    sound = "^weapons/charlie725/weap_romeo870_sup_plr_01.wav"
})

-- Sound: 6
sound.Add({
	name = "weap_charlie725_fire_bang_plr",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {98,101},
	sound = {
		"weapons/romeo870/weap_romeo870_fire_plr_01.ogg",
		"weapons/romeo870/weap_romeo870_fire_plr_02.ogg",
		"weapons/romeo870/weap_romeo870_fire_plr_03.ogg",
		"weapons/romeo870/weap_romeo870_fire_plr_04.ogg",
		"weapons/romeo870/weap_romeo870_fire_plr_05.ogg",
		"weapons/romeo870/weap_romeo870_fire_plr_06.ogg",
		}
})
-- Sound: 7
sound.Add({
	name = "weap_charlie725_fire_plr",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {98,101},
	sound = {
		"weapons/charlie725/weap_charlie725_fire_first_plr_01.ogg",
		"weapons/charlie725/weap_charlie725_fire_first_plr_02.ogg",
		"weapons/charlie725/weap_charlie725_fire_first_plr_03.ogg",
		"weapons/charlie725/weap_charlie725_fire_first_plr_04.ogg",
		"weapons/charlie725/weap_charlie725_fire_first_plr_05.ogg",
		"weapons/charlie725/weap_charlie725_fire_first_plr_06.ogg",
		"weapons/charlie725/weap_charlie725_fire_first_plr_ads_01.ogg",
		"weapons/charlie725/weap_charlie725_fire_first_plr_ads_02.ogg",
		"weapons/charlie725/weap_charlie725_fire_first_plr_ads_03.ogg",
		"weapons/charlie725/weap_charlie725_fire_first_plr_ads_04.ogg",
		"weapons/charlie725/weap_charlie725_fire_first_plr_ads_05.ogg",
		"weapons/charlie725/weap_charlie725_fire_first_plr_ads_06.ogg",
		}
})
-- Sound: 8
sound.Add({
	name = "weap_charlie725_fire_plr_atmo",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {98,101},
	sound = {
		"weapons/atmo/exterior/shotgun/weap_shotgun_fire_plr_atmo_ext1_01.ogg",
		"weapons/atmo/exterior/shotgun/weap_shotgun_fire_plr_atmo_ext1_02.ogg",
		"weapons/atmo/exterior/shotgun/weap_shotgun_fire_plr_atmo_ext1_03.ogg",
		"weapons/atmo/exterior/shotgun/weap_shotgun_fire_plr_atmo_ext1_04.ogg",
		"weapons/atmo/exterior/shotgun/weap_shotgun_fire_plr_atmo_ext1_05.ogg",
		"weapons/atmo/exterior/shotgun/weap_shotgun_fire_plr_atmo_ext1_06.ogg",
		"weapons/atmo/interior/shotgun/weap_shotgun_fire_plr_atmo_int1_01.ogg",
		"weapons/atmo/interior/shotgun/weap_shotgun_fire_plr_atmo_int1_02.ogg",
		"weapons/atmo/interior/shotgun/weap_shotgun_fire_plr_atmo_int1_03.ogg",
		"weapons/atmo/interior/shotgun/weap_shotgun_fire_plr_atmo_int1_04.ogg",
		"weapons/atmo/interior/shotgun/weap_shotgun_fire_plr_atmo_int1_05.ogg",
		"weapons/atmo/interior/shotgun/weap_shotgun_fire_plr_atmo_int1_06.ogg",
		}
})
-- Sound: 9
sound.Add({
	name = "weap_charlie725_fire_plr_lfe",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"weapons/iw8_dpapa12/iw8_weap_dpapa12_fire_plr_lfe_01.ogg",
		"weapons/iw8_dpapa12/iw8_weap_dpapa12_fire_plr_lfe_01.ogg",
		}
})
-- Sound: 10
sound.Add({
	name = "weap_charlie725_fire_plr_mech",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {98,101},
	sound = {
		"weapons/charlie725/weap_charlie725_fire_plr_swtn_01.ogg",
		"weapons/charlie725/weap_charlie725_fire_plr_swtn_02.ogg",
		"weapons/charlie725/weap_charlie725_fire_plr_swtn_03.ogg",
		"weapons/charlie725/weap_charlie725_fire_plr_swtn_04.ogg",
		"weapons/charlie725/weap_charlie725_fire_plr_swtn_05.ogg",
		"weapons/charlie725/weap_charlie725_fire_plr_swtn_06.ogg",
		"weapons/charlie725/weap_charlie725_fire_plr_swtn_ads_01.ogg",
		"weapons/charlie725/weap_charlie725_fire_plr_swtn_ads_02.ogg",
		"weapons/charlie725/weap_charlie725_fire_plr_swtn_ads_03.ogg",
		"weapons/charlie725/weap_charlie725_fire_plr_swtn_ads_04.ogg",
		"weapons/charlie725/weap_charlie725_fire_plr_swtn_ads_05.ogg",
		"weapons/charlie725/weap_charlie725_fire_plr_swtn_ads_06.ogg",
		}
})
-- Sound: 11
sound.Add({
	name = "weap_charlie725_sup_bang_plr",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {98,101},
	sound = {
		"weapons/romeo870/weap_romeo870_sup_plr_01.ogg",
		"weapons/romeo870/weap_romeo870_sup_plr_02.ogg",
		"weapons/romeo870/weap_romeo870_sup_plr_03.ogg",
		"weapons/romeo870/weap_romeo870_sup_plr_04.ogg",
		"weapons/romeo870/weap_romeo870_sup_plr_05.ogg",
		"weapons/romeo870/weap_romeo870_sup_plr_06.ogg",
		}
})
-- Sound: 12
sound.Add({
	name = "weap_charlie725_sup_plr",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {98,101},
	sound = {
		"weapons/charlie725/weap_charlie725_fire_first_plr_01.ogg",
		"weapons/charlie725/weap_charlie725_fire_first_plr_02.ogg",
		"weapons/charlie725/weap_charlie725_fire_first_plr_03.ogg",
		"weapons/charlie725/weap_charlie725_fire_first_plr_04.ogg",
		"weapons/charlie725/weap_charlie725_fire_first_plr_05.ogg",
		"weapons/charlie725/weap_charlie725_fire_first_plr_06.ogg",
		"weapons/charlie725/weap_charlie725_fire_first_plr_ads_01.ogg",
		"weapons/charlie725/weap_charlie725_fire_first_plr_ads_02.ogg",
		"weapons/charlie725/weap_charlie725_fire_first_plr_ads_03.ogg",
		"weapons/charlie725/weap_charlie725_fire_first_plr_ads_04.ogg",
		"weapons/charlie725/weap_charlie725_fire_first_plr_ads_05.ogg",
		"weapons/charlie725/weap_charlie725_fire_first_plr_ads_06.ogg",
		}
})
-- Sound: 13
sound.Add({
	name = "weap_charlie725_sup_plr_atmo",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {98,101},
	sound = {
		"weapons/atmo/exterior/shotgun_sup/weap_shotgunsup_fire_plr_atmo_ext1_01.ogg",
		"weapons/atmo/exterior/shotgun_sup/weap_shotgunsup_fire_plr_atmo_ext1_02.ogg",
		"weapons/atmo/exterior/shotgun_sup/weap_shotgunsup_fire_plr_atmo_ext1_03.ogg",
		"weapons/atmo/exterior/shotgun_sup/weap_shotgunsup_fire_plr_atmo_ext1_04.ogg",
		"weapons/atmo/exterior/shotgun_sup/weap_shotgunsup_fire_plr_atmo_ext1_05.ogg",
		"weapons/atmo/exterior/shotgun_sup/weap_shotgunsup_fire_plr_atmo_ext1_06.ogg",
		"weapons/atmo/interior/shotgun/weap_shotgun_fire_plr_atmo_int1_01.ogg",
		"weapons/atmo/interior/shotgun/weap_shotgun_fire_plr_atmo_int1_02.ogg",
		"weapons/atmo/interior/shotgun/weap_shotgun_fire_plr_atmo_int1_03.ogg",
		"weapons/atmo/interior/shotgun/weap_shotgun_fire_plr_atmo_int1_04.ogg",
		"weapons/atmo/interior/shotgun/weap_shotgun_fire_plr_atmo_int1_05.ogg",
		"weapons/atmo/interior/shotgun/weap_shotgun_fire_plr_atmo_int1_06.ogg",
		}
})
-- Sound: 14
sound.Add({
	name = "weap_charlie725_sup_plr_lfe",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"weapons/iw8_dpapa12/iw8_weap_dpapa12_fire_plr_lfe_01.ogg",
		"weapons/iw8_dpapa12/iw8_weap_dpapa12_fire_plr_lfe_01.ogg",
		}
})
-- Sound: 15
sound.Add({
	name = "weap_charlie725_sup_plr_mech",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {98,101},
	sound = {
		"weapons/charlie725/weap_charlie725_fire_plr_swtn_01.ogg",
		"weapons/charlie725/weap_charlie725_fire_plr_swtn_02.ogg",
		"weapons/charlie725/weap_charlie725_fire_plr_swtn_03.ogg",
		"weapons/charlie725/weap_charlie725_fire_plr_swtn_04.ogg",
		"weapons/charlie725/weap_charlie725_fire_plr_swtn_05.ogg",
		"weapons/charlie725/weap_charlie725_fire_plr_swtn_06.ogg",
		"weapons/charlie725/weap_charlie725_fire_plr_swtn_ads_01.ogg",
		"weapons/charlie725/weap_charlie725_fire_plr_swtn_ads_02.ogg",
		"weapons/charlie725/weap_charlie725_fire_plr_swtn_ads_03.ogg",
		"weapons/charlie725/weap_charlie725_fire_plr_swtn_ads_04.ogg",
		"weapons/charlie725/weap_charlie725_fire_plr_swtn_ads_05.ogg",
		"weapons/charlie725/weap_charlie725_fire_plr_swtn_ads_06.ogg",
		}
})
-- Sound: 16
sound.Add({
	name = "weap_sh_charlie725_ads_down",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/weap_sh_charlie725_ads_down.ogg",
		}
})
-- Sound: 17
sound.Add({
	name = "weap_sh_charlie725_ads_up",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/weap_sh_charlie725_ads_up.ogg",
		}
})
-- Sound: 18
sound.Add({
	name = "wfoly_plr_sh_charlie725_drop_01",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/wfoly_plr_sh_charlie725_drop_down.ogg",
		}
})
-- Sound: 17
sound.Add({
	name = "weap_sh_charlie725_fire_first_plr",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"weapons/charlie725/weap_charlie725_fire_first_plr_01.ogg",
		}
})
-- Sound: 18
sound.Add({
	name = "weap_sh_charlie725_disconnector_plr",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"weapons/romeo870/weap_romeo870_disconnector_plr_01.ogg",
		}
})
-- Sound: 19
sound.Add({
	name = "wfoly_plr_sh_charlie725_drop_quick_01",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/wfoly_plr_sh_charlie725_drop_quick_down.ogg",
		}
})
-- Sound: 20
sound.Add({
	name = "wfoly_plr_sh_charlie725_inspect_01",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/wfoly_sh_charlie725_inspect_01.ogg",
		}
})
-- Sound: 21
sound.Add({
	name = "wfoly_plr_sh_charlie725_inspect_02",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/wfoly_sh_charlie725_inspect_02.ogg",
		}
})
-- Sound: 22
sound.Add({
	name = "wfoly_plr_sh_charlie725_inspect_03",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/wfoly_sh_charlie725_inspect_03.ogg",
		}
})
-- Sound: 23
sound.Add({
	name = "wfoly_plr_sh_charlie725_inspect_04",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/wfoly_sh_charlie725_inspect_04.ogg",
		}
})
-- Sound: 24
sound.Add({
	name = "wfoly_plr_sh_charlie725_inspect_05",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/wfoly_sh_charlie725_inspect_05.ogg",
		}
})
-- Sound: 25
sound.Add({
	name = "wfoly_plr_sh_charlie725_raise_01",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/wfoly_plr_sh_charlie725_raise_up.ogg",
		}
})
-- Sound: 26
sound.Add({
	name = "wfoly_plr_sh_charlie725_raise_quick_01",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/wfoly_plr_sh_charlie725_raise_quick_up.ogg",
		}
})
-- Sound: 27
sound.Add({
	name = "wfoly_plr_sh_charlie725_reload_01",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/wfoly_plr_sh_charlie725_reload_start.ogg",
		}
})
-- Sound: 28
sound.Add({
	name = "wfoly_plr_sh_charlie725_reload_02",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/wfoly_plr_sh_charlie725_reload_open_01.ogg",
		}
})
-- Sound: 29
sound.Add({
	name = "wfoly_plr_sh_charlie725_reload_03",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/wfoly_plr_sh_charlie725_reload_swing.ogg",
		}
})
-- Sound: 30
sound.Add({
	name = "wfoly_plr_sh_charlie725_reload_04",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/wfoly_plr_sh_charlie725_reload_shellin_01.ogg",
		}
})
-- Sound: 31
sound.Add({
	name = "wfoly_plr_sh_charlie725_reload_05",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/wfoly_plr_sh_charlie725_reload_close_01.ogg",
		}
})
-- Sound: 32
sound.Add({
	name = "wfoly_plr_sh_charlie725_reload_06",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/wfoly_plr_sh_charlie725_reload_end.ogg",
		}
})
-- Sound: 33
sound.Add({
	name = "wfoly_plr_sh_charlie725_reload_empty_01",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/wfoly_plr_sh_charlie725_reload_empty_start.ogg",
		}
})
-- Sound: 34
sound.Add({
	name = "wfoly_plr_sh_charlie725_reload_empty_02",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/wfoly_plr_sh_charlie725_reload_empty_open_01.ogg",
		}
})
-- Sound: 35
sound.Add({
	name = "wfoly_plr_sh_charlie725_reload_empty_03",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/wfoly_plr_sh_charlie725_reload_empty_swing.ogg",
		}
})
-- Sound: 36
sound.Add({
	name = "wfoly_plr_sh_charlie725_reload_empty_04",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/wfoly_plr_sh_charlie725_reload_empty_shellsin_v2_01.ogg",
		}
})
-- Sound: 37
sound.Add({
	name = "wfoly_plr_sh_charlie725_reload_empty_045",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/wfoly_plr_sh_charlie725_reload_empty_shellsin_v2_02.ogg",
		}
})
-- Sound: 38
sound.Add({
	name = "wfoly_plr_sh_charlie725_reload_empty_05",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/wfoly_plr_sh_charlie725_reload_empty_close_01.ogg",
		}
})
-- Sound: 39
sound.Add({
	name = "wfoly_plr_sh_charlie725_reload_empty_06",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/wfoly_plr_sh_charlie725_reload_empty_end.ogg",
		}
})
-- Sound: 40
sound.Add({
	name = "wfoly_plr_sh_charlie725_reload_empty_fast_01",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/wfoly_plr_sh_charlie725_reload_empty_fast_start.ogg",
		}
})
-- Sound: 41
sound.Add({
	name = "wfoly_plr_sh_charlie725_reload_empty_fast_02",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/wfoly_plr_sh_charlie725_reload_empty_fast_open_01.ogg",
		}
})
-- Sound: 42
sound.Add({
	name = "wfoly_plr_sh_charlie725_reload_empty_fast_03",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/wfoly_plr_sh_charlie725_reload_empty_fast_swing.ogg",
		}
})
-- Sound: 43
sound.Add({
	name = "wfoly_plr_sh_charlie725_reload_empty_fast_04",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/wfoly_plr_sh_charlie725_reload_empty_fast_shellsin_01.ogg",
		}
})
-- Sound: 44
sound.Add({
	name = "wfoly_plr_sh_charlie725_reload_empty_fast_05",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/wfoly_plr_sh_charlie725_reload_empty_fast_end.ogg",
		}
})
-- Sound: 45
sound.Add({
	name = "wfoly_plr_sh_charlie725_reload_empty_fast_06",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/wfoly_plr_sh_charlie725_reload_empty_close_01.ogg",
		}
})
-- Sound: 46
sound.Add({
	name = "wfoly_plr_sh_charlie725_reload_empty_fast_scope_01",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/wfoly_plr_sh_charlie725_reload_empty_fast_scope_start.ogg",
		}
})
-- Sound: 47
sound.Add({
	name = "wfoly_plr_sh_charlie725_reload_empty_fast_scope_02",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/wfoly_plr_sh_charlie725_reload_empty_fast_scope_open_01.ogg",
		}
})
-- Sound: 48
sound.Add({
	name = "wfoly_plr_sh_charlie725_reload_empty_fast_scope_03",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/wfoly_plr_sh_charlie725_reload_empty_fast_scope_swing.ogg",
		}
})
-- Sound: 49
sound.Add({
	name = "wfoly_plr_sh_charlie725_reload_empty_fast_scope_04",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/wfoly_plr_sh_charlie725_reload_empty_fast_scope_shellsin_01.ogg",
		}
})
-- Sound: 50
sound.Add({
	name = "wfoly_plr_sh_charlie725_reload_empty_fast_scope_05",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/wfoly_plr_sh_charlie725_reload_empty_fast_scope_end.ogg",
		}
})
-- Sound: 51
sound.Add({
	name = "wfoly_plr_sh_charlie725_reload_empty_fast_scope_06",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/wfoly_plr_sh_charlie725_reload_empty_close_01.ogg",
		}
})
-- Sound: 52
sound.Add({
	name = "wfoly_plr_sh_charlie725_reload_empty_scope_01",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/wfoly_plr_sh_charlie725_reload_empty_scope_start.ogg",
		}
})
-- Sound: 53
sound.Add({
	name = "wfoly_plr_sh_charlie725_reload_empty_scope_02",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/wfoly_plr_sh_charlie725_reload_empty_scope_open_01.ogg",
		}
})
-- Sound: 54
sound.Add({
	name = "wfoly_plr_sh_charlie725_reload_empty_scope_03",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/wfoly_plr_sh_charlie725_reload_empty_scope_swing.ogg",
		}
})
-- Sound: 55
sound.Add({
	name = "wfoly_plr_sh_charlie725_reload_empty_scope_04",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/wfoly_plr_sh_charlie725_reload_empty_scope_shellsin_v2_01.ogg",
		}
})
-- Sound: 56
sound.Add({
	name = "wfoly_plr_sh_charlie725_reload_empty_scope_045",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/wfoly_plr_sh_charlie725_reload_empty_scope_shellsin_v2_02.ogg",
		}
})
-- Sound: 57
sound.Add({
	name = "wfoly_plr_sh_charlie725_reload_empty_scope_05",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/wfoly_plr_sh_charlie725_reload_empty_close_01.ogg",
		}
})
-- Sound: 58
sound.Add({
	name = "wfoly_plr_sh_charlie725_reload_empty_scope_06",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/wfoly_plr_sh_charlie725_reload_empty_scope_end.ogg",
		}
})
-- Sound: 59
sound.Add({
	name = "wfoly_plr_sh_charlie725_reload_fast_01",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/wfoly_plr_sh_charlie725_reload_fast_open_01.ogg",
		}
})
-- Sound: 60
sound.Add({
	name = "wfoly_plr_sh_charlie725_reload_fast_02",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/wfoly_plr_sh_charlie725_reload_fast_start.ogg",
		}
})
-- Sound: 61
sound.Add({
	name = "wfoly_plr_sh_charlie725_reload_fast_03",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/wfoly_plr_sh_charlie725_reload_fast_swing.ogg",
		}
})
-- Sound: 62
sound.Add({
	name = "wfoly_plr_sh_charlie725_reload_fast_04",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/wfoly_plr_sh_charlie725_reload_fast_shellin_01.ogg",
		}
})
-- Sound: 63
sound.Add({
	name = "wfoly_plr_sh_charlie725_reload_fast_05",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/wfoly_plr_sh_charlie725_reload_fast_end.ogg",
		}
})
-- Sound: 64
sound.Add({
	name = "wfoly_plr_sh_charlie725_reload_fast_06",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/wfoly_plr_sh_charlie725_reload_close_01.ogg",
		}
})
-- Sound: 65
sound.Add({
	name = "wfoly_plr_sh_charlie725_reload_fast_scope_01",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/wfoly_plr_sh_charlie725_reload_fast_scope_start.ogg",
		}
})
-- Sound: 66
sound.Add({
	name = "wfoly_plr_sh_charlie725_reload_fast_scope_02",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/wfoly_plr_sh_charlie725_reload_fast_scope_open_01.ogg",
		}
})
-- Sound: 67
sound.Add({
	name = "wfoly_plr_sh_charlie725_reload_fast_scope_03",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/wfoly_plr_sh_charlie725_reload_fast_scope_swing.ogg",
		}
})
-- Sound: 68
sound.Add({
	name = "wfoly_plr_sh_charlie725_reload_fast_scope_04",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/wfoly_plr_sh_charlie725_reload_fast_scope_shellin_01.ogg",
		}
})
-- Sound: 69
sound.Add({
	name = "wfoly_plr_sh_charlie725_reload_fast_scope_05",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/wfoly_plr_sh_charlie725_reload_fast_scope_end.ogg",
		}
})
-- Sound: 70
sound.Add({
	name = "wfoly_plr_sh_charlie725_reload_fast_scope_06",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/wfoly_plr_sh_charlie725_reload_close_01.ogg",
		}
})
-- Sound: 71
sound.Add({
	name = "wfoly_plr_sh_charlie725_reload_scope_01",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/wfoly_plr_sh_charlie725_reload_scope_start.ogg",
		}
})
-- Sound: 72
sound.Add({
	name = "wfoly_plr_sh_charlie725_reload_scope_02",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/wfoly_plr_sh_charlie725_reload_scope_open_01.ogg",
		}
})
-- Sound: 73
sound.Add({
	name = "wfoly_plr_sh_charlie725_reload_scope_03",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/wfoly_plr_sh_charlie725_reload_scope_swing.ogg",
		}
})
-- Sound: 74
sound.Add({
	name = "wfoly_plr_sh_charlie725_reload_scope_04",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/wfoly_plr_sh_charlie725_reload_scope_shellin_01.ogg",
		}
})
-- Sound: 75
sound.Add({
	name = "wfoly_plr_sh_charlie725_reload_scope_05",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/wfoly_plr_sh_charlie725_reload_close_01.ogg",
		}
})
-- Sound: 76
sound.Add({
	name = "wfoly_plr_sh_charlie725_reload_scope_06",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_charlie725/wfoly_plr_sh_charlie725_reload_scope_end.ogg",
		}
})
