-- Generated by GmodSoundGen

-- File: D:\Downloads\important_stuff_v2\Tools\GmodSoundGen_0519\weapon_sm_uzulu.all.lua
-- Total length: 148
sound.Add({
    name =           "ps_wfoly_plr_sm_uzulu_raise_first_01",
    channel =        CHAN_WPNFOLEY +1,
    volume =         1,
    sound = {"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_raise_first_start.ogg"}              
})
sound.Add({
    name =           "ps_wfoly_plr_sm_uzulu_raise_first_02",
    channel =        CHAN_WPNFOLEY +2,
    volume =         1,
    sound = {"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_raise_first_stock.ogg"}              
})
sound.Add({
    name =           "ps_wfoly_plr_sm_uzulu_raise_first_03",
    channel =        CHAN_WPNFOLEY +3,
    volume =         1,
    sound = {"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_raise_first_extend.ogg"}              
})
sound.Add({
    name =           "ps_wfoly_plr_sm_uzulu_raise_first_04",
    channel =        CHAN_WPNFOLEY +4,
    volume =         1,
    sound = {"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_raise_first_end.ogg"}              
})
sound.Add({
    name =           "wfoly_plr_sm_uzulu_raise_first_nostock_01",
    channel =        CHAN_WPNFOLEY +1,
    volume =         1,
    sound = {"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_raise_first_start.ogg"}              
})
sound.Add({
    name =           "wfoly_plr_sm_uzulu_raise_first_nostock_02",
    channel =        CHAN_WPNFOLEY +2,
    volume =         1,
    sound = {"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_charge_01.ogg"}              
})
sound.Add({
    name =           "wfoly_plr_sm_uzulu_raise_first_nostock_03",
    channel =        CHAN_WPNFOLEY +3,
    volume =         1,
    sound = {"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_raise_first_end.ogg"}              
})
-- Sound: 4
sound.Add({
	name = "weap_uzulu_disconnector_plr",
	channel = CHAN_WPNFOLEY + 1,

	volume = 1,
	pitch = {100,100},
	sound = {
		"weapons/uzulu/weap_uzulu_disconnector_plr_01.ogg",
		}
})
-- Sound: 23
sound.Add({
	name = "weap_uzulu_fire_first_plr",
	channel = CHAN_WPNFOLEY + 2,

	volume = 1,
	pitch = {100,100},
	sound = {
		"weapons/uzulu/weap_uzulu_prefire_plr_01.ogg",
		}
})

sound.Add({
	name = "weap_sm_uzulu_ads_down",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/weap_sm_uzulu_ads_down.ogg",
		}
})
-- Sound: 5
sound.Add({
	name = "weap_sm_uzulu_ads_up",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/weap_sm_uzulu_ads_up.ogg",
		}
})
-- Sound: 6
sound.Add({
	name = "weap_sm_uzulu_selector_off",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/selector/weap_sm_uzulu_selector_off.ogg",
		}
})
-- Sound: 7
sound.Add({
	name = "weap_sm_uzulu_selector_on",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/selector/weap_sm_uzulu_selector_on.ogg",
		}
})
-- Sound: 10
sound.Add({
	name = "weap_uzulu_fire_plr",
	channel = CHAN_WEAPON,
	level = 140,
	volume = 1,
	pitch = {80,110},
	sound = 
		"^weapons/uzulu/weap_uzulu_fire_plr_01.wav",
		
})
-- Sound: 15
sound.Add({
	name = "weap_uzulu_sub_fire_plr",
	channel = CHAN_WEAPON,
	volume = 1,
	pitch = {80,110},
	sound = {
		"weapons/uzulu/weap_uzulu1911_fire_plr_01.ogg",
		}
})
-- Sound: 19
sound.Add({
	name = "weap_uzulu_sup_fire_plr",
	channel = CHAN_WEAPON,
	level = 140,
	volume = 1,
	pitch = {100,100},
	sound = {
		"weapons/uzulu/weap_uzulu_sup_fire_plr_01.ogg",
		}
})

-- Sound: 23
sound.Add({
	name = "wfoly_plr_sm_uzulu_drop_01",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_drop_down.ogg",
		}
})
-- Sound: 24
sound.Add({
	name = "wfoly_plr_sm_uzulu_drop_quick_01",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_drop_quick_down.ogg",
		}
})
-- Sound: 25
sound.Add({
	name = "wfoly_plr_sm_uzulu_hybrid_scope_side_off",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/hybrid_scope/wfoly_plr_sm_uzulu_hybrid_scope_side_off.ogg",
		}
})
-- Sound: 26
sound.Add({
	name = "wfoly_plr_sm_uzulu_hybrid_scope_side_on",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/hybrid_scope/wfoly_plr_sm_uzulu_hybrid_scope_side_on.ogg",
		}
})
-- Sound: 27
sound.Add({
	name = "wfoly_plr_sm_uzulu_hybrid_scope_snap_closed",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/hybrid_scope/wfoly_plr_ar_falpha_hybrid_scope_snap_closed.ogg",
		}
})
-- Sound: 28
sound.Add({
	name = "wfoly_plr_sm_uzulu_hybrid_scope_snap_open",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/hybrid_scope/wfoly_plr_ar_falpha_hybrid_scope_snap_open.ogg",
		}
})
-- Sound: 29
sound.Add({
	name = "wfoly_plr_sm_uzulu_hybrid_scope_top_in",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/hybrid_scope/wfoly_plr_sm_uzulu_hybrid_scope_top_in.ogg",
		}
})
-- Sound: 30
sound.Add({
	name = "wfoly_plr_sm_uzulu_hybrid_scope_top_out",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/hybrid_scope/wfoly_plr_sm_uzulu_hybrid_scope_top_out.ogg",
		}
})
-- Sound: 31
sound.Add({
	name = "wfoly_plr_sm_uzulu_idle_active_01",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_idle_active_idle1.ogg",
		}
})
-- Sound: 32
sound.Add({
	name = "wfoly_plr_sm_uzulu_idle_active_02",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_idle_active_idle2.ogg",
		}
})
-- Sound: 33
sound.Add({
	name = "wfoly_plr_sm_uzulu_idle_active_03",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_idle_active_idle3.ogg",
		}
})
-- Sound: 34
sound.Add({
	name = "wfoly_plr_sm_uzulu_idle_active_04",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_idle_active_idle4.ogg",
		}
})
-- Sound: 35
sound.Add({
	name = "wfoly_plr_sm_uzulu_inspect_01",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_inspect_01.ogg",
		}
})
-- Sound: 36
sound.Add({
	name = "wfoly_plr_sm_uzulu_inspect_02",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_inspect_02.ogg",
		}
})
-- Sound: 37
sound.Add({
	name = "wfoly_plr_sm_uzulu_inspect_03",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_inspect_03.ogg",
		}
})
-- Sound: 38
sound.Add({
	name = "wfoly_plr_sm_uzulu_inspect_04",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_inspect_04.ogg",
		}
})
-- Sound: 39
sound.Add({
	name = "wfoly_plr_sm_uzulu_inspect_05",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_inspect_05.ogg",
		}
})
-- Sound: 40
sound.Add({
	name = "wfoly_plr_sm_uzulu_raise_01",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_raise_up.ogg",
		}
})
-- Sound: 41
sound.Add({
	name = "wfoly_plr_sm_uzulu_raise_first_01",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_raise_first_start.ogg",
		}
})
-- Sound: 42
sound.Add({
	name = "wfoly_plr_sm_uzulu_raise_first_02",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_raise_first_stock.ogg",
		}
})
-- Sound: 43
sound.Add({
	name = "wfoly_plr_sm_uzulu_raise_first_03",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_raise_first_extend.ogg",
		}
})
-- Sound: 44
sound.Add({
	name = "wfoly_plr_sm_uzulu_raise_first_04",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_raise_first_end.ogg",
		}
})
-- Sound: 45
sound.Add({
	name = "wfoly_plr_sm_uzulu_raise_quick_01",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_raise_quick_up.ogg",
		}
})
-- Sound: 46
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_01",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_start.ogg",
		}
})
-- Sound: 47
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_02",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_arm.ogg",
		}
})
-- Sound: 48
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_03",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_magout_01.ogg",
		}
})
-- Sound: 49
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_04",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_shake.ogg",
		}
})
-- Sound: 50
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_05",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_magin_01.ogg",
		}
})
-- Sound: 51
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_06",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_rattle.ogg",
		}
})
-- Sound: 52
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_07",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_end.ogg",
		}
})
-- Sound: 53
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_01",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_start.ogg",
		}
})
-- Sound: 54
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_02",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_magout_01.ogg",
		}
})
-- Sound: 55
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_03",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_rattle.ogg",
		}
})
-- Sound: 56
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_04",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_arm.ogg",
		}
})
-- Sound: 57
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_05",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_magin_01.ogg",
		}
})
-- Sound: 58
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_06",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_tilt.ogg",
		}
})
-- Sound: 59
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_07",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_charge_01.ogg",
		}
})
-- Sound: 60
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_08",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_end.ogg",
		}
})
-- Sound: 61
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_fast_01",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_fast_start.ogg",
		}
})
-- Sound: 62
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_fast_02",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_fast_magout_01.ogg",
		}
})
-- Sound: 63
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_fast_03",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_fast_rattle.ogg",
		}
})
-- Sound: 64
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_fast_04",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_fast_arm.ogg",
		}
})
-- Sound: 65
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_fast_05",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_fast_magin_01.ogg",
		}
})
-- Sound: 66
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_fast_06",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_fast_tilt.ogg",
		}
})
-- Sound: 67
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_fast_07",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_fast_charge_01.ogg",
		}
})
-- Sound: 68
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_fast_08",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_fast_end.ogg",
		}
})
-- Sound: 69
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_scope_01",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_scope_start.ogg",
		}
})
-- Sound: 70
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_scope_02",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_scope_magout_01.ogg",
		}
})
-- Sound: 71
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_scope_03",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_scope_rattle.ogg",
		}
})
-- Sound: 72
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_scope_04",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_scope_arm.ogg",
		}
})
-- Sound: 73
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_scope_05",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_scope_magin_01.ogg",
		}
})
-- Sound: 74
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_scope_06",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_scope_tilt.ogg",
		}
})
-- Sound: 75
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_scope_07",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_scope_charge_01.ogg",
		}
})
-- Sound: 76
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_scope_08",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_scope_end.ogg",
		}
})
-- Sound: 77
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_scope_fast_01",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_scope_fast_start.ogg",
		}
})
-- Sound: 78
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_scope_fast_02",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_scope_fast_magout_01.ogg",
		}
})
-- Sound: 79
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_scope_fast_03",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_scope_fast_rattle.ogg",
		}
})
-- Sound: 80
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_scope_fast_04",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_scope_fast_arm.ogg",
		}
})
-- Sound: 81
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_scope_fast_05",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_scope_fast_magin_01.ogg",
		}
})
-- Sound: 82
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_scope_fast_06",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_scope_fast_tilt.ogg",
		}
})
-- Sound: 83
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_scope_fast_07",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_scope_fast_charge_01.ogg",
		}
})
-- Sound: 84
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_scope_fast_08",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_scope_fast_end.ogg",
		}
})
-- Sound: 85
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_xmag_01",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_xmag_start.ogg",
		}
})
-- Sound: 86
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_xmag_02",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_xmag_magout_01.ogg",
		}
})
-- Sound: 87
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_xmag_03",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_xmag_rattle.ogg",
		}
})
-- Sound: 88
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_xmag_04",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_xmag_arm.ogg",
		}
})
-- Sound: 89
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_xmag_05",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_xmag_magin_01.ogg",
		}
})
-- Sound: 90
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_xmag_06",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_xmag_tilt.ogg",
		}
})
-- Sound: 91
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_xmag_07",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_xmag_charge_01.ogg",
		}
})
-- Sound: 92
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_xmag_08",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_xmag_end.ogg",
		}
})
-- Sound: 93
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_xmeg_fast_01",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_xmag_fast_start.ogg",
		}
})
-- Sound: 94
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_xmeg_fast_02",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_xmag_fast_magout_01.ogg",
		}
})
-- Sound: 95
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_xmeg_fast_03",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_xmag_fast_rattle.ogg",
		}
})
-- Sound: 96
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_xmeg_fast_04",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_xmag_fast_arm.ogg",
		}
})
-- Sound: 97
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_xmeg_fast_05",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_xmag_fast_magin_01.ogg",
		}
})
-- Sound: 98
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_xmeg_fast_06",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_xmag_fast_tilt.ogg",
		}
})
-- Sound: 99
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_xmeg_fast_07",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_xmag_fast_charge_01.ogg",
		}
})
-- Sound: 100
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_xmeg_fast_08",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_xmag_fast_end.ogg",
		}
})
-- Sound: 101
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_xxmag_01",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_xxmag_start.ogg",
		}
})
-- Sound: 102
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_xxmag_02",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_xxmag_magout_01.ogg",
		}
})
-- Sound: 103
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_xxmag_03",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_xxmag_rattle.ogg",
		}
})
-- Sound: 104
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_xxmag_04",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_xxmag_arm.ogg",
		}
})
-- Sound: 105
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_xxmag_05",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_xxmag_magin_01.ogg",
		}
})
-- Sound: 106
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_xxmag_06",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_xxmag_tilt.ogg",
		}
})
-- Sound: 107
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_xxmag_07",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_xxmag_charge_01.ogg",
		}
})
-- Sound: 108
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_xxmag_08",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_xxmag_end.ogg",
		}
})
-- Sound: 109
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_xxmeg_fast_01",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_xxmag_fast_start.ogg",
		}
})
-- Sound: 110
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_xxmeg_fast_02",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_xxmag_fast_magout_01.ogg",
		}
})
-- Sound: 111
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_xxmeg_fast_03",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_xxmag_fast_rattle.ogg",
		}
})
-- Sound: 112
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_xxmeg_fast_04",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_xxmag_fast_arm.ogg",
		}
})
-- Sound: 113
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_xxmeg_fast_05",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_xxmag_fast_magin_01.ogg",
		}
})
-- Sound: 114
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_xxmeg_fast_06",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_xxmag_fast_tilt.ogg",
		}
})
-- Sound: 115
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_xxmeg_fast_07",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_xxmag_fast_charge_01.ogg",
		}
})
-- Sound: 116
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_empty_xxmeg_fast_08",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_empty_xxmag_fast_end.ogg",
		}
})
-- Sound: 117
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_fast_01",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_fast_start.ogg",
		}
})
-- Sound: 118
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_fast_02",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_fast_arm.ogg",
		}
})
-- Sound: 119
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_fast_03",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_fast_magout_01.ogg",
		}
})
-- Sound: 120
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_fast_04",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_fast_rattle.ogg",
		}
})
-- Sound: 121
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_fast_05",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_fast_magin_01.ogg",
		}
})
-- Sound: 122
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_fast_06",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_fast_end.ogg",
		}
})
-- Sound: 123
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_xmag_01",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_xmag_start.ogg",
		}
})
-- Sound: 124
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_xmag_02",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_xmag_arm.ogg",
		}
})
-- Sound: 125
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_xmag_03",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_xmag_magout_01.ogg",
		}
})
-- Sound: 126
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_xmag_04",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_xmag_rattle.ogg",
		}
})
-- Sound: 127
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_xmag_05",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_xmag_magin_01.ogg",
		}
})
-- Sound: 128
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_xmag_06",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_xmag_end.ogg",
		}
})
-- Sound: 129
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_xmeg_fast_01",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_xmag_fast_start.ogg",
		}
})
-- Sound: 130
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_xmeg_fast_02",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_xmag_fast_arm.ogg",
		}
})
-- Sound: 131
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_xmeg_fast_03",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_xmag_fast_magout_01.ogg",
		}
})
-- Sound: 132
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_xmeg_fast_04",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_xmag_fast_rattle.ogg",
		}
})
-- Sound: 133
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_xmeg_fast_05",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_xmag_fast_magin_01.ogg",
		}
})
-- Sound: 134
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_xmeg_fast_06",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_xmag_fast_shake.ogg",
		}
})
-- Sound: 135
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_xmeg_fast_07",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_xmag_fast_end.ogg",
		}
})
-- Sound: 136
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_xxmag_01",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_xxmag_start.ogg",
		}
})
-- Sound: 137
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_xxmag_02",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_xxmag_arm.ogg",
		}
})
-- Sound: 138
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_xxmag_03",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_xxmag_magout_01.ogg",
		}
})
-- Sound: 139
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_xxmag_04",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_xxmag_rattle.ogg",
		}
})
-- Sound: 140
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_xxmag_05",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_xxmag_magin_01.ogg",
		}
})
-- Sound: 141
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_xxmag_06",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_xxmag_end.ogg",
		}
})
-- Sound: 142
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_xxmeg_fast_01",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_xxmag_fast_start.ogg",
		}
})
-- Sound: 143
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_xxmeg_fast_02",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_xxmag_fast_arm.ogg",
		}
})
-- Sound: 144
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_xxmeg_fast_03",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_xxmag_fast_magout_01.ogg",
		}
})
-- Sound: 145
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_xxmeg_fast_04",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_xxmag_fast_rattle.ogg",
		}
})
-- Sound: 146
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_xxmeg_fast_05",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_xxmag_fast_magin_01.ogg",
		}
})
-- Sound: 147
sound.Add({
	name = "wfoly_plr_sm_uzulu_reload_xxmeg_fast_06",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_uzulu/wfoly_plr_sm_uzulu_reload_xxmag_fast_end.ogg",
		}
})
