-- Generated by GmodSoundGen

-- File: D:\Downloads\important_stuff_v2\Tools\GmodSoundGen_0519\weapon_sm_mpapa5.all.lua
-- Total length: 71
sound.Add({
    name =           "wfoly_plr_sm_mpapa5_raise_first_01",
    channel =        CHAN_WPNFOLEY +1,
    volume =         1,
    sound = {"reloads/iw8_mpapa5/wfoly_pi_mpapa5_raise_first_mvmnt.ogg"}              
})
sound.Add({
    name =           "wfoly_plr_sm_mpapa5_raise_first_02",
    channel =        CHAN_WPNFOLEY +2,
    volume =         1,
    sound = {"reloads/iw8_mpapa5/wfoly_pi_mpapa5_raise_first_closebolt_01.ogg"}              
})
sound.Add({
    name =           "wfoly_plr_sm_mpapa5_raise_first_03",
    channel =        CHAN_WPNFOLEY +3,
    volume =         1,
    sound = {"reloads/iw8_mpapa5/wfoly_pi_mpapa5_raise_first_end.ogg"}              
})
-- Sound: 22
sound.Add({
	name = "weap_mpapa5_disconnector_plr",
	channel = CHAN_WPNFOLEY + 1,

	volume = 1,
	pitch = {100,100},
	sound = {
		"weapons/mpapa5/weap_mpapa5_disconnector_plr_01.ogg",
		}
})
-- Sound: 23
sound.Add({
	name = "weap_mpapa5_fire_first_plr",
	channel = CHAN_WPNFOLEY + 2,

	volume = 1,
	pitch = {100,100},
	sound = {
		"weapons/mpapa5/weap_mpapa5_fire_first_plr_01.ogg",
		}
})
-- Sound: 10
sound.Add({
	name = "weap_mpapa5_fire_plr_lfe",
	channel = CHAN_WEAPON,
	level = 140,
	volume = 1,
	pitch = {80,110},
	sound = 
		"^weapons/mpapa5/weap_mpapa5_fire_plr_01.wav",
		
})
-- Sound: 14
sound.Add({
	name = "weap_mpapa5_sup_fire_plr_lfe",
	channel = CHAN_WEAPON,
	volume = 1,
	pitch = {80,110},
	sound = {
		"weapons/mpapa5/weap_mpapa5_sup_fire_plr_01.ogg",
		}
})
-- Sound: 17
sound.Add({
	name = "weap_sm_mpapa5_ads_down",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mpapa5/wfoly_sm_mpapa5_ads_down.ogg",
		}
})
-- Sound: 18
sound.Add({
	name = "weap_sm_mpapa5_ads_up",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mpapa5/wfoly_sm_mpapa5_ads_up.ogg",
		}
})
-- Sound: 19
sound.Add({
	name = "weap_sm_mpapa5_selector_off",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/selector/weap_sm_mpapa5_selector_off.ogg",
		}
})
-- Sound: 20
sound.Add({
	name = "weap_sm_mpapa5_selector_on",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/selector/weap_sm_mpapa5_selector_on.ogg",
		}
})
-- Sound: 21
sound.Add({
	name = "wfoly_plr_sm_mpapa5_drop_01",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mpapa5/wfoly_sm_mpapa5_drop.ogg",
		}
})
-- Sound: 22
sound.Add({
	name = "wfoly_plr_sm_mpapa5_drop_quick_01",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mpapa5/wfoly_sm_mpapa5_drop_quick.ogg",
		}
})
-- Sound: 23
sound.Add({
	name = "wfoly_plr_sm_mpapa5_hybrid_scope_side_off",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/hybrid_scope/wfoly_plr_sm_mpapa5_hybrid_scope_side_off.ogg",
		}
})
-- Sound: 24
sound.Add({
	name = "wfoly_plr_sm_mpapa5_hybrid_scope_side_on",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/hybrid_scope/wfoly_plr_sm_mpapa5_hybrid_scope_side_on.ogg",
		}
})
-- Sound: 25
sound.Add({
	name = "wfoly_plr_sm_mpapa5_hybrid_scope_snap_closed",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/hybrid_scope/wfoly_plr_ar_falpha_hybrid_scope_snap_closed.ogg",
		}
})
-- Sound: 26
sound.Add({
	name = "wfoly_plr_sm_mpapa5_hybrid_scope_snap_open",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/hybrid_scope/wfoly_plr_ar_falpha_hybrid_scope_snap_open.ogg",
		}
})
-- Sound: 27
sound.Add({
	name = "wfoly_plr_sm_mpapa5_hybrid_scope_top_in",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/hybrid_scope/wfoly_plr_sm_mpapa5_hybrid_scope_top_in.ogg",
		}
})
-- Sound: 28
sound.Add({
	name = "wfoly_plr_sm_mpapa5_hybrid_scope_top_out",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/hybrid_scope/wfoly_plr_sm_mpapa5_hybrid_scope_top_out.ogg",
		}
})
-- Sound: 29
sound.Add({
	name = "wfoly_plr_sm_mpapa5_inspect_01",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mpapa5/wfoly_sm_mpapa5_inspect_01.ogg",
		}
})
-- Sound: 30
sound.Add({
	name = "wfoly_plr_sm_mpapa5_inspect_02",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mpapa5/wfoly_sm_mpapa5_inspect_02.ogg",
		}
})
-- Sound: 31
sound.Add({
	name = "wfoly_plr_sm_mpapa5_inspect_03",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mpapa5/wfoly_sm_mpapa5_inspect_03.ogg",
		}
})
-- Sound: 32
sound.Add({
	name = "wfoly_plr_sm_mpapa5_inspect_04",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mpapa5/wfoly_sm_mpapa5_inspect_04.ogg",
		}
})
-- Sound: 33
sound.Add({
	name = "wfoly_plr_sm_mpapa5_inspect_05",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mpapa5/wfoly_sm_mpapa5_inspect_05.ogg",
		}
})
-- Sound: 34
sound.Add({
	name = "wfoly_plr_sm_mpapa5_raise_01",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mpapa5/wfoly_sm_mpapa5_raise.ogg",
		}
})
-- Sound: 35
sound.Add({
	name = "wfoly_plr_sm_mpapa5_raise_quick_01",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mpapa5/wfoly_sm_mpapa5_raise_quick.ogg",
		}
})
-- Sound: 36
sound.Add({
	name = "wfoly_plr_sm_mpapa5_reload_01",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mpapa5/wfoly_pi_mpapa5_reload_rotate.ogg",
		}
})
-- Sound: 37
sound.Add({
	name = "wfoly_plr_sm_mpapa5_reload_02",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mpapa5/wfoly_pi_mpapa5_reload_bolt_open.ogg",
		}
})
-- Sound: 38
sound.Add({
	name = "wfoly_plr_sm_mpapa5_reload_03",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mpapa5/wfoly_pi_mpapa5_reload_cloth01.ogg",
		}
})
-- Sound: 39
sound.Add({
	name = "wfoly_plr_sm_mpapa5_reload_04",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mpapa5/wfoly_pi_mpapa5_reload_magout_01.ogg",
		}
})
-- Sound: 40
sound.Add({
	name = "wfoly_plr_sm_mpapa5_reload_05",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mpapa5/wfoly_pi_mpapa5_reload_rattle_01.ogg",
		}
})
-- Sound: 41
sound.Add({
	name = "wfoly_plr_sm_mpapa5_reload_06",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mpapa5/wfoly_sm_mpapa5_reload_magin_v2_01.ogg",
		}
})
-- Sound: 42
sound.Add({
	name = "wfoly_plr_sm_mpapa5_reload_065",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mpapa5/wfoly_sm_mpapa5_reload_magin_v2_02.ogg",
		}
})
-- Sound: 43
sound.Add({
	name = "wfoly_plr_sm_mpapa5_reload_07",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mpapa5/wfoly_pi_mpapa5_reload_rattle_02.ogg",
		}
})
-- Sound: 44
sound.Add({
	name = "wfoly_plr_sm_mpapa5_reload_08",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mpapa5/wfoly_pi_mpapa5_reload_boltclose_01.ogg",
		}
})
-- Sound: 45
sound.Add({
	name = "wfoly_plr_sm_mpapa5_reload_09",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mpapa5/wfoly_pi_mpapa5_reload_cloth02.ogg",
		}
})
-- Sound: 46
sound.Add({
	name = "wfoly_plr_sm_mpapa5_reload_10",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mpapa5/wfoly_pi_mpapa5_reload_end.ogg",
		}
})
-- Sound: 47
sound.Add({
	name = "wfoly_plr_sm_mpapa5_reload_empty_01",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mpapa5/wfoly_pi_mpapa5_reload_empty_rotate.ogg",
		}
})
-- Sound: 48
sound.Add({
	name = "wfoly_plr_sm_mpapa5_reload_empty_02",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mpapa5/wfoly_pi_mpapa5_reload_empty_boltopen_01.ogg",
		}
})
-- Sound: 49
sound.Add({
	name = "wfoly_plr_sm_mpapa5_reload_empty_03",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mpapa5/wfoly_pi_mpapa5_reload_empty_magout_01.ogg",
		}
})
-- Sound: 50
sound.Add({
	name = "wfoly_plr_sm_mpapa5_reload_empty_04",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mpapa5/wfoly_pi_mpapa5_reload_empty_mvmnt.ogg",
		}
})
-- Sound: 51
sound.Add({
	name = "wfoly_plr_sm_mpapa5_reload_empty_05",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mpapa5/wfoly_sm_mpapa5_reload_empty_magin_v2_01.ogg",
		}
})
-- Sound: 52
sound.Add({
	name = "wfoly_plr_sm_mpapa5_reload_empty_055",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mpapa5/wfoly_sm_mpapa5_reload_empty_magin_v2_02.ogg",
		}
})
-- Sound: 53
sound.Add({
	name = "wfoly_plr_sm_mpapa5_reload_empty_06",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mpapa5/wfoly_pi_mpapa5_reload_empty_cloth.ogg",
		}
})
-- Sound: 54
sound.Add({
	name = "wfoly_plr_sm_mpapa5_reload_empty_07",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mpapa5/wfoly_pi_mpapa5_reload_empty_boltclose_01.ogg",
		}
})
-- Sound: 55
sound.Add({
	name = "wfoly_plr_sm_mpapa5_reload_empty_08",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mpapa5/wfoly_pi_mpapa5_reload_empty_end.ogg",
		}
})
-- Sound: 56
sound.Add({
	name = "wfoly_plr_sm_mpapa5_reload_empty_fast_01",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mpapa5/wfoly_pi_mpapa5_reload_empty_fast_rotate.ogg",
		}
})
-- Sound: 57
sound.Add({
	name = "wfoly_plr_sm_mpapa5_reload_empty_fast_02",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mpapa5/wfoly_pi_mpapa5_reload_empty_fast_boltopen_01.ogg",
		}
})
-- Sound: 58
sound.Add({
	name = "wfoly_plr_sm_mpapa5_reload_empty_fast_03",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mpapa5/wfoly_pi_mpapa5_reload_empty_fast_magout_01.ogg",
		}
})
-- Sound: 59
sound.Add({
	name = "wfoly_plr_sm_mpapa5_reload_empty_fast_04",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mpapa5/wfoly_pi_mpapa5_reload_empty_fast_mvmnt.ogg",
		}
})
-- Sound: 60
sound.Add({
	name = "wfoly_plr_sm_mpapa5_reload_empty_fast_05",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mpapa5/wfoly_pi_mpapa5_reload_empty_fast_cloth.ogg",
		}
})
-- Sound: 61
sound.Add({
	name = "wfoly_plr_sm_mpapa5_reload_empty_fast_06",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mpapa5/wfoly_pi_mpapa5_reload_empty_fast_magin_01.ogg",
		}
})
-- Sound: 62
sound.Add({
	name = "wfoly_plr_sm_mpapa5_reload_empty_fast_07",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mpapa5/wfoly_pi_mpapa5_reload_empty_fast_boltclose_01.ogg",
		}
})
-- Sound: 63
sound.Add({
	name = "wfoly_plr_sm_mpapa5_reload_empty_fast_08",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mpapa5/wfoly_pi_mpapa5_reload_empty_fast_end.ogg",
		}
})
-- Sound: 64
sound.Add({
	name = "wfoly_plr_sm_mpapa5_reload_fast_01",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mpapa5/wfoly_sm_mpapa5_reload_fast_openbolt_01.ogg",
		}
})
-- Sound: 65
sound.Add({
	name = "wfoly_plr_sm_mpapa5_reload_fast_02",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mpapa5/wfoly_sm_mpapa5_reload_fast_rotate.ogg",
		}
})
-- Sound: 66
sound.Add({
	name = "wfoly_plr_sm_mpapa5_reload_fast_03",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mpapa5/wfoly_sm_mpapa5_reload_fast_magout_01.ogg",
		}
})
-- Sound: 67
sound.Add({
	name = "wfoly_plr_sm_mpapa5_reload_fast_04",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mpapa5/wfoly_sm_mpapa5_reload_fast_rattle.ogg",
		}
})
-- Sound: 68
sound.Add({
	name = "wfoly_plr_sm_mpapa5_reload_fast_05",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mpapa5/wfoly_sm_mpapa5_reload_fast_magin_01.ogg",
		}
})
-- Sound: 69
sound.Add({
	name = "wfoly_plr_sm_mpapa5_reload_fast_06",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mpapa5/wfoly_sm_mpapa5_reload_fast_end.ogg",
		}
})
-- Sound: 70
sound.Add({
	name = "wfoly_plr_sm_mpapa5_reload_fast_07",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mpapa5/wfoly_sm_mpapa5_reload_fast_closebolt_01.ogg",
		}
})
