-- Generated by GmodSoundGen

-- File: D:\Downloads\important_stuff_v2\Tools\GmodSoundGen_0519\weapon_lm_mkilo3.all.lua
-- Total length: 125

-- Sound: 5
sound.Add({
	name = "weap_lm_mkilo3_ads_down",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_ads_down.ogg",
		}
})
-- Sound: 6
sound.Add({
	name = "weap_lm_mkilo3_ads_up",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_ads_up.ogg",
		}
})
-- Sound: 7
sound.Add({
	name = "weap_lm_mkilo3_selector_off",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/selector/weap_m4_selector_semi_on_01.ogg",
		"foley/selector/weap_m4_selector_semi_on_02.ogg",
		"foley/selector/weap_m4_selector_semi_on_03.ogg",
		}
})
-- Sound: 8
sound.Add({
	name = "weap_lm_mkilo3_selector_on",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/selector/weap_m4_selector_semi_on_01.ogg",
		"foley/selector/weap_m4_selector_semi_on_02.ogg",
		"foley/selector/weap_m4_selector_semi_on_03.ogg",
		}
})
-- Sound: 9
sound.Add({
	name = "weap_mkilo3_dryfire_plr",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"weapons/weap_dryfire_rifle.ogg",
		}
})
-- Sound: 10
sound.Add({
	name = "weap_mkilo3_dryfirst_plr",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"weapons/mike14/weap_mike14_deadtrigger_plr_01.ogg",
		"weapons/mike14/weap_mike14_deadtrigger_plr_02.ogg",
		"weapons/mike14/weap_mike14_deadtrigger_plr_03.ogg",
		"weapons/mike14/weap_mike14_deadtrigger_plr_04.ogg",
		"weapons/mike14/weap_mike14_deadtrigger_plr_05.ogg",
		"weapons/mike14/weap_mike14_deadtrigger_plr_06.ogg",
		"weapons/mike14/weap_mike14_deadtrigger_plr_ads_01.ogg",
		"weapons/mike14/weap_mike14_deadtrigger_plr_ads_02.ogg",
		"weapons/mike14/weap_mike14_deadtrigger_plr_ads_03.ogg",
		"weapons/mike14/weap_mike14_deadtrigger_plr_ads_04.ogg",
		"weapons/mike14/weap_mike14_deadtrigger_plr_ads_05.ogg",
		"weapons/mike14/weap_mike14_deadtrigger_plr_ads_06.ogg",
		}
})
-- Sound: 11
sound.Add({
	name = "weap_mkilo3_fire_plr",
	channel = CHAN_WEAPON,
	level = 140,
	volume = 1,
	pitch = {100,100},
	sound = 
		"^weapons/mkilo3/weap_mkilo3_fire_plr_01.wav",
		
})
-- Sound: 12
sound.Add({
	name = "weap_mkilo3_fire_plr_atmo",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"weapons/atmo/exterior/ar/weap_ar5_fire_plr_atmo_ext1_01.ogg",
		"weapons/atmo/exterior/ar/weap_ar5_fire_plr_atmo_ext1_02.ogg",
		"weapons/atmo/exterior/ar/weap_ar5_fire_plr_atmo_ext1_03.ogg",
		"weapons/atmo/exterior/ar/weap_ar5_fire_plr_atmo_ext1_04.ogg",
		"weapons/atmo/exterior/ar/weap_ar5_fire_plr_atmo_ext1_05.ogg",
		"weapons/atmo/exterior/ar/weap_ar5_fire_plr_atmo_ext1_06.ogg",
		"weapons/atmo/interior/lmg/weap_lmg_fire_plr_atmo_int1_01.ogg",
		"weapons/atmo/interior/lmg/weap_lmg_fire_plr_atmo_int1_02.ogg",
		"weapons/atmo/interior/lmg/weap_lmg_fire_plr_atmo_int1_03.ogg",
		"weapons/atmo/interior/lmg/weap_lmg_fire_plr_atmo_int1_04.ogg",
		"weapons/atmo/interior/lmg/weap_lmg_fire_plr_atmo_int1_05.ogg",
		"weapons/atmo/interior/lmg/weap_lmg_fire_plr_atmo_int1_06.ogg",
		}
})
-- Sound: 13
sound.Add({
	name = "weap_mkilo3_fire_plr_lfe",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"weapons/iw8_kilo121/weap_kilo121_fire_plr_lfe.ogg",
		"weapons/iw8_kilo121/weap_kilo121_fire_plr_lfe.ogg",
		}
})
-- Sound: 15
sound.Add({
	name = "weap_mkilo3_prefire_plr",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"weapons/mkilo3/weap_mkilo3_prefire_plr_01.ogg",
		"weapons/mkilo3/weap_mkilo3_prefire_plr_ads_01.ogg",
		}
})
-- Sound: 16
sound.Add({
	name = "weap_mkilo3_sup_plr",
	channel = CHAN_WEAPON,
	level = 140,
	volume = 1,
	pitch = {100,100},
	sound = 
		"^weapons/mkilo3/weap_mkilo3_sup_plr_01.wav",
		
})
-- Sound: 17
sound.Add({
	name = "weap_mkilo3_sup_plr_atmo",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"weapons/atmo/exterior/dmr_sup/weap_dmr_sup_fire_plr_atmo_ext2_01.ogg",
		"weapons/atmo/exterior/dmr_sup/weap_dmr_sup_fire_plr_atmo_ext2_02.ogg",
		"weapons/atmo/exterior/dmr_sup/weap_dmr_sup_fire_plr_atmo_ext2_03.ogg",
		"weapons/atmo/exterior/dmr_sup/weap_dmr_sup_fire_plr_atmo_ext2_04.ogg",
		"weapons/atmo/exterior/dmr_sup/weap_dmr_sup_fire_plr_atmo_ext2_05.ogg",
		"weapons/atmo/exterior/dmr_sup/weap_dmr_sup_fire_plr_atmo_ext2_06.ogg",
		"weapons/atmo/interior/ar_sup/weap_ar_sup_fire_plr_atmo_int1_01.ogg",
		"weapons/atmo/interior/ar_sup/weap_ar_sup_fire_plr_atmo_int1_02.ogg",
		"weapons/atmo/interior/ar_sup/weap_ar_sup_fire_plr_atmo_int1_03.ogg",
		"weapons/atmo/interior/ar_sup/weap_ar_sup_fire_plr_atmo_int1_04.ogg",
		"weapons/atmo/interior/ar_sup/weap_ar_sup_fire_plr_atmo_int1_05.ogg",
		"weapons/atmo/interior/ar_sup/weap_ar_sup_fire_plr_atmo_int1_06.ogg",
		}
})
-- Sound: 18
sound.Add({
	name = "weap_mkilo3_sup_plr_lfe",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"weapons/mkilo3/weap_mkilo3_sup_plr_lfe.ogg",
		"weapons/mkilo3/weap_mkilo3_sup_plr_lfe.ogg",
		}
})
-- Sound: 20
sound.Add({
	name = "wfoly_plr_lm_mkilo3_raise_first_01",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_raise_first_up.ogg",
		}
})
-- Sound: 21
sound.Add({
	name = "wfoly_plr_lm_mkilo3_raise_first_02",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_raise_first_charge_pull.ogg",
		}
})
-- Sound: 20
sound.Add({
	name = "wfoly_npc_lm_mkilo3_raise_first_03",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_raise_first_charge_push.ogg",
		}
})
-- Sound: 21
sound.Add({
	name = "wfoly_npc_lm_mkilo3_raise_first_04",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_raise_first_charge_end.ogg",
		}
})
-- Sound: 22
sound.Add({
	name = "wfoly_plr_lm_mkilo3_drop_01",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_drop.ogg",
		}
})
-- Sound: 23
sound.Add({
	name = "wfoly_plr_lm_mkilo3_drop_empty_01",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_drop_empty.ogg",
		}
})
-- Sound: 24
sound.Add({
	name = "wfoly_plr_lm_mkilo3_drop_fast_01",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_drop_fast.ogg",
		}
})
-- Sound: 25
sound.Add({
	name = "wfoly_plr_lm_mkilo3_drop_fast_smag_01",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_drop_fast_smag.ogg",
		}
})
-- Sound: 26
sound.Add({
	name = "wfoly_plr_lm_mkilo3_drop_smag_01",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_drop_smag.ogg",
		}
})
-- Sound: 27
sound.Add({
	name = "wfoly_plr_lm_mkilo3_hybrid_scope_side_off",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/hybrid_scope/wfoly_plr_lm_mgolf34_hybrid_side_off.ogg",
		}
})
-- Sound: 28
sound.Add({
	name = "wfoly_plr_lm_mkilo3_hybrid_scope_side_on",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/hybrid_scope/wfoly_plr_lm_mgolf34_hybrid_side_on.ogg",
		}
})
-- Sound: 29
sound.Add({
	name = "wfoly_plr_lm_mkilo3_hybrid_scope_snap_closed",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/hybrid_scope/wfoly_plr_ar_falpha_hybrid_scope_snap_closed.ogg",
		}
})
-- Sound: 30
sound.Add({
	name = "wfoly_plr_lm_mkilo3_hybrid_scope_snap_open",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/hybrid_scope/wfoly_plr_ar_falpha_hybrid_scope_snap_open.ogg",
		}
})
-- Sound: 31
sound.Add({
	name = "wfoly_plr_lm_mkilo3_hybrid_scope_top_in",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/hybrid_scope/wfoly_plr_lm_mgolf34_hybrid_top_in.ogg",
		}
})
-- Sound: 32
sound.Add({
	name = "wfoly_plr_lm_mkilo3_hybrid_scope_top_out",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/hybrid_scope/wfoly_plr_lm_mgolf34_hybrid_top_out.ogg",
		}
})
-- Sound: 33
sound.Add({
	name = "wfoly_plr_lm_mkilo3_idle_active_01",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_idle_active_01.ogg",
		}
})
-- Sound: 34
sound.Add({
	name = "wfoly_plr_lm_mkilo3_idle_active_02",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_idle_active_02.ogg",
		}
})
-- Sound: 35
sound.Add({
	name = "wfoly_plr_lm_mkilo3_idle_active_03",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_idle_active_03.ogg",
		}
})
-- Sound: 36
sound.Add({
	name = "wfoly_plr_lm_mkilo3_idle_active_04",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_idle_active_04.ogg",
		}
})
-- Sound: 37
sound.Add({
	name = "wfoly_plr_lm_mkilo3_idle_active_05",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_idle_active_05.ogg",
		}
})
-- Sound: 38
sound.Add({
	name = "wfoly_plr_lm_mkilo3_idle_active_smag_01",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_idle_active_smag_01.ogg",
		}
})
-- Sound: 39
sound.Add({
	name = "wfoly_plr_lm_mkilo3_idle_active_smag_02",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_idle_active_smag_02.ogg",
		}
})
-- Sound: 40
sound.Add({
	name = "wfoly_plr_lm_mkilo3_idle_active_smag_03",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_idle_active_smag_03.ogg",
		}
})
-- Sound: 41
sound.Add({
	name = "wfoly_plr_lm_mkilo3_idle_active_smag_04",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_idle_active_smag_04.ogg",
		}
})
-- Sound: 42
sound.Add({
	name = "wfoly_plr_lm_mkilo3_idle_active_smag_05",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_idle_active_smag_05.ogg",
		}
})
-- Sound: 43
sound.Add({
	name = "wfoly_plr_lm_mkilo3_inspect_01",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_inspect_01.ogg",
		}
})
-- Sound: 44
sound.Add({
	name = "wfoly_plr_lm_mkilo3_inspect_02",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_inspect_02.ogg",
		}
})
-- Sound: 45
sound.Add({
	name = "wfoly_plr_lm_mkilo3_inspect_03",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_inspect_03.ogg",
		}
})
-- Sound: 46
sound.Add({
	name = "wfoly_plr_lm_mkilo3_inspect_04",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_inspect_04.ogg",
		}
})
-- Sound: 47
sound.Add({
	name = "wfoly_plr_lm_mkilo3_raise_01",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_raise.ogg",
		}
})
-- Sound: 48
sound.Add({
	name = "wfoly_plr_lm_mkilo3_raise_empty_01",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_raise_empty.ogg",
		}
})
-- Sound: 49
sound.Add({
	name = "wfoly_plr_lm_mkilo3_raise_fast_01",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_raise_fast.ogg",
		}
})
-- Sound: 50
sound.Add({
	name = "wfoly_plr_lm_mkilo3_raise_fast_smag_01",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_raise_fast_smag.ogg",
		}
})
-- Sound: 51
sound.Add({
	name = "wfoly_plr_lm_mkilo3_raise_first_03",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_raise_first_charge_push.ogg",
		}
})
-- Sound: 52
sound.Add({
	name = "wfoly_plr_lm_mkilo3_raise_first_04",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_raise_first_charge_end.ogg",
		}
})
-- Sound: 53
sound.Add({
	name = "wfoly_plr_lm_mkilo3_raise_first_smag_02",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_raise_first_smag_charge.ogg",
		}
})
-- Sound: 54
sound.Add({
	name = "wfoly_plr_lm_mkilo3_raise_first_smag_03",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_raise_first_smag_end.ogg",
		}
})
-- Sound: 55
sound.Add({
	name = "wfoly_plr_lm_mkilo3_raise_smag_01",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_raise_smag.ogg",
		}
})
-- Sound: 56
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_01",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_down.ogg",
		}
})
-- Sound: 57
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_02",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_cover_open.ogg",
		}
})
-- Sound: 58
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_03",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_magout.ogg",
		}
})
-- Sound: 59
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_04",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_magup.ogg",
		}
})
-- Sound: 60
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_05",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_magin_01.ogg",
		}
})
-- Sound: 61
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_055",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_magin_02.ogg",
		}
})
-- Sound: 62
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_06",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_magin_load_belt.ogg",
		}
})
-- Sound: 63
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_07",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_cover_close.ogg",
		}
})
-- Sound: 64
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_08",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_end.ogg",
		}
})
-- Sound: 65
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_empty_01",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_empty_down.ogg",
		}
})
-- Sound: 66
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_empty_02",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_empty_charge_pull.ogg",
		}
})
-- Sound: 67
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_empty_03",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_empty_charge_push.ogg",
		}
})
-- Sound: 68
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_empty_04",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_empty_up.ogg",
		}
})
-- Sound: 69
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_empty_05",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_empty_cover_open.ogg",
		}
})
-- Sound: 70
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_empty_06",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_magin_links.ogg",
		}
})
-- Sound: 71
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_empty_07",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_empty_tray_cover.ogg",
		}
})
-- Sound: 72
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_empty_08",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_empty_magout.ogg",
		}
})
-- Sound: 73
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_empty_09",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_empty_magup.ogg",
		}
})
-- Sound: 74
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_empty_10",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_empty_magin_01.ogg",
		}
})
-- Sound: 75
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_empty_105",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_empty_magin_02.ogg",
		}
})
-- Sound: 76
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_empty_11",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_empty_load_belt.ogg",
		}
})
-- Sound: 77
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_empty_12",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_empty_cover_close.ogg",
		}
})
-- Sound: 78
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_empty_13",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_empty_end.ogg",
		}
})
-- Sound: 79
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_empty_fast_01",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_empty_fast_down.ogg",
		}
})
-- Sound: 80
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_empty_fast_02",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_empty_fast_charge_pull.ogg",
		}
})
-- Sound: 81
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_empty_fast_03",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_empty_fast_charge_push.ogg",
		}
})
-- Sound: 82
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_empty_fast_04",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_empty_fast_mvmnt.ogg",
		}
})
-- Sound: 83
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_empty_fast_05",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_empty_fast_cover_open.ogg",
		}
})
-- Sound: 84
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_empty_fast_06",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_empty_fast_magout.ogg",
		}
})
-- Sound: 85
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_empty_fast_07",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_empty_fast_magup.ogg",
		}
})
-- Sound: 86
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_empty_fast_08",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_empty_fast_magin_01.ogg",
		}
})
-- Sound: 87
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_empty_fast_085",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_empty_fast_magin_02.ogg",
		}
})
-- Sound: 88
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_empty_fast_09",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_empty_fast_load_belt.ogg",
		}
})
-- Sound: 89
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_empty_fast_10",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_empty_fast_cover_close.ogg",
		}
})
-- Sound: 90
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_empty_fast_11",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_empty_fast_end.ogg",
		}
})
-- Sound: 91
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_empty_smag_01",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_empty_smag_up.ogg",
		}
})
-- Sound: 92
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_empty_smag_02",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_empty_smag_magout.ogg",
		}
})
-- Sound: 93
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_empty_smag_03",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_empty_smag_maghit.ogg",
		}
})
-- Sound: 94
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_empty_smag_04",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_empty_smag_magin.ogg",
		}
})
-- Sound: 95
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_empty_smag_05",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_empty_smag_magslap.ogg",
		}
})
-- Sound: 96
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_empty_smag_06",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_empty_smag_charge_pull.ogg",
		}
})
-- Sound: 97
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_empty_smag_07",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_empty_smag_charge_push.ogg",
		}
})
-- Sound: 98
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_empty_smag_08",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_empty_smag_end.ogg",
		}
})
-- Sound: 99
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_empty_smag_fast_01",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_empty_fast_smag_up.ogg",
		}
})
-- Sound: 100
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_empty_smag_fast_02",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_empty_fast_smag_magout.ogg",
		}
})
-- Sound: 101
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_empty_smag_fast_03",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_empty_fast_smag_magin_01.ogg",
		}
})
-- Sound: 102
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_empty_smag_fast_035",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_empty_fast_smag_magin_02.ogg",
		}
})
-- Sound: 103
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_empty_smag_fast_04",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_empty_fast_smag_mvmnt.ogg",
		}
})
-- Sound: 104
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_empty_smag_fast_05",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_empty_fast_smag_charge.ogg",
		}
})
-- Sound: 105
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_empty_smag_fast_06",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_empty_fast_smag_end.ogg",
		}
})
-- Sound: 106
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_fast_01",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_fast_up.ogg",
		}
})
-- Sound: 107
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_fast_02",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_fast_cover_open.ogg",
		}
})
-- Sound: 108
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_fast_03",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_fast_magout.ogg",
		}
})
-- Sound: 109
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_fast_04",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_fast_magup.ogg",
		}
})
-- Sound: 110
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_fast_05",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_fast_magin_01.ogg",
		}
})
-- Sound: 111
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_fast_055",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_fast_magin_02.ogg",
		}
})
-- Sound: 112
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_fast_06",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_fast_load_belt.ogg",
		}
})
-- Sound: 113
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_fast_07",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_fast_close_cover.ogg",
		}
})
-- Sound: 114
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_fast_08",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_fast_end.ogg",
		}
})
-- Sound: 115
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_smag_01",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_smag_up.ogg",
		}
})
-- Sound: 116
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_smag_02",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_smag_magout.ogg",
		}
})
-- Sound: 117
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_smag_03",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_smag_maghit.ogg",
		}
})
-- Sound: 118
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_smag_04",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_smag_magin.ogg",
		}
})
-- Sound: 119
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_smag_05",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_smag_end.ogg",
		}
})
-- Sound: 120
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_smag_fast_01",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_smag_fast_up.ogg",
		}
})
-- Sound: 121
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_smag_fast_02",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_smag_fast_magout.ogg",
		}
})
-- Sound: 122
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_smag_fast_03",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_smag_fast_maghit.ogg",
		}
})
-- Sound: 123
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_smag_fast_04",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_smag_fast_magin.ogg",
		}
})
-- Sound: 124
sound.Add({
	name = "wfoly_plr_lm_mkilo3_reload_smag_fast_05",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mkilo3/wfoly_lm_mkilo3_reload_smag_fast_end.ogg",
		}
})
