-- Generated by GmodSoundGen

-- File: D:\Downloads\important_stuff_v2\Tools\GmodSoundGen_0519\weapon_lm_sierrax.all.lua
-- Total length: 111

-- Sound: 10
sound.Add({
	name = "weap_sierrax_fire_plr",
	channel = CHAN_WEAPON,
	level = 140,
	volume = 1,
	pitch = {75,110},
	sound = 
		"^weapons/sierrax/weap_sierrax_fire_plr_01.wav",
		
})
-- Sound: 14
sound.Add({
	name = "weap_sierrax_prefire_plr",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {80,100},
	sound = {
		"weapons/sierrax/weap_sierrax_prefire_plr_01.ogg",
		}
})
-- Sound: 15
sound.Add({
	name = "weap_sierrax_sup_plr",
	channel = CHAN_WPNFOLEY + 6,
	level = 140,
	volume = 1,
	pitch = {75,110},
	sound = 
		"^weapons/sierrax/weap_sierrax_sup_plr_01.wav",
		
})
-- Sound: 25
sound.Add({
	name = "wfoly_plr_lm_sierrax_drop_01",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_drop.ogg",
		}
})
-- Sound: 26
sound.Add({
	name = "wfoly_plr_lm_sierrax_drop_fast_01",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_drop_fast.ogg",
		}
})
-- Sound: 27
sound.Add({
	name = "wfoly_plr_lm_sierrax_inspect_01",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_inspect_lift.ogg",
		}
})
-- Sound: 28
sound.Add({
	name = "wfoly_plr_lm_sierrax_inspect_02",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_inspect_rotate.ogg",
		}
})
-- Sound: 29
sound.Add({
	name = "wfoly_plr_lm_sierrax_inspect_03",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_inspect_lower.ogg",
		}
})
-- Sound: 30
sound.Add({
	name = "wfoly_plr_lm_sierrax_inspect_04",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_inspect_end.ogg",
		}
})
-- Sound: 31
sound.Add({
	name = "wfoly_plr_lm_sierrax_raise_01",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_raise.ogg",
		}
})


sound.Add({
	name = "wfoly_plr_lm_sierrax_raise_first_01",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_raise_first_lift.ogg",
		}
})
sound.Add({
	name = "wfoly_plr_lm_sierrax_raise_first_02",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_raise_first_coverplate.ogg",
		}
})
sound.Add({
	name = "wfoly_plr_lm_sierrax_raise_first_03",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_raise_first_end.ogg",
		}
})
-- Sound: 32
sound.Add({
	name = "wfoly_plr_lm_sierrax_raise_fast_01",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_raise_fast.ogg",
		}
})
-- Sound: 33
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_01",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_lift.ogg",
		}
})
-- Sound: 34
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_02",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_coveropen.ogg",
		}
})
-- Sound: 35
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_03",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_magout.ogg",
		}
})
-- Sound: 36
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_04",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_rotate.ogg",
		}
})
-- Sound: 37
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_05",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_maghit.ogg",
		}
})
-- Sound: 38
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_06",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_magin.ogg",
		}
})
-- Sound: 39
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_07",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_beltpull.ogg",
		}
})
-- Sound: 40
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_08",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_bullets.ogg",
		}
})
-- Sound: 41
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_09",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_closecover.ogg",
		}
})
-- Sound: 42
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_10",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_end.ogg",
		}
})
-- Sound: 43
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_empty_01",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_empty_lift.ogg",
		}
})
-- Sound: 44
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_empty_02",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_empty_charge.ogg",
		}
})
-- Sound: 45
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_empty_03",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_empty_coveropen.ogg",
		}
})
-- Sound: 46
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_empty_04",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_empty_magout.ogg",
		}
})
-- Sound: 47
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_empty_05",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_empty_adjust.ogg",
		}
})
-- Sound: 48
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_empty_06",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_empty_magup.ogg",
		}
})
-- Sound: 49
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_empty_07",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_empty_maghit.ogg",
		}
})
-- Sound: 50
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_empty_08",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_empty_magin.ogg",
		}
})
-- Sound: 51
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_empty_09",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_empty_bullets.ogg",
		}
})
-- Sound: 52
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_empty_10",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_empty_coverclose.ogg",
		}
})
-- Sound: 53
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_empty_11",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_empty_end.ogg",
		}
})
-- Sound: 54
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_empty_fast_01",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_empty_fast_lift.ogg",
		}
})
-- Sound: 55
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_empty_fast_02",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_empty_fast_charge.ogg",
		}
})
-- Sound: 56
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_empty_fast_03",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_empty_fast_coveropen.ogg",
		}
})
-- Sound: 57
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_empty_fast_04",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_empty_fast_magout.ogg",
		}
})
-- Sound: 58
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_empty_fast_05",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_empty_fast_adjust.ogg",
		}
})
-- Sound: 59
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_empty_fast_06",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_empty_fast_magup.ogg",
		}
})
-- Sound: 60
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_empty_fast_07",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_empty_fast_magin.ogg",
		}
})
-- Sound: 61
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_empty_fast_08",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_empty_fast_beltpull.ogg",
		}
})
-- Sound: 62
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_empty_fast_09",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_empty_fast_coverclose.ogg",
		}
})
-- Sound: 63
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_empty_fast_10",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_empty_fast_end.ogg",
		}
})
-- Sound: 64
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_empty_fast_xmag_01",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_empty_fast_xmag_rattle.ogg",
		}
})
-- Sound: 65
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_empty_fast_xmag_02",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_empty_fast_xmag_charge.ogg",
		}
})
-- Sound: 66
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_empty_fast_xmag_03",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_empty_fast_xmag_coveropen.ogg",
		}
})
-- Sound: 67
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_empty_fast_xmag_04",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_empty_fast_xmag_magout.ogg",
		}
})
-- Sound: 68
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_empty_fast_xmag_05",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_empty_fast_xmag_mvmnt.ogg",
		}
})
-- Sound: 69
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_empty_fast_xmag_06",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_empty_fast_xmag_maghit.ogg",
		}
})
-- Sound: 70
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_empty_fast_xmag_07",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_empty_fast_xmag_magin.ogg",
		}
})
-- Sound: 71
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_empty_fast_xmag_08",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_empty_fast_xmag_bullets.ogg",
		}
})
-- Sound: 72
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_empty_fast_xmag_09",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_empty_fast_xmag_coverclose.ogg",
		}
})
-- Sound: 73
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_empty_fast_xmag_10",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_empty_fast_xmag_end.ogg",
		}
})
-- Sound: 74
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_empty_xmag_01",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_empty_xmag_lift.ogg",
		}
})
-- Sound: 75
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_empty_xmag_02",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_empty_xmag_charge.ogg",
		}
})
-- Sound: 76
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_empty_xmag_03",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_empty_xmag_coveropen.ogg",
		}
})
-- Sound: 77
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_empty_xmag_04",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_empty_xmag_magout.ogg",
		}
})
-- Sound: 78
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_empty_xmag_05",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_empty_xmag_adjust.ogg",
		}
})
-- Sound: 79
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_empty_xmag_06",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_empty_xmag_magup.ogg",
		}
})
-- Sound: 80
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_empty_xmag_07",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_empty_xmag_magin.ogg",
		}
})
-- Sound: 81
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_empty_xmag_08",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_empty_xmag_bullets.ogg",
		}
})
-- Sound: 82
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_empty_xmag_09",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_empty_xmag_coverclose.ogg",
		}
})
-- Sound: 83
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_empty_xmag_10",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_empty_xmag_end.ogg",
		}
})
-- Sound: 84
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_fast_01",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_fast_lift.ogg",
		}
})
-- Sound: 85
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_fast_02",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_fast_coveropen.ogg",
		}
})
-- Sound: 86
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_fast_03",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_fast_magout.ogg",
		}
})
-- Sound: 87
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_fast_04",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_fast_up.ogg",
		}
})
-- Sound: 88
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_fast_05",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_fast_magin.ogg",
		}
})
-- Sound: 89
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_fast_06",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_fast_bullets.ogg",
		}
})
-- Sound: 90
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_fast_07",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_fast_coverclose.ogg",
		}
})
-- Sound: 91
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_fast_08",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_fast_end.ogg",
		}
})
-- Sound: 92
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_fast_xmag_01",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_fast_xmag_lower.ogg",
		}
})
-- Sound: 93
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_fast_xmag_02",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_fast_xmag_coveropen.ogg",
		}
})
-- Sound: 94
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_fast_xmag_03",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_fast_xmag_magout.ogg",
		}
})
-- Sound: 95
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_fast_xmag_04",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_fast_xmag_lift.ogg",
		}
})
-- Sound: 96
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_fast_xmag_05",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_fast_xmag_maghit.ogg",
		}
})
-- Sound: 97
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_fast_xmag_06",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_fast_xmag_magin.ogg",
		}
})
-- Sound: 98
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_fast_xmag_07",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_fast_xmag_bullets.ogg",
		}
})
-- Sound: 99
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_fast_xmag_08",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_fast_xmag_coverclose.ogg",
		}
})
-- Sound: 100
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_fast_xmag_09",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_fast_xmag_end.ogg",
		}
})
-- Sound: 101
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_xmag_01",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_xmag_lower.ogg",
		}
})
-- Sound: 102
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_xmag_02",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_xmag_coveropen.ogg",
		}
})
-- Sound: 103
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_xmag_03",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_xmag_magout.ogg",
		}
})
-- Sound: 104
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_xmag_04",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_xmag_lift.ogg",
		}
})
-- Sound: 105
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_xmag_05",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_xmag_maghit.ogg",
		}
})
-- Sound: 106
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_xmag_06",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_xmag_magin.ogg",
		}
})
-- Sound: 107
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_xmag_07",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_xmag_beltpull.ogg",
		}
})
-- Sound: 108
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_xmag_08",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_xmag_bullets.ogg",
		}
})
-- Sound: 109
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_xmag_09",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_xmag_coverclose.ogg",
		}
})
-- Sound: 110
sound.Add({
	name = "wfoly_plr_lm_sierrax_reload_xmag_10",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_sierrax/wfoly_lm_sierrax_reload_xmag_end.ogg",
		}
})
