-- Generated by GmodSoundGen

-- File: D:\Downloads\important_stuff_v2\Tools\GmodSoundGen_0519\weapon_lm_slima.all.sabs.lua
-- Total length: 184

-- Sound: 0
sound.Add({
	name = "Name",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"File.ogg",
		}
})
-- Sound: 1
sound.Add({
	name = "# Note: Secondary is triggered by this alias",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		".ogg",
		}
})
-- Sound: 2
sound.Add({
	name = "# Note: There are other settings that cannot be pulled",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		".ogg",
		}
})
-- Sound: 3
sound.Add({
	name = "mount_enter_side_slima_vestlight_plr",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/mount/mount_enter_side_pkilo_vestlight_plr.ogg",
		}
})
-- Sound: 4
sound.Add({
	name = "mount_enter_top_slima_vestlight_plr",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/mount/mount_enter_top_pkilo_vestlight_plr.ogg",
		}
})
-- Sound: 5
sound.Add({
	name = "mount_exit_side_slima_vestlight_plr",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/mount/mount_exit_side_pkilo_vestlight_plr.ogg",
		}
})
-- Sound: 6
sound.Add({
	name = "mount_exit_top_slima_vestlight_plr",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/mount/mount_exit_top_pkilo_vestlight_plr.ogg",
		}
})
-- Sound: 7
sound.Add({
	name = "weap_lm_slima_ads_down",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_lm_pkilo_ads_down.ogg",
		}
})
-- Sound: 8
sound.Add({
	name = "weap_lm_slima_ads_up",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_lm_pkilo_ads_up.ogg",
		}
})
-- Sound: 10
sound.Add({
	name = "weap_slima_fire_prefire_plr",
	channel = CHAN_WPNFOLEY,
	volume = 1,
	pitch = {100,100},
	sound = {
		"weapons/slima/weap_slima_prefire_plr_01.ogg",
		}
})
-- Sound: 14
sound.Add({
	name = "weap_slima_fire_plr",
	channel = CHAN_WEAPON,
	level = 140,
	volume = 1,
	pitch = {80,110},
	sound = 
		"^weapons/slima/weap_slima_fire_plr_01.wav",
		
})
-- Sound: 19
sound.Add({
	name = "weap_slima_sup_plr",
	channel = CHAN_WEAPON,
	level = 140,
	volume = 1,
	pitch = {80,110},
	sound = 
		"^weapons/slima/weap_slima_sup_plr_01.wav",
		
})
-- Sound: 21
sound.Add({
	name = "wfoly_plr_lm_slima_hybrid_scope_side_off",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/hybrid_scope/wfoly_plr_lm_pkilo_hybrid_side_off.ogg",
		}
})
-- Sound: 22
sound.Add({
	name = "wfoly_plr_lm_slima_hybrid_scope_side_on",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/hybrid_scope/wfoly_plr_lm_pkilo_hybrid_side_on.ogg",
		}
})
-- Sound: 23
sound.Add({
	name = "wfoly_plr_lm_slima_hybrid_scope_snap_closed",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/hybrid_scope/wfoly_plr_ar_falpha_hybrid_scope_snap_closed.ogg",
		}
})
-- Sound: 24
sound.Add({
	name = "wfoly_plr_lm_slima_hybrid_scope_snap_open",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/hybrid_scope/wfoly_plr_ar_falpha_hybrid_scope_snap_open.ogg",
		}
})
-- Sound: 25
sound.Add({
	name = "wfoly_plr_lm_slima_hybrid_scope_top_in",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/hybrid_scope/wfoly_plr_lm_pkilo_hybrid_top_in.ogg",
		}
})
-- Sound: 26
sound.Add({
	name = "wfoly_plr_lm_slima_hybrid_scope_top_out",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/hybrid_scope/wfoly_plr_lm_pkilo_hybrid_top_out.ogg",
		}
})
-- Sound: 27
sound.Add({
	name = "wfoly_plr_lm_slima338_drop_01",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_drop.ogg",
		}
})
-- Sound: 28
sound.Add({
	name = "wfoly_plr_lm_slima338_drop_quick_01",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_drop_quick.ogg",
		}
})
-- Sound: 29
sound.Add({
	name = "wfoly_plr_lm_slima338_fire_switch_off_01",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_fire_switch_off.ogg",
		}
})
-- Sound: 30
sound.Add({
	name = "wfoly_plr_lm_slima338_fire_switch_on_01",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_fire_switch_on.ogg",
		}
})
-- Sound: 31
sound.Add({
	name = "wfoly_plr_lm_slima338_idle_active_01",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_idle_active_01.ogg",
		}
})
-- Sound: 32
sound.Add({
	name = "wfoly_plr_lm_slima338_idle_active_02",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_idle_active_02.ogg",
		}
})
-- Sound: 33
sound.Add({
	name = "wfoly_plr_lm_slima338_idle_active_03",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_idle_active_03.ogg",
		}
})
-- Sound: 34
sound.Add({
	name = "wfoly_plr_lm_slima338_idle_active_04",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_idle_active_04.ogg",
		}
})
-- Sound: 35
sound.Add({
	name = "wfoly_plr_lm_slima338_inspect_01",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_inspect_lower.ogg",
		}
})
-- Sound: 36
sound.Add({
	name = "wfoly_plr_lm_slima338_inspect_02",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_inspect_top_cover_open.ogg",
		}
})
-- Sound: 37
sound.Add({
	name = "wfoly_plr_lm_slima338_inspect_03",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_inspect_top_cover_close.ogg",
		}
})
-- Sound: 38
sound.Add({
	name = "wfoly_plr_lm_slima338_inspect_04",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_inspect_lift.ogg",
		}
})
-- Sound: 39
sound.Add({
	name = "wfoly_plr_lm_slima338_inspect_05",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_inspect_rotate.ogg",
		}
})
-- Sound: 40
sound.Add({
	name = "wfoly_plr_lm_slima338_inspect_06",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_inspect_end.ogg",
		}
})
-- Sound: 41
sound.Add({
	name = "wfoly_plr_lm_slima338_inspect_smag_01",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_inspect_smag_lower.ogg",
		}
})
-- Sound: 42
sound.Add({
	name = "wfoly_plr_lm_slima338_inspect_smag_02",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_inspect_smag_top_cover_open.ogg",
		}
})
-- Sound: 43
sound.Add({
	name = "wfoly_plr_lm_slima338_inspect_smag_03",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_inspect_smag_top_cover_close.ogg",
		}
})
-- Sound: 44
sound.Add({
	name = "wfoly_plr_lm_slima338_inspect_smag_04",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_inspect_smag_lift.ogg",
		}
})
-- Sound: 45
sound.Add({
	name = "wfoly_plr_lm_slima338_inspect_smag_05",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_inspect_smag_rotate.ogg",
		}
})
-- Sound: 46
sound.Add({
	name = "wfoly_plr_lm_slima338_inspect_smag_06",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_inspect_smag_end.ogg",
		}
})
-- Sound: 47
sound.Add({
	name = "wfoly_plr_lm_slima338_inspect_xmag_01",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_inspect_xmag_lower.ogg",
		}
})
-- Sound: 48
sound.Add({
	name = "wfoly_plr_lm_slima338_inspect_xmag_02",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_inspect_xmag_top_cover_open.ogg",
		}
})
-- Sound: 49
sound.Add({
	name = "wfoly_plr_lm_slima338_inspect_xmag_03",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_inspect_xmag_top_cover_close.ogg",
		}
})
-- Sound: 50
sound.Add({
	name = "wfoly_plr_lm_slima338_inspect_xmag_04",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_inspect_xmag_lift.ogg",
		}
})
-- Sound: 51
sound.Add({
	name = "wfoly_plr_lm_slima338_inspect_xmag_05",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_inspect_xmag_rotate.ogg",
		}
})
-- Sound: 52
sound.Add({
	name = "wfoly_plr_lm_slima338_inspect_xmag_06",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_inspect_xmag_end.ogg",
		}
})
-- Sound: 53
sound.Add({
	name = "wfoly_plr_lm_slima338_raise_01",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_raise.ogg",
		}
})
sound.Add({
	name = "wfoly_plr_lm_slima338_raise_first_01",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_raise_first_lift.ogg",
		}
})
sound.Add({
	name = "wfoly_plr_lm_slima338_raise_first_02",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_raise_first_bolt_pull.ogg",
		}
})
sound.Add({
	name = "wfoly_plr_lm_slima338_raise_first_03",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_raise_first_bolt_close.ogg",
		}
})
-- Sound: 54
sound.Add({
	name = "wfoly_plr_lm_slima338_raise_first_04",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_raise_first_end.ogg",
		}
})
-- Sound: 55
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_01",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_lower.ogg",
		}
})
-- Sound: 56
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_02",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_top_cover_open.ogg",
		}
})
-- Sound: 57
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_03",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_clean_tray.ogg",
		}
})
-- Sound: 58
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_04",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_arm_down.ogg",
		}
})
-- Sound: 59
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_05",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_magout.ogg",
		}
})
-- Sound: 60
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_06",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_lift.ogg",
		}
})
-- Sound: 61
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_07",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_maghit.ogg",
		}
})
-- Sound: 62
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_08",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_magin.ogg",
		}
})
-- Sound: 63
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_09",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_bullets_into_tray.ogg",
		}
})
-- Sound: 64
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_10",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_top_cover_close.ogg",
		}
})
-- Sound: 65
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_11",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_end.ogg",
		}
})
-- Sound: 66
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_01",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_lower.ogg",
		}
})
-- Sound: 67
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_02",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_botl_pull.ogg",
		}
})
-- Sound: 68
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_03",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_botl_close.ogg",
		}
})
-- Sound: 69
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_04",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_settle.ogg",
		}
})
-- Sound: 70
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_05",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_top_cover_open.ogg",
		}
})
-- Sound: 71
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_06",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_clean_tray.ogg",
		}
})
-- Sound: 72
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_07",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_lift.ogg",
		}
})
-- Sound: 73
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_08",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_magout.ogg",
		}
})
-- Sound: 74
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_09",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_maghit.ogg",
		}
})
-- Sound: 75
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_10",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_magin.ogg",
		}
})
-- Sound: 76
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_11",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_bullets_into_tray.ogg",
		}
})
-- Sound: 77
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_12",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_top_cover_close.ogg",
		}
})
-- Sound: 78
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_13",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_end.ogg",
		}
})
-- Sound: 79
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_fast_01",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_fast_lower.ogg",
		}
})
-- Sound: 80
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_fast_02",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_fast_bolt_pull.ogg",
		}
})
-- Sound: 81
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_fast_03",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_fast_bolt_close.ogg",
		}
})
-- Sound: 82
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_fast_04",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_fast_top_cover_pop.ogg",
		}
})
-- Sound: 83
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_fast_05",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_fast_magout.ogg",
		}
})
-- Sound: 84
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_fast_06",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_fast_maghit.ogg",
		}
})
-- Sound: 85
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_fast_07",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_fast_magin.ogg",
		}
})
-- Sound: 86
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_fast_08",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_fast_bullets_into_tray.ogg",
		}
})
-- Sound: 87
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_fast_09",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_fast_top_cover_close.ogg",
		}
})
-- Sound: 88
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_fast_10",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_fast_end.ogg",
		}
})
-- Sound: 89
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_fast_smag_01",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_fast_smag_lower.ogg",
		}
})
-- Sound: 90
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_fast_smag_02",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_fast_smag_bolt_pull.ogg",
		}
})
-- Sound: 91
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_fast_smag_03",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_fast_smag_bolt_close.ogg",
		}
})
-- Sound: 92
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_fast_smag_04",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_fast_smag_top_cover_open.ogg",
		}
})
-- Sound: 93
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_fast_smag_05",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_fast_smag_tray_open.ogg",
		}
})
-- Sound: 94
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_fast_smag_06",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_fast_smag_tray_close.ogg",
		}
})
-- Sound: 95
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_fast_smag_07",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_fast_smag_magout.ogg",
		}
})
-- Sound: 96
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_fast_smag_08",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_fast_smag_maghit.ogg",
		}
})
-- Sound: 97
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_fast_smag_09",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_fast_smag_magin.ogg",
		}
})
-- Sound: 98
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_fast_smag_10",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_fast_smag_bullets_into_tray.ogg",
		}
})
-- Sound: 99
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_fast_xmag_01",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_fast_xmag_lower.ogg",
		}
})
-- Sound: 100
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_fast_xmag_02",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_fast_xmag_bolt_pull.ogg",
		}
})
-- Sound: 101
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_fast_xmag_03",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_fast_xmag_bolt_close.ogg",
		}
})
-- Sound: 102
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_fast_xmag_04",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_fast_xmag_top_cover_pop.ogg",
		}
})
-- Sound: 103
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_fast_xmag_05",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_fast_xmag_magout.ogg",
		}
})
-- Sound: 104
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_fast_xmag_06",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_fast_xmag_maghit.ogg",
		}
})
-- Sound: 105
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_fast_xmag_07",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_fast_xmag_magin.ogg",
		}
})
-- Sound: 106
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_fast_xmag_08",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_fast_xmag_bullets_into_tray.ogg",
		}
})
-- Sound: 107
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_fast_xmag_09",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_fast_xmag_top_cover_close.ogg",
		}
})
-- Sound: 108
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_fast_xmag_10",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_fast_xmag_end.ogg",
		}
})
-- Sound: 109
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_smag_01",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_smag_lower.ogg",
		}
})
-- Sound: 110
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_smag_02",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_smag_bolt_pull.ogg",
		}
})
-- Sound: 111
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_smag_03",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_smag_bolt_close.ogg",
		}
})
-- Sound: 112
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_smag_04",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_smag_top_cover_pop.ogg",
		}
})
-- Sound: 113
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_smag_05",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_smag_magout.ogg",
		}
})
-- Sound: 114
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_smag_06",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_smag_maghit.ogg",
		}
})
-- Sound: 115
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_smag_07",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_smag_magin.ogg",
		}
})
-- Sound: 116
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_smag_08",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_smag_bullets_into_tray.ogg",
		}
})
-- Sound: 117
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_smag_09",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_smag_top_cover_close.ogg",
		}
})
-- Sound: 118
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_smag_10",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_smag_end.ogg",
		}
})
-- Sound: 119
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_xmag_01",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_xmag_lower.ogg",
		}
})
-- Sound: 120
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_xmag_02",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_xmag_bolt_pull.ogg",
		}
})
-- Sound: 121
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_xmag_03",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_xmag_bolt_close.ogg",
		}
})
-- Sound: 122
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_xmag_04",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_xmag_top_cover_open.ogg",
		}
})
-- Sound: 123
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_xmag_05",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_xmag_tray_open.ogg",
		}
})
-- Sound: 124
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_xmag_06",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_xmag_tray_close.ogg",
		}
})
-- Sound: 125
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_xmag_07",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_xmag_magout.ogg",
		}
})
-- Sound: 126
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_xmag_08",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_xmag_maghit.ogg",
		}
})
-- Sound: 127
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_xmag_09",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_xmag_magin.ogg",
		}
})
-- Sound: 128
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_xmag_10",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_xmag_bullets_into_tray.ogg",
		}
})
-- Sound: 129
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_xmag_11",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_xmag_top_cover_close.ogg",
		}
})
-- Sound: 130
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_empty_xmag_12",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_empty_xmag_end.ogg",
		}
})
-- Sound: 131
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_fast_01",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_fast_lower.ogg",
		}
})
-- Sound: 132
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_fast_02",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_fast_top_cover_open.ogg",
		}
})
-- Sound: 133
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_fast_03",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_fast_clean_tray.ogg",
		}
})
-- Sound: 134
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_fast_04",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_fast_magout.ogg",
		}
})
-- Sound: 135
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_fast_05",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_fast_raise.ogg",
		}
})
-- Sound: 136
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_fast_06",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_fast_maghit.ogg",
		}
})
-- Sound: 137
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_fast_07",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_fast_magin.ogg",
		}
})
-- Sound: 138
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_fast_08",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_fast_bullets_into_tray.ogg",
		}
})
-- Sound: 139
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_fast_09",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_fast_top_cover_close.ogg",
		}
})
-- Sound: 140
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_fast_10",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_fast_end.ogg",
		}
})
-- Sound: 141
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_fast_smag_01",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_fast_smag_lower.ogg",
		}
})
-- Sound: 142
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_fast_smag_02",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_fast_smag_top_cover_open.ogg",
		}
})
-- Sound: 143
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_fast_smag_03",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_fast_smag_clean_tray.ogg",
		}
})
-- Sound: 144
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_fast_smag_04",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_fast_smag_magout.ogg",
		}
})
-- Sound: 145
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_fast_smag_05",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_fast_smag_maghit.ogg",
		}
})
-- Sound: 146
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_fast_smag_06",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_fast_smag_magin.ogg",
		}
})
-- Sound: 147
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_fast_smag_07",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_fast_smag_bullets_into_tray.ogg",
		}
})
-- Sound: 148
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_fast_smag_08",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_fast_smag_top_cover_close.ogg",
		}
})
-- Sound: 149
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_fast_smag_09",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_fast_smag_end.ogg",
		}
})
-- Sound: 150
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_fast_xmag_01",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_fast_xmag_lower.ogg",
		}
})
-- Sound: 151
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_fast_xmag_02",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_fast_xmag_top_cover_pop.ogg",
		}
})
-- Sound: 152
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_fast_xmag_03",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_fast_xmag_clean_tray.ogg",
		}
})
-- Sound: 153
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_fast_xmag_04",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_fast_xmag_magout.ogg",
		}
})
-- Sound: 154
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_fast_xmag_05",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_fast_xmag_raise.ogg",
		}
})
-- Sound: 155
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_fast_xmag_06",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_fast_xmag_maghit.ogg",
		}
})
-- Sound: 156
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_fast_xmag_07",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_fast_xmag_magin.ogg",
		}
})
-- Sound: 157
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_fast_xmag_08",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_fast_xmag_bullets_into_tray.ogg",
		}
})
-- Sound: 158
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_fast_xmag_09",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_fast_xmag_top_cover_close.ogg",
		}
})
-- Sound: 159
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_fast_xmag_10",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_fast_xmag_end.ogg",
		}
})
-- Sound: 160
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_smag_01",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_smag_lower.ogg",
		}
})
-- Sound: 161
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_smag_02",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_smag_top_cover_open.ogg",
		}
})
-- Sound: 162
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_smag_03",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_smag_clean_tray.ogg",
		}
})
-- Sound: 163
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_smag_04",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_smag_tray_open.ogg",
		}
})
-- Sound: 164
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_smag_05",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_smag_tray_close.ogg",
		}
})
-- Sound: 165
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_smag_06",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_smag_magout.ogg",
		}
})
-- Sound: 166
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_smag_07",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_smag_maghit.ogg",
		}
})
-- Sound: 167
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_smag_08",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_smag_magin.ogg",
		}
})
-- Sound: 168
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_smag_09",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_smag_bullets_into_tray.ogg",
		}
})
-- Sound: 169
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_smag_10",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_smag_top_cover_close.ogg",
		}
})
-- Sound: 170
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_smag_11",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_smag_end.ogg",
		}
})
-- Sound: 171
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_xmag_01",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_xmag_lower.ogg",
		}
})
-- Sound: 172
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_xmag_02",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_xmag_top_cover_open.ogg",
		}
})
-- Sound: 173
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_xmag_03",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_xmag_clean_tray.ogg",
		}
})
-- Sound: 174
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_xmag_04",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_xmag_open_tray.ogg",
		}
})
-- Sound: 175
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_xmag_05",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_xmag_close_tray.ogg",
		}
})
-- Sound: 176
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_xmag_06",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_xmag_magout.ogg",
		}
})
-- Sound: 177
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_xmag_07",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_xmag_raise.ogg",
		}
})
-- Sound: 178
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_xmag_08",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_xmag_maghit.ogg",
		}
})
-- Sound: 179
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_xmag_09",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_xmag_magin.ogg",
		}
})
-- Sound: 180
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_xmag_10",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_xmag_settle.ogg",
		}
})
-- Sound: 181
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_xmag_11",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_xmag_bullets_into_tray.ogg",
		}
})
-- Sound: 182
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_xmag_12",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_xmag_top_cover_close.ogg",
		}
})
-- Sound: 183
sound.Add({
	name = "wfoly_plr_lm_slima338_reload_xmag_13",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_slima338/wfoly_lm_slima_reload_xmag_end.ogg",
		}
})
