-- Generated by GmodSoundGen

-- File: D:\Downloads\important_stuff_v2\Tools\GmodSoundGen_0519\weapon_lm_kilo121.all.lua
-- Total length: 92

-- Sound: 0
sound.Add({
	name = "mount_enter_side_kilo121_vestlight_plr",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/mount/mount_enter_side_kilo121_vestlight_plr.ogg",
		}
})
-- Sound: 1
sound.Add({
	name = "mount_enter_top_kilo121_vestlight_plr",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/mount/mount_enter_top_kilo121_vestlight_plr.ogg",
		}
})
-- Sound: 2
sound.Add({
	name = "mount_exit_side_kilo121_vestlight_plr",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/mount/mount_exit_side_kilo121_vestlight_plr.ogg",
		}
})
-- Sound: 3
sound.Add({
	name = "mount_exit_top_kilo121_vestlight_plr",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/mount/mount_exit_top_kilo121_vestlight_plr.ogg",
		}
})
-- Sound: 4
sound.Add({
	name = "weap_kilo121_dryfire_plr",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"weapons/weap_dryfire_rifle.ogg",
		}
})
-- Sound: 5
sound.Add({
	name = "weap_kilo121_dryfirst_plr",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"weapons/iw8_kilo121/weap_kilo121_prefire_plr_01.ogg",
		}
})
-- Sound: 8
sound.Add({
	name = "weap_kilo121_fire_plr",
	channel = CHAN_WEAPON,
	level = 140,
	volume = 1,
	pitch = {80,100},
	sound = 
		"^weapons/kilo121/weap_kilo121_fire_plr_01.wav",
		
})
sound.Add({
	name = "weap_kilo121_sup_plr",
	channel = CHAN_WEAPON,
	level = 140,
	volume = 1,
	pitch = {80,100},
	sound = 
		"^weapons/kilo121/weap_scharlie_sup_plr_01.wav",
		
})
-- Sound: 15
sound.Add({
	name = "weap_lm_kilo121_ads_down",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_ads_down.ogg",
		}
})
-- Sound: 16
sound.Add({
	name = "weap_lm_kilo121_ads_up",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_ads_up.ogg",
		}
})
-- Sound: 17
sound.Add({
	name = "weap_lm_kilo121_selector_off",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/selector/weap_m4_selector_semi_on_01.ogg",
		"foley/selector/weap_m4_selector_semi_on_02.ogg",
		"foley/selector/weap_m4_selector_semi_on_03.ogg",
		}
})
-- Sound: 18
sound.Add({
	name = "weap_lm_kilo121_selector_on",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/selector/weap_m4_selector_semi_on_01.ogg",
		"foley/selector/weap_m4_selector_semi_on_02.ogg",
		"foley/selector/weap_m4_selector_semi_on_03.ogg",
		}
})
-- Sound: 19
sound.Add({
	name = "wfoly_plr_lm_kilo121_drop_01",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_drop.ogg",
		}
})
-- Sound: 20
sound.Add({
	name = "wfoly_plr_lm_kilo121_drop_empty_01",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_drop_empty.ogg",
		}
})

sound.Add({
	name = "wfoly_plr_lm_kilo121_raise_first_01",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_raise_first_raise.ogg",
		}
})
sound.Add({
	name = "wfoly_plr_lm_kilo121_raise_first_02",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_raise_first_drop.ogg",
		}
})
sound.Add({
	name = "wfoly_plr_lm_kilo121_raise_first_03",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_raise_first_cloth02.ogg",
		}
})
sound.Add({
	name = "wfoly_plr_lm_kilo121_raise_first_04",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_raise_first_cloth01.ogg",
		}
})
sound.Add({
	name = "wfoly_plr_lm_kilo121_raise_first_05",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_raise_first_boltopen_01.ogg",
		}
})
sound.Add({
	name = "wfoly_plr_lm_kilo121_raise_first_06",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_raise_first_cloth02.ogg",
		}
})
sound.Add({
	name = "wfoly_plr_lm_kilo121_raise_first_07",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_raise_first_boltclose_01.ogg",
		}
})
sound.Add({
	name = "wfoly_plr_lm_kilo121_raise_first_08",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_raise_first_rattle.ogg",
		}
})
sound.Add({
	name = "wfoly_plr_lm_kilo121_raise_first_09",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_raise_first_end.ogg",
		}
})



-- Sound: 21
sound.Add({
	name = "wfoly_plr_lm_kilo121_drop_fast_01",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_drop_fast.ogg",
		}
})
-- Sound: 22
sound.Add({
	name = "wfoly_plr_lm_kilo121_hybrid_scope_side_off",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/hybrid_scope/wfoly_plr_lm_kilo121_hybrid_side_off.ogg",
		}
})
-- Sound: 23
sound.Add({
	name = "wfoly_plr_lm_kilo121_hybrid_scope_side_on",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/hybrid_scope/wfoly_plr_lm_kilo121_hybrid_side_on.ogg",
		}
})
-- Sound: 24
sound.Add({
	name = "wfoly_plr_lm_kilo121_hybrid_scope_snap_closed",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/hybrid_scope/wfoly_plr_ar_falpha_hybrid_scope_snap_closed.ogg",
		}
})
-- Sound: 25
sound.Add({
	name = "wfoly_plr_lm_kilo121_hybrid_scope_snap_open",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/hybrid_scope/wfoly_plr_ar_falpha_hybrid_scope_snap_open.ogg",
		}
})
-- Sound: 26
sound.Add({
	name = "wfoly_plr_lm_kilo121_hybrid_scope_top_in",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/hybrid_scope/wfoly_plr_lm_kilo121_hybrid_top_in.ogg",
		}
})
-- Sound: 27
sound.Add({
	name = "wfoly_plr_lm_kilo121_hybrid_scope_top_out",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/hybrid_scope/wfoly_plr_lm_kilo121_hybrid_top_out.ogg",
		}
})
-- Sound: 28
sound.Add({
	name = "wfoly_plr_lm_kilo121_inspect_01",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_inspect_01.ogg",
		}
})
-- Sound: 29
sound.Add({
	name = "wfoly_plr_lm_kilo121_inspect_02",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_inspect_02.ogg",
		}
})
-- Sound: 30
sound.Add({
	name = "wfoly_plr_lm_kilo121_inspect_03",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_inspect_03.ogg",
		}
})
-- Sound: 31
sound.Add({
	name = "wfoly_plr_lm_kilo121_raise_01",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_raise.ogg",
		}
})
-- Sound: 32
sound.Add({
	name = "wfoly_plr_lm_kilo121_raise_empty_01",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_raise_empty.ogg",
		}
})
-- Sound: 33
sound.Add({
	name = "wfoly_plr_lm_kilo121_raise_fast_01",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo98/wfoly_lm_kilo121_raise_fast.ogg",
		}
})
-- Sound: 38
sound.Add({
	name = "wfoly_plr_lm_kilo121_reload_01",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_reload_raise.ogg",
		}
})
-- Sound: 39
sound.Add({
	name = "wfoly_plr_lm_kilo121_reload_02",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_reload_boltopen_01.ogg",
		}
})
-- Sound: 40
sound.Add({
	name = "wfoly_plr_lm_kilo121_reload_03",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_reload_lower.ogg",
		}
})
-- Sound: 41
sound.Add({
	name = "wfoly_plr_lm_kilo121_reload_04",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_reload_boltclose_01.ogg",
		}
})
-- Sound: 42
sound.Add({
	name = "wfoly_plr_lm_kilo121_reload_05",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_reload_coveropen_01.ogg",
		}
})
-- Sound: 43
sound.Add({
	name = "wfoly_plr_lm_kilo121_reload_06",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_reload_magout_01.ogg",
		}
})
-- Sound: 44
sound.Add({
	name = "wfoly_plr_lm_kilo121_reload_07",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_reload_boxmag.ogg",
		}
})
-- Sound: 45
sound.Add({
	name = "wfoly_plr_lm_kilo121_reload_08",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_reload_magin_01.ogg",
		}
})
-- Sound: 46
sound.Add({
	name = "wfoly_plr_lm_kilo121_reload_09",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_reload_click_01.ogg",
		}
})
-- Sound: 47
sound.Add({
	name = "wfoly_plr_lm_kilo121_reload_10",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_reload_coverclose_01.ogg",
		}
})
-- Sound: 48
sound.Add({
	name = "wfoly_plr_lm_kilo121_reload_11",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_reload_end.ogg",
		}
})
-- Sound: 49
sound.Add({
	name = "wfoly_plr_lm_kilo121_reload_empty_01",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_reload_empty_lift.ogg",
		}
})
-- Sound: 50
sound.Add({
	name = "wfoly_plr_lm_kilo121_reload_empty_02",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_reload_empty_raise_01.ogg",
		}
})
-- Sound: 51
sound.Add({
	name = "wfoly_plr_lm_kilo121_reload_empty_03",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_reload_empty_boltopen_01.ogg",
		}
})
-- Sound: 52
sound.Add({
	name = "wfoly_plr_lm_kilo121_reload_empty_04",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_reload_empty_boltclose_01.ogg",
		}
})
-- Sound: 53
sound.Add({
	name = "wfoly_plr_lm_kilo121_reload_empty_05",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_reload_empty_lower.ogg",
		}
})
-- Sound: 54
sound.Add({
	name = "wfoly_plr_lm_kilo121_reload_empty_06",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_reload_empty_mvmnt01.ogg",
		}
})
-- Sound: 55
sound.Add({
	name = "wfoly_plr_lm_kilo121_reload_empty_07",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_reload_empty_coveropen_01.ogg",
		}
})
-- Sound: 56
sound.Add({
	name = "wfoly_plr_lm_kilo121_reload_empty_08",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_reload_empty_clean.ogg",
		}
})
-- Sound: 57
sound.Add({
	name = "wfoly_plr_lm_kilo121_reload_empty_09",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_reload_empty_inspect.ogg",
		}
})
-- Sound: 58
sound.Add({
	name = "wfoly_plr_lm_kilo121_reload_empty_10",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_reload_empty_magout_01.ogg",
		}
})
-- Sound: 59
sound.Add({
	name = "wfoly_plr_lm_kilo121_reload_empty_11",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_reload_empty_beltmvmnt.ogg",
		}
})
-- Sound: 60
sound.Add({
	name = "wfoly_plr_lm_kilo121_reload_empty_12",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_reload_empty_boxmag.ogg",
		}
})
-- Sound: 61
sound.Add({
	name = "wfoly_plr_lm_kilo121_reload_empty_13",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_reload_empty_magin_01.ogg",
		}
})
-- Sound: 62
sound.Add({
	name = "wfoly_plr_lm_kilo121_reload_empty_14",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_reload_empty_mvmnt02.ogg",
		}
})
-- Sound: 63
sound.Add({
	name = "wfoly_plr_lm_kilo121_reload_empty_15",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_reload_empty_click_01.ogg",
		}
})
-- Sound: 64
sound.Add({
	name = "wfoly_plr_lm_kilo121_reload_empty_16",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_reload_empty_coverclose_01.ogg",
		}
})
-- Sound: 65
sound.Add({
	name = "wfoly_plr_lm_kilo121_reload_empty_17",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_reload_empty_end.ogg",
		}
})
-- Sound: 66
sound.Add({
	name = "wfoly_plr_lm_kilo121_reload_empty_fast_01",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_reload_empty_fast_rotate.ogg",
		}
})
-- Sound: 67
sound.Add({
	name = "wfoly_plr_lm_kilo121_reload_empty_fast_02",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_reload_empty_fast_boltopen_01.ogg",
		}
})
-- Sound: 68
sound.Add({
	name = "wfoly_plr_lm_kilo121_reload_empty_fast_03",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_reload_empty_fast_boltclose_01.ogg",
		}
})
-- Sound: 69
sound.Add({
	name = "wfoly_plr_lm_kilo121_reload_empty_fast_04",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_reload_empty_fast_lower.ogg",
		}
})
-- Sound: 70
sound.Add({
	name = "wfoly_plr_lm_kilo121_reload_empty_fast_05",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_reload_empty_fast_mvmnt01.ogg",
		}
})
-- Sound: 71
sound.Add({
	name = "wfoly_plr_lm_kilo121_reload_empty_fast_06",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_reload_empty_fast_coveropen_01.ogg",
		}
})
-- Sound: 72
sound.Add({
	name = "wfoly_plr_lm_kilo121_reload_empty_fast_07",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_reload_empty_fast_magout_01.ogg",
		}
})
-- Sound: 73
sound.Add({
	name = "wfoly_plr_lm_kilo121_reload_empty_fast_08",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_reload_empty_fast_rattle.ogg",
		}
})
-- Sound: 74
sound.Add({
	name = "wfoly_plr_lm_kilo121_reload_empty_fast_09",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_reload_empty_fast_boxmag.ogg",
		}
})
-- Sound: 75
sound.Add({
	name = "wfoly_plr_lm_kilo121_reload_empty_fast_10",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_reload_empty_fast_magin_01.ogg",
		}
})
-- Sound: 76
sound.Add({
	name = "wfoly_plr_lm_kilo121_reload_empty_fast_11",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_reload_empty_fast_mvmnt02.ogg",
		}
})
-- Sound: 77
sound.Add({
	name = "wfoly_plr_lm_kilo121_reload_empty_fast_12",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_reload_empty_fast_clean.ogg",
		}
})
-- Sound: 78
sound.Add({
	name = "wfoly_plr_lm_kilo121_reload_empty_fast_13",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_reload_empty_fast_close.ogg",
		}
})
-- Sound: 79
sound.Add({
	name = "wfoly_plr_lm_kilo121_reload_empty_fast_14",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_reload_empty_fast_cloth.ogg",
		}
})
-- Sound: 80
sound.Add({
	name = "wfoly_plr_lm_kilo121_reload_empty_fast_15",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_reload_empty_fast_end.ogg",
		}
})
-- Sound: 81
sound.Add({
	name = "wfoly_plr_lm_kilo121_reload_fast_01",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_reload_fast_mvmnt.ogg",
		}
})
-- Sound: 82
sound.Add({
	name = "wfoly_plr_lm_kilo121_reload_fast_02",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_reload_fast_boltopen_01.ogg",
		}
})
-- Sound: 83
sound.Add({
	name = "wfoly_plr_lm_kilo121_reload_fast_03",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_reload_fast_boltclose_01.ogg",
		}
})
-- Sound: 84
sound.Add({
	name = "wfoly_plr_lm_kilo121_reload_fast_04",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_reload_fast_coverrelease_01.ogg",
		}
})
-- Sound: 85
sound.Add({
	name = "wfoly_plr_lm_kilo121_reload_fast_05",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_reload_fast_coveropen_01.ogg",
		}
})
-- Sound: 86
sound.Add({
	name = "wfoly_plr_lm_kilo121_reload_fast_06",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_reload_fast_magout_01.ogg",
		}
})
-- Sound: 87
sound.Add({
	name = "wfoly_plr_lm_kilo121_reload_fast_07",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_reload_fast_magin_01.ogg",
		}
})
-- Sound: 88
sound.Add({
	name = "wfoly_plr_lm_kilo121_reload_fast_08",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_reload_fast_ammobelt_01.ogg",
		}
})
-- Sound: 89
sound.Add({
	name = "wfoly_plr_lm_kilo121_reload_fast_09",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_reload_fast_cloth.ogg",
		}
})
-- Sound: 90
sound.Add({
	name = "wfoly_plr_lm_kilo121_reload_fast_10",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_reload_fast_coverclose_01.ogg",
		}
})
-- Sound: 91
sound.Add({
	name = "wfoly_plr_lm_kilo121_reload_fast_11",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_kilo121/wfoly_lm_kilo121_reload_fast_end.ogg",
		}
})
