-- Generated by GmodSoundGen

-- File: D:\Downloads\important_stuff_v2\Tools\GmodSoundGen_0519\weapon_pi_decho.all.lua
-- Total length: 106

-- Sound: 16
sound.Add({
	name = "weap_decho_fire_plr",
	channel = CHAN_WEAPON,
	level = 140,
	volume = 1,
	pitch = {80,100},
	sound = "^weapons/decho/weap_decho_fire_plr_01.wav"
		
})
sound.Add({
	name = "weap_decho_fire_first",
	channel = CHAN_WPNFOLEY,
	volume = 1,
	pitch = {100,100},
	sound = {
		"weapons/decho/weap_decho_fire_first_plr_01.ogg",
		}
})
-- Sound: 40
sound.Add({
	name = "weap_decho_sup_plr",
	channel = CHAN_WEAPON,
	level = 140,
	volume = 1,
	pitch = {100,100},
	sound = {
		"weapons/decho/weap_decho_sup_plr_01.ogg",
		}
})
-- Sound: 45
sound.Add({
	name = "weap_decho_sup1_last_plr_mech",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"weapons/decho/weap_decho_fire_last_plr_mech_01.ogg",
		"weapons/decho/weap_decho_fire_last_plr_mech_02.ogg",
		"weapons/decho/weap_decho_fire_last_plr_mech_03.ogg",
		}
})
-- Sound: 48
sound.Add({
	name = "weap_decho_sup1_plr_lfe",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"weapons/decho/weap_decho_fire_plr_lfe.ogg",
		}
})
-- Sound: 53
sound.Add({
	name = "weap_decho_sup2_last_plr_mech",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"weapons/decho/weap_decho_fire_last_plr_mech_01.ogg",
		"weapons/decho/weap_decho_fire_last_plr_mech_02.ogg",
		"weapons/decho/weap_decho_fire_last_plr_mech_03.ogg",
		}
})
-- Sound: 56
sound.Add({
	name = "weap_decho_sup2_plr_lfe",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"weapons/decho/weap_decho_fire_plr_lfe.ogg",
		}
})
-- Sound: 58
sound.Add({
	name = "weap_pi_decho_ads_down",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_decho/wfoly_pi_decho_ads_down.ogg",
		}
})
-- Sound: 59
sound.Add({
	name = "weap_pi_decho_ads_up",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_decho/wfoly_pi_decho_ads_up.ogg",
		}
})
-- Sound: 60
sound.Add({
	name = "wfoly_plr_pi_decho_drop_01",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_decho/wfoly_pi_decho_drop_mvmnt.ogg",
		}
})
-- Sound: 61
sound.Add({
	name = "wfoly_plr_pi_decho_inspect_01",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_decho/wfoly_pi_decho_inspect_01.ogg",
		}
})
-- Sound: 62
sound.Add({
	name = "wfoly_plr_pi_decho_inspect_02",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_decho/wfoly_pi_decho_inspect_02.ogg",
		}
})
-- Sound: 63
sound.Add({
	name = "wfoly_plr_pi_decho_inspect_03",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_decho/wfoly_pi_decho_inspect_03.ogg",
		}
})
-- Sound: 64
sound.Add({
	name = "wfoly_plr_pi_decho_raise_01",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_decho/wfoly_pi_decho_raise_mvmnt.ogg",
		}
})
-- Sound: 64
sound.Add({
	name = "wfoly_plr_pi_decho_first_raise_01",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_decho/wfoly_pi_decho_first_raise_mvmnt.ogg",
		}
})
-- Sound: 64
sound.Add({
	name = "wfoly_plr_pi_decho_first_raise_02",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_decho/wfoly_pi_decho_first_raise_safetyoff.ogg",
		}
})
-- Sound: 64
sound.Add({
	name = "wfoly_plr_pi_decho_first_raise_03",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_decho/wfoly_pi_decho_first_raise_end.ogg",
		}
})
-- Sound: 65
sound.Add({
	name = "wfoly_plr_pi_decho_reload_01",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_decho/wfoly_pi_decho_reload_raise.ogg",
		}
})
-- Sound: 66
sound.Add({
	name = "wfoly_plr_pi_decho_reload_02",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_decho/wfoly_pi_decho_reload_magout_01.ogg",
		}
})
-- Sound: 67
sound.Add({
	name = "wfoly_plr_pi_decho_reload_03",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_decho/wfoly_pi_decho_reload_magin_v2_01.ogg",
		}
})
-- Sound: 68
sound.Add({
	name = "wfoly_plr_pi_decho_reload_035",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_decho/wfoly_pi_decho_reload_magin_v2_02.ogg",
		}
})
-- Sound: 69
sound.Add({
	name = "wfoly_plr_pi_decho_reload_04",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_decho/wfoly_pi_decho_reload_end.ogg",
		}
})
-- Sound: 70
sound.Add({
	name = "wfoly_plr_pi_decho_reload_empty_01",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_decho/wfoly_pi_decho_reload_empty_shake.ogg",
		}
})
-- Sound: 71
sound.Add({
	name = "wfoly_plr_pi_decho_reload_empty_02",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_decho/wfoly_pi_decho_reload_empty_magout_01.ogg",
		}
})
-- Sound: 72
sound.Add({
	name = "wfoly_plr_pi_decho_reload_empty_03",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_decho/wfoly_pi_decho_reload_empty_magin_v2_01.ogg",
		}
})
-- Sound: 73
sound.Add({
	name = "wfoly_plr_pi_decho_reload_empty_035",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_decho/wfoly_pi_decho_reload_empty_magin_v2_02.ogg",
		}
})
-- Sound: 74
sound.Add({
	name = "wfoly_plr_pi_decho_reload_empty_04",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_decho/wfoly_pi_decho_reload_empty_mvmnt.ogg",
		}
})
-- Sound: 75
sound.Add({
	name = "wfoly_plr_pi_decho_reload_empty_05",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_decho/wfoly_pi_decho_reload_empty_end.ogg",
		}
})
-- Sound: 76
sound.Add({
	name = "wfoly_plr_pi_decho_reload_empty_06",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_decho/wfoly_pi_decho_reload_empty_charge_01.ogg",
		}
})
-- Sound: 77
sound.Add({
	name = "wfoly_plr_pi_decho_reload_empty_fast_01",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_decho/wfoly_pi_decho_fast_reload_empty_raise.ogg",
		}
})
-- Sound: 78
sound.Add({
	name = "wfoly_plr_pi_decho_reload_empty_fast_02",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_decho/wfoly_pi_decho_fast_reload_empty_magout_01.ogg",
		}
})
-- Sound: 79
sound.Add({
	name = "wfoly_plr_pi_decho_reload_empty_fast_03",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_decho/wfoly_pi_decho_fast_reload_empty_magin_v2_01.ogg",
		}
})
-- Sound: 80
sound.Add({
	name = "wfoly_plr_pi_decho_reload_empty_fast_035",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_decho/wfoly_pi_decho_fast_reload_empty_magin_v2_02.ogg",
		}
})
-- Sound: 81
sound.Add({
	name = "wfoly_plr_pi_decho_reload_empty_fast_04",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_decho/wfoly_pi_decho_fast_reload_empty_slide_01.ogg",
		}
})
-- Sound: 82
sound.Add({
	name = "wfoly_plr_pi_decho_reload_empty_fast_05",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_decho/wfoly_pi_decho_fast_reload_empty_end.ogg",
		}
})
-- Sound: 83
sound.Add({
	name = "wfoly_plr_pi_decho_reload_empty_xmag_01",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_decho/wfoly_pi_decho_reload_empty_xmag_shake.ogg",
		}
})
-- Sound: 84
sound.Add({
	name = "wfoly_plr_pi_decho_reload_empty_xmag_02",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_decho/wfoly_pi_decho_reload_empty_xmag_magout_01.ogg",
		}
})
-- Sound: 85
sound.Add({
	name = "wfoly_plr_pi_decho_reload_empty_xmag_03",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_decho/wfoly_pi_decho_reload_empty_xmag_magin_v2_01.ogg",
		}
})
-- Sound: 86
sound.Add({
	name = "wfoly_plr_pi_decho_reload_empty_xmag_035",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_decho/wfoly_pi_decho_reload_empty_xmag_magin_v2_02.ogg",
		}
})
-- Sound: 87
sound.Add({
	name = "wfoly_plr_pi_decho_reload_empty_xmag_04",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_decho/wfoly_pi_decho_reload_empty_xmag_grab.ogg",
		}
})
-- Sound: 88
sound.Add({
	name = "wfoly_plr_pi_decho_reload_empty_xmag_05",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_decho/wfoly_pi_decho_reload_empty_xmag_charge_01.ogg",
		}
})
-- Sound: 89
sound.Add({
	name = "wfoly_plr_pi_decho_reload_empty_xmag_06",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_decho/wfoly_pi_decho_reload_empty_xmag_end.ogg",
		}
})
-- Sound: 90
sound.Add({
	name = "wfoly_plr_pi_decho_reload_fast_01",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_decho/wfoly_pi_decho_fast_reload_raise.ogg",
		}
})
-- Sound: 91
sound.Add({
	name = "wfoly_plr_pi_decho_reload_fast_02",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_decho/wfoly_pi_decho_fast_reload_magout_01.ogg",
		}
})
-- Sound: 92
sound.Add({
	name = "wfoly_plr_pi_decho_reload_fast_03",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_decho/wfoly_pi_decho_fast_reload_magin_v2_01.ogg",
		}
})
-- Sound: 93
sound.Add({
	name = "wfoly_plr_pi_decho_reload_fast_035",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_decho/wfoly_pi_decho_fast_reload_magin_v2_02.ogg",
		}
})
-- Sound: 94
sound.Add({
	name = "wfoly_plr_pi_decho_reload_fast_04",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_decho/wfoly_pi_decho_fast_reload_end.ogg",
		}
})
-- Sound: 95
sound.Add({
	name = "wfoly_plr_pi_decho_reload_fast_xmag_01",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_decho/wfoly_pi_decho_fast_reload_exmag_raise.ogg",
		}
})
-- Sound: 96
sound.Add({
	name = "wfoly_plr_pi_decho_reload_fast_xmag_02",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_decho/wfoly_pi_decho_fast_reload_exmag_magout_01.ogg",
		}
})
-- Sound: 97
sound.Add({
	name = "wfoly_plr_pi_decho_reload_fast_xmag_03",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_decho/wfoly_pi_decho_fast_reload_exmag_magin_v2_01.ogg",
		}
})
-- Sound: 98
sound.Add({
	name = "wfoly_plr_pi_decho_reload_fast_xmag_035",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_decho/wfoly_pi_decho_fast_reload_exmag_magin_v2_02.ogg",
		}
})
-- Sound: 99
sound.Add({
	name = "wfoly_plr_pi_decho_reload_fast_xmag_04",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_decho/wfoly_pi_decho_fast_reload_exmag_mvmnt.ogg",
		}
})
-- Sound: 100
sound.Add({
	name = "wfoly_plr_pi_decho_reload_fast_xmag_05",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_decho/wfoly_pi_decho_fast_reload_exmag_end.ogg",
		}
})
-- Sound: 101
sound.Add({
	name = "wfoly_plr_pi_decho_reload_xmag_01",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_decho/wfoly_pi_decho_reload_xmag_raise.ogg",
		}
})
-- Sound: 102
sound.Add({
	name = "wfoly_plr_pi_decho_reload_xmag_02",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_decho/wfoly_pi_decho_reload_xmag_magout_01.ogg",
		}
})
-- Sound: 103
sound.Add({
	name = "wfoly_plr_pi_decho_reload_xmag_03",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_decho/wfoly_pi_decho_reload_xmag_magin_v2_01.ogg",
		}
})
-- Sound: 104
sound.Add({
	name = "wfoly_plr_pi_decho_reload_xmag_035",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_decho/wfoly_pi_decho_reload_xmag_magin_v2_02.ogg",
		}
})
-- Sound: 105
sound.Add({
	name = "wfoly_plr_pi_decho_reload_xmag_04",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_decho/wfoly_pi_decho_reload_xmag_end.ogg",
		}
})
