-- Generated by GmodSoundGen

-- File: D:\Downloads\important_stuff_v2\Tools\GmodSoundGen_0519\weapon_pi_mike1911.all.lua
-- Total length: 90


sound.Add({
	name = "weap_mike1911_fire_plr",
	channel = CHAN_WEAPON,
	level = 140,
	volume = 1,
	pitch = {100,100},
	sound = 
		"^weapons/mike1911/weap_mike1911_fire_plr_01.wav"
		
})
sound.Add({
	name = "weap_mike1911_fire_first",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"weapons/mike1911/weap_mike1911_fire_first_plr_01.ogg",
		}
})
sound.Add({
	name = "weap_mike1911_fire_disconnector",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"weapons/mike1911/weap_mike1911_disconnector_plr_01.ogg",
		}
})
-- Sound: 21
sound.Add({
	name = "weap_mike1911_fire1_last_plr_mech",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"weapons/mike1911/weap_mike1911_fire_last_plr_mech_01.ogg",
		"weapons/mike1911/weap_mike1911_fire_last_plr_mech_02.ogg",
		"weapons/mike1911/weap_mike1911_fire_last_plr_mech_03.ogg",
		}
})

-- Sound: 40
sound.Add({
	name = "weap_mike1911_sup_plr",
	channel = CHAN_WEAPON,
	level = 140,
	volume = 1,
	pitch = {100,100},
	sound = {
		"weapons/mike1911/weap_mike1911_sup_plr_01.ogg",
		}
})

-- Sound: 58
sound.Add({
	name = "weap_pi_mike1911_ads_down",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike1911/wfoly_pi_mike1911_ads_down.ogg",
		}
})
-- Sound: 59
sound.Add({
	name = "weap_pi_mike1911_ads_up",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike1911/wfoly_pi_mike1911_ads_up.ogg",
		}
})
-- Sound: 60
sound.Add({
	name = "wfoly_plr_pi_mike1911_drop_01",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike1911/wfoly_pi_mike1911_drop.ogg",
		}
})
-- Sound: 60
sound.Add({
	name = "wfoly_plr_pi_mike1911_raise_01",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike1911/wfoly_pi_mike1911_raise.ogg",
		}
})
-- Sound: 60
sound.Add({
	name = "wfoly_plr_pi_mike1911_first_raise_01",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike1911/wfoly_pi_mike1911_first_raise_lift.ogg",
		}
})
-- Sound: 60
sound.Add({
	name = "wfoly_plr_pi_mike1911_first_raise_02",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike1911/wfoly_pi_mike1911_first_raise_slide_pull.ogg",
		}
})
-- Sound: 60
sound.Add({
	name = "wfoly_plr_pi_mike1911_first_raise_03",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike1911/wfoly_pi_mike1911_first_raise_chamber_end.ogg",
		}
})
-- Sound: 60
sound.Add({
	name = "wfoly_plr_pi_mike1911_first_raise_04",
	channel = CHAN_WPNFOLEY + 11,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike1911/wfoly_pi_mike1911_first_raise_slide_release.ogg",
		}
})
-- Sound: 61
sound.Add({
	name = "wfoly_plr_pi_mike1911_first_raise_oil_supressor_sp_c_01",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike1911/wfoly_plr_pi_mike1911_first_raise_oil_supressor_sp_c_01.ogg",
		}
})
-- Sound: 62
sound.Add({
	name = "wfoly_plr_pi_mike1911_first_raise_oil_supressor_sp_c_02",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike1911/wfoly_plr_pi_mike1911_first_raise_oil_supressor_sp_c_02.ogg",
		}
})
-- Sound: 63
sound.Add({
	name = "wfoly_plr_pi_mike1911_first_raise_oil_supressor_sp_lr_01",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike1911/wfoly_plr_pi_mike1911_first_raise_oil_supressor_sp_lr_01.ogg",
		}
})
-- Sound: 64
sound.Add({
	name = "wfoly_plr_pi_mike1911_first_raise_oil_supressor_sp_lr_02",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike1911/wfoly_plr_pi_mike1911_first_raise_oil_supressor_sp_lr_02.ogg",
		}
})
-- Sound: 65
sound.Add({
	name = "wfoly_plr_pi_mike1911_inspect_01",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike1911/wfoly_pi_mike1911_inspect_01.ogg",
		}
})
-- Sound: 66
sound.Add({
	name = "wfoly_plr_pi_mike1911_inspect_02",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike1911/wfoly_pi_mike1911_inspect_02.ogg",
		}
})
-- Sound: 67
sound.Add({
	name = "wfoly_plr_pi_mike1911_inspect_03",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike1911/wfoly_pi_mike1911_inspect_03.ogg",
		}
})
-- Sound: 68
sound.Add({
	name = "wfoly_plr_pi_mike1911_inspect_04",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike1911/wfoly_pi_mike1911_inspect_04.ogg",
		}
})
-- Sound: 69
sound.Add({
	name = "wfoly_plr_pi_mike1911_quick_drop_01",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike1911/wfoly_pi_mike1911_quick_drop.ogg",
		}
})
-- Sound: 70
sound.Add({
	name = "wfoly_plr_pi_mike1911_reload_01",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike1911/wfoly_pi_mike1911_reload_lift.ogg",
		}
})
-- Sound: 71
sound.Add({
	name = "wfoly_plr_pi_mike1911_reload_02",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike1911/wfoly_pi_mike1911_reload_magout_01.ogg",
		}
})
-- Sound: 72
sound.Add({
	name = "wfoly_plr_pi_mike1911_reload_03",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike1911/wfoly_pi_mike1911_reload_magin_v2_01.ogg",
		}
})
-- Sound: 73
sound.Add({
	name = "wfoly_plr_pi_mike1911_reload_035",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike1911/wfoly_pi_mike1911_reload_magin_v2_02.ogg",
		}
})
-- Sound: 74
sound.Add({
	name = "wfoly_plr_pi_mike1911_reload_04",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike1911/wfoly_pi_mike1911_reload_end.ogg",
		}
})
-- Sound: 75
sound.Add({
	name = "wfoly_plr_pi_mike1911_reload_empty_01",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike1911/wfoly_pi_mike1911_reload_empty_lift.ogg",
		}
})
-- Sound: 76
sound.Add({
	name = "wfoly_plr_pi_mike1911_reload_empty_02",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike1911/wfoly_pi_mike1911_reload_empty_magout_01.ogg",
		}
})
-- Sound: 77
sound.Add({
	name = "wfoly_plr_pi_mike1911_reload_empty_03",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike1911/wfoly_pi_mike1911_reload_empty_magin_v2_01.ogg",
		}
})
-- Sound: 78
sound.Add({
	name = "wfoly_plr_pi_mike1911_reload_empty_035",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike1911/wfoly_pi_mike1911_reload_empty_magin_v2_02.ogg",
		}
})
-- Sound: 79
sound.Add({
	name = "wfoly_plr_pi_mike1911_reload_empty_04",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike1911/wfoly_pi_mike1911_reload_empty_end.ogg",
		}
})
-- Sound: 80
sound.Add({
	name = "wfoly_plr_pi_mike1911_reload_empty_05",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike1911/wfoly_pi_mike1911_reload_empty_chamber_01.ogg",
		}
})
-- Sound: 81
sound.Add({
	name = "wfoly_plr_pi_mike1911_reload_empty_fast_01",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike1911/wfoly_pi_mike1911_fast_reload_empty_lift.ogg",
		}
})
-- Sound: 82
sound.Add({
	name = "wfoly_plr_pi_mike1911_reload_empty_fast_02",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike1911/wfoly_pi_mike1911_fast_reload_empty_magout_01.ogg",
		}
})
-- Sound: 83
sound.Add({
	name = "wfoly_plr_pi_mike1911_reload_empty_fast_03",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike1911/wfoly_pi_mike1911_fast_reload_empty_magin_01.ogg",
		}
})
-- Sound: 84
sound.Add({
	name = "wfoly_plr_pi_mike1911_reload_empty_fast_04",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike1911/wfoly_pi_mike1911_fast_reload_empty_end.ogg",
		}
})
-- Sound: 85
sound.Add({
	name = "wfoly_plr_pi_mike1911_reload_empty_fast_05",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike1911/wfoly_pi_mike1911_fast_reload_empty_chamber_01.ogg",
		}
})
-- Sound: 86
sound.Add({
	name = "wfoly_plr_pi_mike1911_reload_fast_01",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike1911/wfoly_pi_mike1911_fast_reload_lift.ogg",
		}
})
-- Sound: 87
sound.Add({
	name = "wfoly_plr_pi_mike1911_reload_fast_02",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike1911/wfoly_pi_mike1911_fast_reload_magout_01.ogg",
		}
})
-- Sound: 88
sound.Add({
	name = "wfoly_plr_pi_mike1911_reload_fast_03",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike1911/wfoly_pi_mike1911_fast_reload_magin_01.ogg",
		}
})
-- Sound: 89
sound.Add({
	name = "wfoly_plr_pi_mike1911_reload_fast_04",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike1911/wfoly_pi_mike1911_fast_reload_end.ogg",
		}
})
