-- Generated by GmodSoundGen

-- File: D:\Downloads\important_stuff_v2\Tools\GmodSoundGen_0519\weapon_sn_hdromeo.all.lua
-- Total length: 74

-- Sound: 0
sound.Add({
	name = "mount_enter_side_hdromeo_vestlight_plr",
	channel = CHAN_WPNFOLEY + 1,
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/mount/mount_enter_side_hdromeo_vestlight_plr.ogg",
		}
})
-- Sound: 1
sound.Add({
	name = "mount_enter_top_hdromeo_vestlight_plr",
	channel = CHAN_WPNFOLEY + 2,
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/mount/mount_enter_top_hdromeo_vestlight_plr.ogg",
		}
})
-- Sound: 2
sound.Add({
	name = "mount_exit_side_hdromeo_vestlight_plr",
	channel = CHAN_WPNFOLEY + 3,
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/mount/mount_exit_side_hdromeo_vestlight_plr.ogg",
		}
})
-- Sound: 3
sound.Add({
	name = "mount_exit_top_hdromeo_vestlight_plr",
	channel = CHAN_WPNFOLEY + 4,
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/mount/mount_exit_top_hdromeo_vestlight_plr.ogg",
		}
})
-- Sound: 4
sound.Add({
	name = "weap_hdromeo_dryfire_plr",
	channel = CHAN_WPNFOLEY + 5,
	volume = 1,
	pitch = {100,100},
	sound = {
		"weapons/weap_dryfire_rifle.ogg",
		}
})
-- Sound: 8
sound.Add({
	name = "weap_hdromeo_fire_plr",
	channel = CHAN_WEAPON,
	level = 140,
	volume = 1,
	pitch = {100,100},
	sound = 
		"^weapons/hdromeo/weap_hdromeo_fire_plr_01.wav",
		
})
sound.Add({
	name = "weap_hdromeo_fire_plr_sup",
	channel = CHAN_WEAPON,
	level = 140,
	volume = 1,
	pitch = {100,100},
	sound = 
		"^weapons/hdromeo/weap_hdromeo_sup_plr_01.wav",
		
})
-- Sound: 10
sound.Add({
	name = "weap_sn_hdromeo_ads_down",
	channel = CHAN_WPNFOLEY + 7,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/weap_sn_hdromeo_ads_down.ogg",
		}
})
-- Sound: 11
sound.Add({
	name = "weap_sn_hdromeo_ads_up",
	channel = CHAN_WPNFOLEY + 8,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/weap_sn_hdromeo_ads_up.ogg",
		}
})
-- Sound: 12
sound.Add({
	name = "wfoly_plr_sn_hdromeo_ballistics_raise_first_01",
	channel = CHAN_WPNFOLEY + 9,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_ballistics_raise_first_start.ogg",
		}
})
-- Sound: 13
sound.Add({
	name = "wfoly_plr_sn_hdromeo_ballistics_raise_first_02",
	channel = CHAN_WPNFOLEY + 10,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_ballistics_raise_first_raisesettle.ogg",
		}
})
-- Sound: 14
sound.Add({
	name = "wfoly_plr_sn_hdromeo_ballistics_raise_first_03",
	channel = CHAN_WPNFOLEY + 1,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_ballistics_raise_first_maggrab.ogg",
		}
})
-- Sound: 15
sound.Add({
	name = "wfoly_plr_sn_hdromeo_ballistics_raise_first_04",
	channel = CHAN_WPNFOLEY + 2,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_ballistics_raise_first_magout_01.ogg",
		}
})
-- Sound: 16
sound.Add({
	name = "wfoly_plr_sn_hdromeo_ballistics_raise_first_05",
	channel = CHAN_WPNFOLEY + 3,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_ballistics_raise_first_look.ogg",
		}
})
-- Sound: 17
sound.Add({
	name = "wfoly_plr_sn_hdromeo_ballistics_raise_first_06",
	channel = CHAN_WPNFOLEY + 4,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_ballistics_raise_first_insert.ogg",
		}
})
-- Sound: 18
sound.Add({
	name = "wfoly_plr_sn_hdromeo_ballistics_raise_first_07",
	channel = CHAN_WPNFOLEY + 5,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_ballistics_raise_first_magin_01.ogg",
		}
})
-- Sound: 19
sound.Add({
	name = "wfoly_plr_sn_hdromeo_ballistics_raise_first_08",
	channel = CHAN_WPNFOLEY + 6,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_ballistics_raise_first_rotate.ogg",
		}
})
-- Sound: 20
sound.Add({
	name = "wfoly_plr_sn_hdromeo_ballistics_raise_first_09",
	channel = CHAN_WPNFOLEY + 7,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_ballistics_raise_first_boltopen_01.ogg",
		}
})
-- Sound: 21
sound.Add({
	name = "wfoly_plr_sn_hdromeo_ballistics_raise_first_10",
	channel = CHAN_WPNFOLEY + 8,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_ballistics_raise_first_arm.ogg",
		}
})
-- Sound: 22
sound.Add({
	name = "wfoly_plr_sn_hdromeo_ballistics_raise_first_11",
	channel = CHAN_WPNFOLEY + 9,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_ballistics_raise_first_boltclose_01.ogg",
		}
})
-- Sound: 23
sound.Add({
	name = "wfoly_plr_sn_hdromeo_ballistics_raise_first_12",
	channel = CHAN_WPNFOLEY + 10,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_ballistics_raise_first_forward.ogg",
		}
})
-- Sound: 24
sound.Add({
	name = "wfoly_plr_sn_hdromeo_ballistics_raise_first_13",
	channel = CHAN_WPNFOLEY + 1,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_ballistics_raise_first_adjust.ogg",
		}
})
-- Sound: 25
sound.Add({
	name = "wfoly_plr_sn_hdromeo_ballistics_raise_first_14",
	channel = CHAN_WPNFOLEY + 2,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_ballistics_raise_first_end.ogg",
		}
})
-- Sound: 26
sound.Add({
	name = "wfoly_plr_sn_hdromeo_drop_01",
	channel = CHAN_WPNFOLEY + 3,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_drop_down.ogg",
		}
})
-- Sound: 27
sound.Add({
	name = "wfoly_plr_sn_hdromeo_drop_quick_01",
	channel = CHAN_WPNFOLEY + 4,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_drop_quick_down.ogg",
		}
})
-- Sound: 28
sound.Add({
	name = "wfoly_plr_sn_hdromeo_inspect_01",
	channel = CHAN_WPNFOLEY + 5,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_sn_hdromeo_inspect_01.ogg",
		}
})
-- Sound: 29
sound.Add({
	name = "wfoly_plr_sn_hdromeo_inspect_02",
	channel = CHAN_WPNFOLEY + 6,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_sn_hdromeo_inspect_02.ogg",
		}
})
-- Sound: 30
sound.Add({
	name = "wfoly_plr_sn_hdromeo_inspect_03",
	channel = CHAN_WPNFOLEY + 7,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_sn_hdromeo_inspect_03.ogg",
		}
})
-- Sound: 31
sound.Add({
	name = "wfoly_plr_sn_hdromeo_raise_01",
	channel = CHAN_WPNFOLEY + 8,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_raise_up.ogg",
		}
})
-- Sound: 32
sound.Add({
	name = "wfoly_plr_sn_hdromeo_raise_02",
	channel = CHAN_WPNFOLEY + 9,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_raise_hand.ogg",
		}
})
-- Sound: 33
sound.Add({
	name = "wfoly_plr_sn_hdromeo_raise_03",
	channel = CHAN_WPNFOLEY + 10,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_raise_settle.ogg",
		}
})
-- Sound: 31
sound.Add({
	name = "wfoly_plr_sn_hdromeo_raise_first_01",
	channel = CHAN_WPNFOLEY + 8,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_raise_first_up.ogg",
		}
})
-- Sound: 32
sound.Add({
	name = "wfoly_plr_sn_hdromeo_raise_first_02",
	channel = CHAN_WPNFOLEY + 9,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_raise_first_boltclose_01.ogg",
		}
})
-- Sound: 33
sound.Add({
	name = "wfoly_plr_sn_hdromeo_raise_first_03",
	channel = CHAN_WPNFOLEY + 10,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_raise_first_adjust.ogg",
		}
})
-- Sound: 33 2
sound.Add({
	name = "wfoly_plr_sn_hdromeo_raise_first_04",
	channel = CHAN_WPNFOLEY + 10,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_raise_first_settle.ogg",
		}
})
-- Sound: 34
sound.Add({
	name = "wfoly_plr_sn_hdromeo_raise_quick_01",
	channel = CHAN_WPNFOLEY + 1,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_raise_quick_up.ogg",
		}
})
-- Sound: 36
sound.Add({
	name = "wfoly_plr_sn_hdromeo_rechamber_01",
	channel = CHAN_WPNFOLEY + 1,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_rechamber_boltopen_01_01.ogg",
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_rechamber_boltopen_01_02.ogg",
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_rechamber_boltopen_01_03.ogg",
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_rechamber_boltopen_01_04.ogg",
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_rechamber_boltopen_01_05.ogg",
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_rechamber_boltopen_01_06.ogg",
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_rechamber_boltopen_01_07.ogg",
		}
})
sound.Add({
	name = "wfoly_plr_sn_hdromeo_rechamber_02",
	channel = CHAN_WPNFOLEY + 2,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_rechamber_boltclose_01.ogg",
		}
})
-- Sound: 37
sound.Add({
	name = "wfoly_plr_sn_hdromeo_reload_01",
	channel = CHAN_WPNFOLEY + 3,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_reload_start.ogg",
		}
})
-- Sound: 38
sound.Add({
	name = "wfoly_plr_sn_hdromeo_reload_02",
	channel = CHAN_WPNFOLEY + 4,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_reload_magout_01.ogg",
		}
})
-- Sound: 39
sound.Add({
	name = "wfoly_plr_sn_hdromeo_reload_03",
	channel = CHAN_WPNFOLEY + 5,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_reload_pull.ogg",
		}
})
-- Sound: 40
sound.Add({
	name = "wfoly_plr_sn_hdromeo_reload_04",
	channel = CHAN_WPNFOLEY + 6,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_reload_rattle.ogg",
		}
})
-- Sound: 41
sound.Add({
	name = "wfoly_plr_sn_hdromeo_reload_05",
	channel = CHAN_WPNFOLEY + 7,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_reload_magin_v2_01.ogg",
		}
})
-- Sound: 42
sound.Add({
	name = "wfoly_plr_sn_hdromeo_reload_055",
	channel = CHAN_WPNFOLEY + 8,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_reload_magin_v2_02.ogg",
		}
})
-- Sound: 43
sound.Add({
	name = "wfoly_plr_sn_hdromeo_reload_06",
	channel = CHAN_WPNFOLEY + 9,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_reload_end.ogg",
		}
})
-- Sound: 45
sound.Add({
	name = "wfoly_plr_sn_hdromeo_reload_empty_02",
	channel = CHAN_WPNFOLEY + 10,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_reload_empty_pull.ogg",
		}
})
-- Sound: 46
sound.Add({
	name = "wfoly_plr_sn_hdromeo_reload_empty_03",
	channel = CHAN_WPNFOLEY + 1,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_reload_empty_raise.ogg",
		}
})
-- Sound: 47
sound.Add({
	name = "wfoly_plr_sn_hdromeo_reload_empty_04",
	channel = CHAN_WPNFOLEY + 2,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_reload_empty_magout_01.ogg",
		}
})
-- Sound: 48
sound.Add({
	name = "wfoly_plr_sn_hdromeo_reload_empty_05",
	channel = CHAN_WPNFOLEY + 3,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_reload_empty_toss.ogg",
		}
})
-- Sound: 49
sound.Add({
	name = "wfoly_plr_sn_hdromeo_reload_empty_06",
	channel = CHAN_WPNFOLEY + 4,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_reload_empty_arm.ogg",
		}
})
-- Sound: 50
sound.Add({
	name = "wfoly_plr_sn_hdromeo_reload_empty_07",
	channel = CHAN_WPNFOLEY + 5,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_reload_empty_magin_v2_01.ogg",
		}
})
-- Sound: 51
sound.Add({
	name = "wfoly_plr_sn_hdromeo_reload_empty_075",
	channel = CHAN_WPNFOLEY + 6,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_reload_empty_magin_v2_02.ogg",
		}
})
-- Sound: 52
sound.Add({
	name = "wfoly_plr_sn_hdromeo_reload_empty_08",
	channel = CHAN_WPNFOLEY + 7,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_reload_empty_end.ogg",
		}
})
-- Sound: 53
sound.Add({
	name = "wfoly_plr_sn_hdromeo_reload_empty_09",
	channel = CHAN_WPNFOLEY + 8,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_reload_empty_boltclose_01.ogg",
		}
})
-- Sound: 54
sound.Add({
	name = "wfoly_plr_sn_hdromeo_reload_empty_fast_01",
	channel = CHAN_WPNFOLEY + 9,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_reload_empty_fast_start.ogg",
		}
})
-- Sound: 56
sound.Add({
	name = "wfoly_plr_sn_hdromeo_reload_empty_fast_03",
	channel = CHAN_WPNFOLEY + 10,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_reload_empty_fast_handmove.ogg",
		}
})
-- Sound: 57
sound.Add({
	name = "wfoly_plr_sn_hdromeo_reload_empty_fast_04",
	channel = CHAN_WPNFOLEY + 1,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_reload_empty_fast_magout_01.ogg",
		}
})
-- Sound: 58
sound.Add({
	name = "wfoly_plr_sn_hdromeo_reload_empty_fast_05",
	channel = CHAN_WPNFOLEY + 2,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_reload_empty_fast_shake.ogg",
		}
})
-- Sound: 59
sound.Add({
	name = "wfoly_plr_sn_hdromeo_reload_empty_fast_06",
	channel = CHAN_WPNFOLEY + 3,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_reload_empty_fast_arm.ogg",
		}
})
-- Sound: 60
sound.Add({
	name = "wfoly_plr_sn_hdromeo_reload_empty_fast_07",
	channel = CHAN_WPNFOLEY + 4,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_reload_empty_fast_magin_v2_01.ogg",
		}
})
-- Sound: 61
sound.Add({
	name = "wfoly_plr_sn_hdromeo_reload_empty_fast_075",
	channel = CHAN_WPNFOLEY + 5,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_reload_empty_fast_magin_v2_02.ogg",
		}
})
-- Sound: 62
sound.Add({
	name = "wfoly_plr_sn_hdromeo_reload_empty_fast_08",
	channel = CHAN_WPNFOLEY + 6,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_reload_empty_fast_rattle.ogg",
		}
})
-- Sound: 63
sound.Add({
	name = "wfoly_plr_sn_hdromeo_reload_empty_fast_09",
	channel = CHAN_WPNFOLEY + 7,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_reload_empty_fast_boltclose_01.ogg",
		}
})
-- Sound: 64
sound.Add({
	name = "wfoly_plr_sn_hdromeo_reload_empty_fast_10",
	channel = CHAN_WPNFOLEY + 8,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_reload_empty_fast_armforward.ogg",
		}
})
-- Sound: 65
sound.Add({
	name = "wfoly_plr_sn_hdromeo_reload_empty_fast_11",
	channel = CHAN_WPNFOLEY + 9,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_reload_empty_fast_end.ogg",
		}
})
-- Sound: 66
sound.Add({
	name = "wfoly_plr_sn_hdromeo_reload_fast_01",
	channel = CHAN_WPNFOLEY + 10,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_reload_fast_start.ogg",
		}
})
-- Sound: 67
sound.Add({
	name = "wfoly_plr_sn_hdromeo_reload_fast_02",
	channel = CHAN_WPNFOLEY + 1,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_reload_fast_magout_01.ogg",
		}
})
-- Sound: 68
sound.Add({
	name = "wfoly_plr_sn_hdromeo_reload_fast_03",
	channel = CHAN_WPNFOLEY + 2,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_reload_fast_pull.ogg",
		}
})
-- Sound: 69
sound.Add({
	name = "wfoly_plr_sn_hdromeo_reload_fast_04",
	channel = CHAN_WPNFOLEY + 3,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_reload_fast_tilt.ogg",
		}
})
-- Sound: 70
sound.Add({
	name = "wfoly_plr_sn_hdromeo_reload_fast_05",
	channel = CHAN_WPNFOLEY + 4,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_reload_fast_magin_v2_01.ogg",
		}
})
-- Sound: 71
sound.Add({
	name = "wfoly_plr_sn_hdromeo_reload_fast_055",
	channel = CHAN_WPNFOLEY + 5,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_reload_fast_magin_v2_02.ogg",
		}
})
-- Sound: 72
sound.Add({
	name = "wfoly_plr_sn_hdromeo_reload_fast_06",
	channel = CHAN_WPNFOLEY + 6,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_reload_fast_shake.ogg",
		}
})
-- Sound: 73
sound.Add({
	name = "wfoly_plr_sn_hdromeo_reload_fast_07",
	channel = CHAN_WPNFOLEY + 7,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_hdromeo/wfoly_plr_sn_hdromeo_reload_fast_end.ogg",
		}
})
