-- Generated by GmodSoundGen

-- File: D:\Downloads\important_stuff_v2\Tools\GmodSoundGen_0519\weapon_sh_romeo870.all.lua
-- Total length: 79
sound.Add({
    name =           "wfoly_plr_sh_romeo870_raise_first_01",
    channel =        CHAN_WPNFOLEY +1,
    volume =         1,
    sound = {"reloads/iw8_romeo870/wfoly_sh_romeo870_raise_first_lift.ogg"}              
})
sound.Add({
    name =           "wfoly_plr_sh_romeo870_raise_first_02",
    channel =        CHAN_WPNFOLEY +2,
    volume =         1,
    sound = {"reloads/iw8_romeo870/wfoly_sh_romeo870_raise_first_chamber_e.ogg"}              
})
sound.Add({
    name =           "wfoly_plr_sh_romeo870_raise_first_03",
    channel =        CHAN_WPNFOLEY +3,
    volume =         1,
    sound = {"reloads/iw8_romeo870/wfoly_sh_romeo870_raise_first_shoulder.ogg"}              
})
-- Sound: 0
sound.Add({
	name = "mount_enter_side_romeo870_vestlight_plr",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/mount/mount_enter_side_romeo870_vestlight_plr.ogg",
		}
})
-- Sound: 1
sound.Add({
	name = "mount_enter_top_romeo870_vestlight_plr",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/mount/mount_enter_top_romeo870_vestlight_plr.ogg",
		}
})
-- Sound: 2
sound.Add({
	name = "mount_exit_side_romeo870_vestlight_plr",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/mount/mount_exit_side_romeo870_vestlight_plr.ogg",
		}
})
-- Sound: 3
sound.Add({
	name = "mount_exit_top_romeo870_vestlight_plr",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/mount/mount_exit_top_romeo870_vestlight_plr.ogg",
		}
})
-- Sound: 10
sound.Add({
	name = "weap_romeo870_fire_plr_lfe",
	channel = CHAN_WEAPON,
	level = 140,
	volume = 1,
	pitch = {80,100},
	sound = 
		"^weapons/romeo870/weap_romeo870_fire_plr_01.wav",
		
})
-- Sound: 20
sound.Add({
	name = "weap_romeo870_sup_plr_lfe",
	channel = CHAN_WEAPON,
	level = 140,
	volume = 1,
	pitch = {100,100},
	sound = 
		"^weapons/romeo870/weap_romeo870_sup_plr_01.wav",
		
})
-- Sound: 22
sound.Add({
	name = "weap_sh_romeo870_ads_down",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_dpapa12/wfoly_sh_dpapa12_ads_down.ogg",
		}
})
-- Sound: 23
sound.Add({
	name = "weap_sh_romeo870_ads_up",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_dpapa12/wfoly_sh_dpapa12_ads_up.ogg",
		}
})
-- Sound: 24
sound.Add({
	name = "wfoly_plr_sh_romeo870_drop_01",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_romeo870/wfoly_sh_romeo870_drop.ogg",
		}
})
-- Sound: 25
sound.Add({
	name = "wfoly_plr_sh_romeo870_drop_quick_01",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_romeo870/wfoly_sh_romeo870_drop_quick.ogg",
		}
})
-- Sound: 26
sound.Add({
	name = "wfoly_plr_sh_romeo870_raise_01",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_romeo870/wfoly_sh_romeo870_raise.ogg",
		}
})
-- Sound: 27
sound.Add({
	name = "wfoly_plr_sh_romeo870_raise_quick_01",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_romeo870/wfoly_sh_romeo870_raise_quick_lift.ogg",
		}
})
-- Sound: 28
sound.Add({
	name = "wfoly_plr_sh_romeo870_raise_quick_02",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_romeo870/wfoly_sh_romeo870_raise_quick_shoulder.ogg",
		}
})
-- Sound: 29
sound.Add({
	name = "wfoly_plr_sh_romeo870_rechamber_01",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_romeo870/wfoly_sh_romeo870_rechamber_v2_01a.ogg",
		"reloads/iw8_romeo870/wfoly_sh_romeo870_rechamber_v2_01b.ogg",
		"reloads/iw8_romeo870/wfoly_sh_romeo870_rechamber_v2_01c.ogg",
		}
})
-- Sound: 29
sound.Add({
	name = "wfoly_plr_sh_romeo870_rechamber_015",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_romeo870/wfoly_sh_romeo870_rechamber_v2_02a.ogg",
		"reloads/iw8_romeo870/wfoly_sh_romeo870_rechamber_v2_02b.ogg",
		"reloads/iw8_romeo870/wfoly_sh_romeo870_rechamber_v2_02c.ogg",
		"reloads/iw8_romeo870/wfoly_sh_romeo870_rechamber_v2_02d.ogg",
		}
})
-- Sound: 31
sound.Add({
	name = "wfoly_plr_sh_romeo870_reload_empty_start_01",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_romeo870/wfoly_sh_romeo870_reload_empty_start_open_01.ogg",
		}
})
-- Sound: 32
sound.Add({
	name = "wfoly_plr_sh_romeo870_reload_empty_start_02",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_romeo870/wfoly_sh_romeo870_reload_empty_start_twist.ogg",
		}
})
-- Sound: 33
sound.Add({
	name = "wfoly_plr_sh_romeo870_reload_empty_start_03",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_romeo870/wfoly_sh_romeo870_reload_empty_start_sideload_01.ogg",
		}
})
-- Sound: 34
sound.Add({
	name = "wfoly_plr_sh_romeo870_reload_empty_start_04",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_romeo870/wfoly_sh_romeo870_reload_empty_start_close_01.ogg",
		}
})
-- Sound: 35
sound.Add({
	name = "wfoly_plr_sh_romeo870_reload_empty_start_05",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_romeo870/wfoly_sh_romeo870_reload_empty_start_end.ogg",
		}
})
-- Sound: 36
sound.Add({
	name = "wfoly_plr_sh_romeo870_reload_empty_start_06",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_romeo870/wfoly_sh_romeo870_reload_empty_start_underload_01.ogg",
		}
})
-- Sound: 37
sound.Add({
	name = "wfoly_plr_sh_romeo870_reload_empty_start_ads_01",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_romeo870/wfoly_sh_romeo870_empty_start_fast_open_01.ogg",
		}
})
-- Sound: 38
sound.Add({
	name = "wfoly_plr_sh_romeo870_reload_empty_start_ads_02",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_romeo870/wfoly_sh_romeo870_empty_start_fast_twist.ogg",
		}
})
-- Sound: 39
sound.Add({
	name = "wfoly_plr_sh_romeo870_reload_empty_start_ads_03",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_romeo870/wfoly_sh_romeo870_empty_start_fast_sideload_01.ogg",
		}
})
-- Sound: 40
sound.Add({
	name = "wfoly_plr_sh_romeo870_reload_empty_start_ads_04",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_romeo870/wfoly_sh_romeo870_empty_start_fast_close.ogg",
		}
})
-- Sound: 41
sound.Add({
	name = "wfoly_plr_sh_romeo870_reload_empty_start_ads_05",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_romeo870/wfoly_sh_romeo870_empty_start_fast_underload_01.ogg",
		}
})
-- Sound: 42
sound.Add({
	name = "wfoly_plr_sh_romeo870_reload_end_01",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_romeo870/wfoly_sh_romeo870_reload_end_turnover.ogg",
		}
})
-- Sound: 43
sound.Add({
	name = "wfoly_plr_sh_romeo870_reload_end_fast_01",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_romeo870/wfoly_sh_romeo870_reload_end_fast_twist.ogg",
		}
})
-- Sound: 44
sound.Add({
	name = "wfoly_plr_sh_romeo870_reload_end_fast_02",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_romeo870/wfoly_sh_romeo870_reload_end_fast_shoulder.ogg",
		}
})
-- Sound: 45
sound.Add({
	name = "wfoly_plr_sh_romeo870_reload_loop_01",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_romeo870/wfoly_sh_romeo870_reload_loop_loadportstart.ogg",
		}
})
-- Sound: 46
sound.Add({
	name = "wfoly_plr_sh_romeo870_reload_loop_02",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_romeo870/wfoly_sh_romeo870_reload_loop_loadportend.ogg",
		}
})
-- Sound: 46 pt2
sound.Add({
	name = "wfoly_plr_sh_romeo870_reload_loop_03",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_romeo870/wfoly_sh_romeo870_reload_loop_shellin_01.ogg",
		"reloads/iw8_romeo870/wfoly_sh_romeo870_reload_loop_shellin_02.ogg",
		"reloads/iw8_romeo870/wfoly_sh_romeo870_reload_loop_shellin_03.ogg",
		"reloads/iw8_romeo870/wfoly_sh_romeo870_reload_loop_shellin_04.ogg",
		}
})
-- Sound: 48
sound.Add({
	name = "wfoly_plr_sh_romeo870_reload_loop_fast_01",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_romeo870/wfoly_sh_romeo870_reload_loop_fast_start.ogg",
		}
})
-- Sound: 50
sound.Add({
	name = "wfoly_plr_sh_romeo870_reload_start_01",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_romeo870/wfoly_sh_romeo870_reload_start_twist.ogg",
		}
})
-- Sound: 51
sound.Add({
	name = "wfoly_plr_sh_romeo870_reload_start_02",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_romeo870/wfoly_sh_romeo870_reload_start_shellin_01.ogg",
		}
})
-- Sound: 52
sound.Add({
	name = "wfoly_plr_sh_romeo870_reload_start_fast_01",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_romeo870/wfoly_sh_romeo870_reload_start_fast_twist.ogg",
		}
})
-- Sound: 53
sound.Add({
	name = "wfoly_plr_sh_romeo870_reload_start_fast_02",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_romeo870/wfoly_sh_romeo870_reload_start_fast_shellin_01.ogg",
		}
})
-- Sound: 54
sound.Add({
	name = "wfoly_plr_sh_romeo871_caldb_reload_01",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_romeo870/wfoly_sh_romeo870_caldb_reload_raise.ogg",
		}
})
-- Sound: 55
sound.Add({
	name = "wfoly_plr_sh_romeo871_caldb_reload_02",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_romeo870/wfoly_sh_romeo870_caldb_reload_magout.ogg",
		}
})
-- Sound: 56
sound.Add({
	name = "wfoly_plr_sh_romeo871_caldb_reload_03",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_romeo870/wfoly_sh_romeo870_caldb_reload_magup.ogg",
		}
})
-- Sound: 57
sound.Add({
	name = "wfoly_plr_sh_romeo871_caldb_reload_04",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_romeo870/wfoly_sh_romeo870_caldb_reload_maghit.ogg",
		}
})
-- Sound: 58
sound.Add({
	name = "wfoly_plr_sh_romeo871_caldb_reload_05",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_romeo870/wfoly_sh_romeo870_caldb_reload_magin.ogg",
		}
})
-- Sound: 59
sound.Add({
	name = "wfoly_plr_sh_romeo871_caldb_reload_06",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_romeo870/wfoly_sh_romeo870_caldb_reload_end.ogg",
		}
})
-- Sound: 60
sound.Add({
	name = "wfoly_plr_sh_romeo872_caldb_reload_empty_01",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_romeo870/wfoly_sh_romeo870_caldb_reload_empty_pump_foreend.ogg",
		}
})
-- Sound: 61
sound.Add({
	name = "wfoly_plr_sh_romeo872_caldb_reload_empty_02",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_romeo870/wfoly_sh_romeo870_caldb_reload_empty_raise.ogg",
		}
})
-- Sound: 62
sound.Add({
	name = "wfoly_plr_sh_romeo872_caldb_reload_empty_03",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_romeo870/wfoly_sh_romeo870_caldb_reload_empty_magout.ogg",
		}
})
-- Sound: 63
sound.Add({
	name = "wfoly_plr_sh_romeo872_caldb_reload_empty_04",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_romeo870/wfoly_sh_romeo870_caldb_reload_empty_magup.ogg",
		}
})
-- Sound: 64
sound.Add({
	name = "wfoly_plr_sh_romeo872_caldb_reload_empty_05",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_romeo870/wfoly_sh_romeo870_caldb_reload_empty_maghit.ogg",
		}
})
-- Sound: 65
sound.Add({
	name = "wfoly_plr_sh_romeo872_caldb_reload_empty_06",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_romeo870/wfoly_sh_romeo870_caldb_reload_empty_magin.ogg",
		}
})
-- Sound: 66
sound.Add({
	name = "wfoly_plr_sh_romeo872_caldb_reload_empty_07",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_romeo870/wfoly_sh_romeo870_caldb_reload_empty_chamber.ogg",
		}
})
-- Sound: 67
sound.Add({
	name = "wfoly_plr_sh_romeo872_caldb_reload_empty_08",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_romeo870/wfoly_sh_romeo870_caldb_reload_empty_end.ogg",
		}
})
-- Sound: 68
sound.Add({
	name = "wfoly_plr_sh_romeo873_caldb_reload_empty_fast_01",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_romeo870/wfoly_sh_romeo870_caldb_reload_empty_fast_pump_foreend.ogg",
		}
})
-- Sound: 69
sound.Add({
	name = "wfoly_plr_sh_romeo873_caldb_reload_empty_fast_02",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_romeo870/wfoly_sh_romeo870_caldb_reload_empty_fast_magout.ogg",
		}
})
-- Sound: 70
sound.Add({
	name = "wfoly_plr_sh_romeo873_caldb_reload_empty_fast_03",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_romeo870/wfoly_sh_romeo870_caldb_reload_empty_fast_magup.ogg",
		}
})
-- Sound: 71
sound.Add({
	name = "wfoly_plr_sh_romeo873_caldb_reload_empty_fast_04",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_romeo870/wfoly_sh_romeo870_caldb_reload_empty_fast_magin.ogg",
		}
})
-- Sound: 72
sound.Add({
	name = "wfoly_plr_sh_romeo873_caldb_reload_empty_fast_05",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_romeo870/wfoly_sh_romeo870_caldb_reload_empty_fast_chamber.ogg",
		}
})
-- Sound: 73
sound.Add({
	name = "wfoly_plr_sh_romeo873_caldb_reload_empty_fast_06",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_romeo870/wfoly_sh_romeo870_caldb_reload_empty_fast_end.ogg",
		}
})
-- Sound: 74
sound.Add({
	name = "wfoly_plr_sh_romeo874_caldb_reload_fast_01",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_romeo870/wfoly_sh_romeo870_caldb_reload_fast_raise.ogg",
		}
})
-- Sound: 75
sound.Add({
	name = "wfoly_plr_sh_romeo874_caldb_reload_fast_02",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_romeo870/wfoly_sh_romeo870_caldb_reload_fast_magout.ogg",
		}
})
-- Sound: 76
sound.Add({
	name = "wfoly_plr_sh_romeo874_caldb_reload_fast_03",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_romeo870/wfoly_sh_romeo870_caldb_reload_fast_magup.ogg",
		}
})
-- Sound: 77
sound.Add({
	name = "wfoly_plr_sh_romeo874_caldb_reload_fast_04",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_romeo870/wfoly_sh_romeo870_caldb_reload_fast_magin.ogg",
		}
})
-- Sound: 78
sound.Add({
	name = "wfoly_plr_sh_romeo874_caldb_reload_fast_05",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_romeo870/wfoly_sh_romeo870_caldb_reload_fast_end.ogg",
		}
})
