-- Generated by GmodSoundGen

-- File: D:\Downloads\important_stuff_v2\Tools\GmodSoundGen_0519\weapon_sm_smgolf45.all.lua
-- Total length: 106
sound.Add({
    name =           "wfoly_plr_sm_smgolf45_raise_first_01",
    channel =        CHAN_WPNFOLEY +1,
    volume =         1,
    sound = {"reloads/iw8_smgolf45/wfoly_sm_smgolf45_raise_first_up.ogg"}              
})
sound.Add({
    name =           "wfoly_plr_sm_smgolf45_raise_first_02",
    channel =        CHAN_WPNFOLEY +2,
    volume =         1,
    sound = {"reloads/iw8_smgolf45/wfoly_sm_smgolf45_raise_first_bolt_pull.ogg"}              
})
sound.Add({
    name =           "wfoly_plr_sm_smgolf45_raise_first_03",
    channel =        CHAN_WPNFOLEY +3,
    volume =         1,
    sound = {"reloads/iw8_smgolf45/wfoly_sm_smgolf45_raise_first_mvmnt.ogg"}              
})
sound.Add({
    name =           "wfoly_plr_sm_smgolf45_raise_first_04",
    channel =        CHAN_WPNFOLEY +4,
    volume =         1,
    sound = {"reloads/iw8_smgolf45/wfoly_sm_smgolf45_raise_first_bolt_release.ogg"}              
})
sound.Add({
    name =           "wfoly_plr_sm_smgolf45_raise_first_05",
    channel =        CHAN_WPNFOLEY +5,
    volume =         1,
    sound = {"reloads/iw8_smgolf45/wfoly_sm_smgolf45_raise_first_end.ogg"}              
})

sound.Add({
    name =           "weap_smgolf45_fire_first_plr",
    channel =        CHAN_WPNFOLEY +20,
    volume =         1,
    sound = {"weapons/smgolf45/weap_smgolf45_fire_hammer_01.ogg"}              
})        
sound.Add({
    name =           "weap_smgolf45_disconnector_plr",
    channel =        CHAN_WPNFOLEY +21,
    volume =         1,
    sound = {"weapons/smgolf45/weap_smgolf45_disconnector_plr_01.ogg"}              
})


-- Sound: 0
sound.Add({
	name = "mount_enter_side_smgolf45_vestlight_plr",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/mount/mount_enter_side_mpapa5_vestlight_plr.ogg",
		}
})



sound.Add({
	name = "weap_sm_mpapa5_selector_off",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/selector/weap_sm_mpapa5_selector_off.ogg",
		}
})
-- Sound: 5
sound.Add({
	name = "weap_sm_mpapa5_selector_on",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/selector/weap_sm_mpapa5_selector_on.ogg",
		}
})
-- Sound: 14
sound.Add({
	name = "weap_smgolf45_fire_plr_lfe",
	channel = CHAN_WEAPON,
	level = 140,
	volume = 1,
	pitch = {80,110},
	sound = 
		"^weapons/smgolf45/weap_smgolf45_fire_plr_01.wav",
		
})
-- Sound: 18
sound.Add({
	name = "weap_smgolf45_sup_fire_plr_lfe",
	channel = CHAN_WEAPON,
	volume = 1,
	pitch = {80,110},
	sound = {
		"weapons/smgolf45/weap_smgolf45_sup_fire_plr_01.ogg",
		}
})
-- Sound: 24
sound.Add({
	name = "wfoly_plr_sm_smgolf45_ads_down",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mpapa5/wfoly_sm_mpapa5_ads_down.ogg",
		}
})
-- Sound: 25
sound.Add({
	name = "wfoly_plr_sm_smgolf45_ads_up",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mpapa5/wfoly_sm_mpapa5_ads_up.ogg",
		}
})
-- Sound: 26
sound.Add({
	name = "wfoly_plr_sm_smgolf45_drop_01",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_drop.ogg",
		}
})
-- Sound: 27
sound.Add({
	name = "wfoly_plr_sm_smgolf45_drop_quick_01",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_drop_quick.ogg",
		}
})
-- Sound: 28
sound.Add({
	name = "wfoly_plr_sm_smgolf45_hybrid_scope_side_off",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/hybrid_scope/wfoly_plr_sm_mpapa5_hybrid_scope_side_off.ogg",
		}
})
-- Sound: 29
sound.Add({
	name = "wfoly_plr_sm_smgolf45_hybrid_scope_side_on",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/hybrid_scope/wfoly_plr_sm_mpapa5_hybrid_scope_side_on.ogg",
		}
})
-- Sound: 30
sound.Add({
	name = "wfoly_plr_sm_smgolf45_hybrid_scope_top_in",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/hybrid_scope/wfoly_plr_sm_mpapa5_hybrid_scope_top_in.ogg",
		}
})
-- Sound: 31
sound.Add({
	name = "wfoly_plr_sm_smgolf45_hybrid_scope_top_out",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/hybrid_scope/wfoly_plr_sm_mpapa5_hybrid_scope_top_out.ogg",
		}
})
-- Sound: 32
sound.Add({
	name = "wfoly_plr_sm_smgolf45_hybrid_west02_toggle_off_01",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_hybrid_west02_toggle_off.ogg",
		}
})
-- Sound: 33
sound.Add({
	name = "wfoly_plr_sm_smgolf45_hybrid_west02_toggle_on_01",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_hybrid_west02_toggle_on.ogg",
		}
})
-- Sound: 34
sound.Add({
	name = "wfoly_plr_sm_smgolf45_inspect_01",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_inspect_01.ogg",
		}
})
-- Sound: 35
sound.Add({
	name = "wfoly_plr_sm_smgolf45_inspect_02",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_inspect_02.ogg",
		}
})
-- Sound: 36
sound.Add({
	name = "wfoly_plr_sm_smgolf45_inspect_03",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_inspect_03.ogg",
		}
})
-- Sound: 37
sound.Add({
	name = "wfoly_plr_sm_smgolf45_inspect_04",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_inspect_04.ogg",
		}
})
-- Sound: 38
sound.Add({
	name = "wfoly_plr_sm_smgolf45_inspect_05",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_inspect_05.ogg",
		}
})
-- Sound: 39
sound.Add({
	name = "wfoly_plr_sm_smgolf45_raise_quick_01",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_raise_quick.ogg",
		}
})
-- Sound: 40
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_01",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_raise.ogg",
		}
})
-- Sound: 41
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_02",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_magout.ogg",
		}
})
-- Sound: 42
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_03",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_magin.ogg",
		}
})
-- Sound: 43
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_04",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_end.ogg",
		}
})
-- Sound: 44
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_empty_01",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_empty_raise.ogg",
		}
})
-- Sound: 45
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_empty_02",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_empty_magout.ogg",
		}
})
-- Sound: 46
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_empty_03",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_empty_maghit.ogg",
		}
})
-- Sound: 47
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_empty_04",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_empty_magin.ogg",
		}
})
-- Sound: 48
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_empty_045",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		" ",
		}
})
-- Sound: 49
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_empty_05",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_empty_bolt_release.ogg",
		}
})
-- Sound: 50
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_empty_06",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_empty_end.ogg",
		}
})
-- Sound: 51
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_empty_fast_01",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_empty_fast_raise.ogg",
		}
})
-- Sound: 52
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_empty_fast_02",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_empty_fast_magout.ogg",
		}
})
-- Sound: 53
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_empty_fast_03",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_empty_fast_maghit.ogg",
		}
})
-- Sound: 54
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_empty_fast_04",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_empty_fast_magin.ogg",
		}
})
-- Sound: 55
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_empty_fast_05",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_empty_fast_charge.ogg",
		}
})
-- Sound: 56
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_empty_fast_06",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_empty_fast_end.ogg",
		}
})
-- Sound: 57
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_empty_fast_smag_01",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_empty_fast_smag_raise.ogg",
		}
})
-- Sound: 58
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_empty_fast_smag_02",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_empty_fast_smag_magout.ogg",
		}
})
-- Sound: 59
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_empty_fast_smag_03",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_empty_fast_smag_magin.ogg",
		}
})
-- Sound: 60
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_empty_fast_smag_04",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_empty_fast_smag_charge.ogg",
		}
})
-- Sound: 61
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_empty_fast_smag_05",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_empty_fast_smag_end.ogg",
		}
})
-- Sound: 62
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_empty_fast_xmaglrg_01",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_empty_fast_xmaglrg_raise.ogg",
		}
})
-- Sound: 63
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_empty_fast_xmaglrg_02",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_empty_fast_xmaglrg_magout.ogg",
		}
})
-- Sound: 64
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_empty_fast_xmaglrg_03",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_empty_fast_xmaglrg_magin.ogg",
		}
})
-- Sound: 65
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_empty_fast_xmaglrg_04",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_empty_fast_xmaglrg_end.ogg",
		}
})
-- Sound: 66
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_empty_fast_xmaglrg_05",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_empty_fast_xmaglrg_charge.ogg",
		}
})
-- Sound: 67
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_empty_smag_01",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_empty_smag_raise.ogg",
		}
})
-- Sound: 68
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_empty_smag_02",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_empty_smag_magout.ogg",
		}
})
-- Sound: 69
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_empty_smag_03",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_empty_smag_maghit.ogg",
		}
})
-- Sound: 70
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_empty_smag_04",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_empty_smag_magin.ogg",
		}
})
-- Sound: 71
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_empty_smag_05",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_empty_smag_end.ogg",
		}
})
-- Sound: 72
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_empty_smag_06",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_empty_smag_charge.ogg",
		}
})
-- Sound: 73
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_empty_xmaglrg_01",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_empty_xmaglrg_raise.ogg",
		}
})
-- Sound: 74
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_empty_xmaglrg_02",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_empty_xmaglrg_magout.ogg",
		}
})
-- Sound: 75
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_empty_xmaglrg_03",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_empty_xmaglrg_maghit.ogg",
		}
})
-- Sound: 76
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_empty_xmaglrg_04",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_empty_xmaglrg_magin.ogg",
		}
})
-- Sound: 77
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_empty_xmaglrg_05",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_empty_xmaglrg_charge.ogg",
		}
})
-- Sound: 78
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_empty_xmaglrg_06",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_empty_xmaglrg_end.ogg",
		}
})
-- Sound: 79
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_fast_01",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_fast_raise.ogg",
		}
})
-- Sound: 80
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_fast_02",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_fast_magout.ogg",
		}
})
-- Sound: 81
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_fast_03",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_fast_maghit.ogg",
		}
})
-- Sound: 82
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_fast_04",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_fast_magin.ogg",
		}
})
-- Sound: 83
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_fast_05",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_fast_end.ogg",
		}
})
-- Sound: 84
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_fast_smag_01",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_fast_smag_raise.ogg",
		}
})
-- Sound: 85
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_fast_smag_02",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_fast_smag_magout.ogg",
		}
})
-- Sound: 86
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_fast_smag_03",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_fast_smag_magin.ogg",
		}
})
-- Sound: 87
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_fast_smag_04",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_fast_smag_end.ogg",
		}
})
-- Sound: 88
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_fast_xmaglrg_01",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_fast_xmaglrg_raise.ogg",
		}
})
-- Sound: 89
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_fast_xmaglrg_02",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_fast_xmaglrg_magout.ogg",
		}
})
-- Sound: 90
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_fast_xmaglrg_03",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_fast_xmaglrg_arm.ogg",
		}
})
-- Sound: 91
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_fast_xmaglrg_04",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_fast_xmaglrg_maghit.ogg",
		}
})
-- Sound: 92
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_fast_xmaglrg_05",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_fast_xmaglrg_magin.ogg",
		}
})
-- Sound: 93
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_fast_xmaglrg_06",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_fast_xmaglrg_end.ogg",
		}
})
-- Sound: 94
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_smag_01",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_smag_raise.ogg",
		}
})
-- Sound: 95
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_smag_02",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_smag_magout.ogg",
		}
})
-- Sound: 96
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_smag_03",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_smag_maghit.ogg",
		}
})
-- Sound: 97
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_smag_04",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_smag_magin.ogg",
		}
})
-- Sound: 98
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_smag_05",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_smag_end.ogg",
		}
})
-- Sound: 99
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_xmaglrg_01",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_xmaglrg_raise.ogg",
		}
})
-- Sound: 100
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_xmaglrg_02",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_xmaglrg_magout.ogg",
		}
})
-- Sound: 101
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_xmaglrg_03",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_xmaglrg_maghit.ogg",
		}
})
-- Sound: 102
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_xmaglrg_04",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_xmaglrg_magin.ogg",
		}
})
-- Sound: 103
sound.Add({
	name = "wfoly_plr_sm_smgolf45_reload_xmaglrg_05",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_smgolf45/wfoly_sm_smgolf45_reload_xmaglrg_end.ogg",
		}
})
-- Sound: 104
sound.Add({
	name = "wfoly_plr_sm_smgolf45_selectsemi_off_01",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/wfoly_sm_smgolf45_selectsemi_off.ogg",
		}
})
-- Sound: 105
sound.Add({
	name = "wfoly_plr_sm_smgolf45_selectsemi_on_01",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/wfoly_sm_smgolf45_selectsemi_on.ogg",
		}
})
