-- Generated by GmodSoundGen

-- File: D:\Downloads\important_stuff_v2\Tools\GmodSoundGen_0519\weapon_sm_papa90.all.lua
-- Total length: 75
sound.Add({
    name =           "wfoly_plr_sm_papa90_raise_first_01",
    channel =        CHAN_WPNFOLEY +1,
    volume =         1,
    sound = {"reloads/iw8_papa90/wfoly_sm_papa90_raise_first_start.ogg"}              
})
sound.Add({
    name =           "wfoly_plr_sm_papa90_raise_first_02",
    channel =        CHAN_WPNFOLEY +2,
    volume =         1,
    sound = {"reloads/iw8_papa90/wfoly_sm_papa90_raise_first_charge_01.ogg"}              
})
sound.Add({
    name =           "wfoly_plr_sm_papa90_raise_first_03",
    channel =        CHAN_WPNFOLEY +3,
    volume =         1,
    sound = {"reloads/iw8_papa90/wfoly_sm_papa90_first_raise_end.ogg"}              
})

sound.Add({
	name = "weap_papa90_disconnector_plr",
	channel = CHAN_WPNFOLEY + 1,

	volume = 1,
	pitch = {100,100},
	sound = {
		"weapons/papa90/weap_papa90_disconnector_plr_01.ogg",
		}
})
-- Sound: 23
sound.Add({
	name = "weap_papa90_fire_first_plr",
	channel = CHAN_WPNFOLEY + 2,

	volume = 1,
	pitch = {100,100},
	sound = {
		"weapons/papa90/weap_papa90_fire_first_plr_01.ogg",
		}
})


-- Sound: 10
sound.Add({
	name = "weap_papa90_fire_plr_lfe",
	channel = CHAN_WEAPON,
	level = 140,
	volume = 1,
	pitch = {80,110},
	sound = 
		"^weapons/papa90/weap_papa90_fire_plr_01.wav",
		
})
-- Sound: 14
sound.Add({
	name = "weap_papa90_sup_fire_plr_lfe",
	channel = CHAN_WEAPON,
	volume = 1,
	pitch = {80,110},
	sound = {
		"weapons/papa90/weap_papa90_sup_fire_plr_01.ogg",
		}
})
-- Sound: 17
sound.Add({
	name = "weap_sm_papa90_ads_down",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa90/wfoly_sm_papa90_ads_down.ogg",
		}
})
-- Sound: 18
sound.Add({
	name = "weap_sm_papa90_ads_up",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa90/wfoly_sm_papa90_ads_up.ogg",
		}
})
-- Sound: 19
sound.Add({
	name = "weap_sm_papa90_selector_off",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/selector/weap_sm_papa90_selector_off.ogg",
		}
})
-- Sound: 20
sound.Add({
	name = "weap_sm_papa90_selector_on",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/selector/weap_sm_papa90_selector_on.ogg",
		}
})
-- Sound: 21
sound.Add({
	name = "wfoly_plr_sm_papa90_drop_01",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa90/wfoly_sm_papa90_drop.ogg",
		}
})
-- Sound: 22
sound.Add({
	name = "wfoly_plr_sm_papa90_drop_quick_01",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa90/wfoly_sm_papa90_drop_quick.ogg",
		}
})
-- Sound: 23
sound.Add({
	name = "wfoly_plr_sm_papa90_gun_butt_hit_01_01",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa90/wfoly_sm_papa90_gun_butt_hit_cloth01.ogg",
		}
})
-- Sound: 24
sound.Add({
	name = "wfoly_plr_sm_papa90_gun_butt_hit_01_02",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa90/wfoly_sm_papa90_gun_butt_hit_cloth02.ogg",
		}
})
-- Sound: 25
sound.Add({
	name = "wfoly_plr_sm_papa90_gun_butt_hit_01_03",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa90/wfoly_sm_papa90_gun_butt_hit_cloth03.ogg",
		}
})
-- Sound: 26
sound.Add({
	name = "wfoly_plr_sm_papa90_hybrid_scope_side_off",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/hybrid_scope/wfoly_plr_sm_papa90_hybrid_scope_side_off.ogg",
		}
})
-- Sound: 27
sound.Add({
	name = "wfoly_plr_sm_papa90_hybrid_scope_side_on",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/hybrid_scope/wfoly_plr_sm_papa90_hybrid_scope_side_on.ogg",
		}
})
-- Sound: 28
sound.Add({
	name = "wfoly_plr_sm_papa90_hybrid_scope_snap_closed",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/hybrid_scope/wfoly_plr_ar_falpha_hybrid_scope_snap_closed.ogg",
		}
})
-- Sound: 29
sound.Add({
	name = "wfoly_plr_sm_papa90_hybrid_scope_snap_open",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/hybrid_scope/wfoly_plr_ar_falpha_hybrid_scope_snap_open.ogg",
		}
})
-- Sound: 30
sound.Add({
	name = "wfoly_plr_sm_papa90_hybrid_scope_top_in",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/hybrid_scope/wfoly_plr_sm_papa90_hybrid_scope_top_in.ogg",
		}
})
-- Sound: 31
sound.Add({
	name = "wfoly_plr_sm_papa90_hybrid_scope_top_out",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/hybrid_scope/wfoly_plr_sm_papa90_hybrid_scope_top_out.ogg",
		}
})
-- Sound: 32
sound.Add({
	name = "wfoly_plr_sm_papa90_inspect_01",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa90/wfoly_sm_papa90_inspect_01.ogg",
		}
})
-- Sound: 33
sound.Add({
	name = "wfoly_plr_sm_papa90_inspect_02",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa90/wfoly_sm_papa90_inspect_02.ogg",
		}
})
-- Sound: 34
sound.Add({
	name = "wfoly_plr_sm_papa90_inspect_03",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa90/wfoly_sm_papa90_inspect_03.ogg",
		}
})
-- Sound: 35
sound.Add({
	name = "wfoly_plr_sm_papa90_inspect_04",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa90/wfoly_sm_papa90_inspect_04.ogg",
		}
})
-- Sound: 36
sound.Add({
	name = "wfoly_plr_sm_papa90_inspect_05",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa90/wfoly_sm_papa90_inspect_05.ogg",
		}
})
-- Sound: 37
sound.Add({
	name = "wfoly_plr_sm_papa90_raise_01",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa90/wfoly_sm_papa90_raise.ogg",
		}
})
-- Sound: 38
sound.Add({
	name = "wfoly_plr_sm_papa90_raise_quick_01",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa90/wfoly_sm_papa90_raise_quick.ogg",
		}
})
-- Sound: 39
sound.Add({
	name = "wfoly_plr_sm_papa90_reload_01",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa90/wfoly_sm_papa90_reload_grabmag.ogg",
		}
})
-- Sound: 40
sound.Add({
	name = "wfoly_plr_sm_papa90_reload_02",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa90/wfoly_sm_papa90_reload_magout_01.ogg",
		}
})
-- Sound: 41
sound.Add({
	name = "wfoly_plr_sm_papa90_reload_03",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa90/wfoly_sm_papa90_reload_arm_down.ogg",
		}
})
-- Sound: 42
sound.Add({
	name = "wfoly_plr_sm_papa90_reload_04",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa90/wfoly_sm_papa90_reload_arm_up.ogg",
		}
})
-- Sound: 43
sound.Add({
	name = "wfoly_plr_sm_papa90_reload_05",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa90/wfoly_sm_papa90_reload_magin_v2_01.ogg",
		}
})
-- Sound: 44
sound.Add({
	name = "wfoly_plr_sm_papa90_reload_055",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa90/wfoly_sm_papa90_reload_magin_v2_02.ogg",
		}
})
-- Sound: 45
sound.Add({
	name = "wfoly_plr_sm_papa90_reload_06",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa90/wfoly_sm_papa90_reload_arm_maghit.ogg",
		}
})
-- Sound: 46
sound.Add({
	name = "wfoly_plr_sm_papa90_reload_07",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa90/wfoly_sm_papa90_reload_hitmag_01.ogg",
		}
})
-- Sound: 47
sound.Add({
	name = "wfoly_plr_sm_papa90_reload_08",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa90/wfoly_sm_papa90_reload_end.ogg",
		}
})
-- Sound: 48
sound.Add({
	name = "wfoly_plr_sm_papa90_reload_empty_01",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa90/wfoly_sm_papa90_reload_empty_gunrattle.ogg",
		}
})
-- Sound: 49
sound.Add({
	name = "wfoly_plr_sm_papa90_reload_empty_02",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa90/wfoly_sm_papa90_reload_empty_magout_01.ogg",
		}
})
-- Sound: 50
sound.Add({
	name = "wfoly_plr_sm_papa90_reload_empty_03",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa90/wfoly_sm_papa90_reload_empty_arm_down.ogg",
		}
})
-- Sound: 51
sound.Add({
	name = "wfoly_plr_sm_papa90_reload_empty_04",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa90/wfoly_sm_papa90_reload_empty_rattle.ogg",
		}
})
-- Sound: 52
sound.Add({
	name = "wfoly_plr_sm_papa90_reload_empty_05",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa90/wfoly_sm_papa90_reload_empty_magin_v2_01.ogg",
		}
})
-- Sound: 53
sound.Add({
	name = "wfoly_plr_sm_papa90_reload_empty_055",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa90/wfoly_sm_papa90_reload_empty_magin_v2_02.ogg",
		}
})
-- Sound: 54
sound.Add({
	name = "wfoly_plr_sm_papa90_reload_empty_06",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa90/wfoly_sm_papa90_reload_empty_arm_swing.ogg",
		}
})
-- Sound: 55
sound.Add({
	name = "wfoly_plr_sm_papa90_reload_empty_07",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa90/wfoly_sm_papa90_reload_empty_hitmag_02.ogg",
		}
})
-- Sound: 56
sound.Add({
	name = "wfoly_plr_sm_papa90_reload_empty_08",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa90/wfoly_sm_papa90_reload_empty_chamber_01.ogg",
		}
})
-- Sound: 57
sound.Add({
	name = "wfoly_plr_sm_papa90_reload_empty_09",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa90/wfoly_sm_papa90_reload_empty_end.ogg",
		}
})
-- Sound: 58
sound.Add({
	name = "wfoly_plr_sm_papa90_reload_empty_fast_01",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa90/wfoly_sm_papa90_reload_empty_fast_start.ogg",
		}
})
-- Sound: 59
sound.Add({
	name = "wfoly_plr_sm_papa90_reload_empty_fast_02",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa90/wfoly_sm_papa90_reload_empty_fast_magout_01.ogg",
		}
})
-- Sound: 60
sound.Add({
	name = "wfoly_plr_sm_papa90_reload_empty_fast_03",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa90/wfoly_sm_papa90_reload_empty_fast_magin.ogg",
		}
})
-- Sound: 61
sound.Add({
	name = "wfoly_plr_sm_papa90_reload_empty_fast_04",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa90/wfoly_sm_papa90_reload_empty_fast_magin_v2_01.ogg",
		}
})
-- Sound: 62
sound.Add({
	name = "wfoly_plr_sm_papa90_reload_empty_fast_045",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa90/wfoly_sm_papa90_reload_empty_fast_magin_v2_02.ogg",
		}
})
-- Sound: 63
sound.Add({
	name = "wfoly_plr_sm_papa90_reload_empty_fast_05",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa90/wfoly_sm_papa90_reload_empty_hitmag_01.ogg",
		}
})
-- Sound: 64
sound.Add({
	name = "wfoly_plr_sm_papa90_reload_empty_fast_06",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa90/wfoly_sm_papa90_reload_empty_fast_chamber_01.ogg",
		}
})
-- Sound: 65
sound.Add({
	name = "wfoly_plr_sm_papa90_reload_empty_fast_07",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa90/wfoly_sm_papa90_reload_empty_fast_end.ogg",
		}
})
-- Sound: 66
sound.Add({
	name = "wfoly_plr_sm_papa90_reload_fast_01",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa90/wfoly_sm_papa90_reload_fast_cloth02.ogg",
		}
})
-- Sound: 67
sound.Add({
	name = "wfoly_plr_sm_papa90_reload_fast_02",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa90/wfoly_sm_papa90_reload_fast_magout_01.ogg",
		}
})
-- Sound: 68
sound.Add({
	name = "wfoly_plr_sm_papa90_reload_fast_03",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa90/wfoly_sm_papa90_reload_fast_cloth.ogg",
		}
})
-- Sound: 69
sound.Add({
	name = "wfoly_plr_sm_papa90_reload_fast_04",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa90/wfoly_sm_papa90_reload_fast_cloth03.ogg",
		}
})
-- Sound: 70
sound.Add({
	name = "wfoly_plr_sm_papa90_reload_fast_05",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa90/wfoly_sm_papa90_reload_fast_magin_v2_01.ogg",
		}
})
-- Sound: 71
sound.Add({
	name = "wfoly_plr_sm_papa90_reload_fast_055",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa90/wfoly_sm_papa90_reload_fast_magin_v2_02.ogg",
		}
})
-- Sound: 72
sound.Add({
	name = "wfoly_plr_sm_papa90_reload_fast_06",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa90/wfoly_sm_papa90_reload_fast_maghit.ogg",
		}
})
-- Sound: 73
sound.Add({
	name = "wfoly_plr_sm_papa90_reload_fast_07",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa90/wfoly_sm_papa90_reload_fast_maghit_02.ogg",
		}
})
-- Sound: 74
sound.Add({
	name = "wfoly_plr_sm_papa90_reload_fast_08",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa90/wfoly_sm_papa90_reload_fast_end.ogg",
		}
})
