-- Generated by GmodSoundGen

-- File: D:\Downloads\important_stuff_v2\Tools\GmodSoundGen_0519\weapon_lm_pkilo.all.lua
-- Total length: 80

-- Sound: 4
sound.Add({
	name = "weap_lm_pkilo_ads_down",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_lm_pkilo_ads_down.ogg",
		}
})
-- Sound: 5
sound.Add({
	name = "weap_lm_pkilo_ads_up",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_lm_pkilo_ads_up.ogg",
		}
})
-- Sound: 8
sound.Add({
	name = "weap_pkilo_fire_plr",
	channel = CHAN_WEAPON,
	level = 140,
	volume = 1,
	pitch = {80,100},
	sound = 
		"^weapons/pkilo/weap_pkilo_fire_plr_01.wav",
		
})
-- Sound: 12
sound.Add({
	name = "weap_pkilo_prefire_plr",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"weapons/pkilo/weap_pkilo_prefire_plr_01.ogg",
		}
})
-- Sound: 13
sound.Add({
	name = "weap_pkilo_sup_plr",
	channel = CHAN_WEAPON,
	level = 140,
	volume = 1,
	pitch = {80,100},
	sound = 
		"^weapons/pkilo/weap_pkilo_sup_plr_01.wav",
		
})
-- Sound: 17
sound.Add({
	name = "wfoly_plr_lm_pkilo_drop_01",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_plr_lm_pkilo_drop.ogg",
		}
})
-- Sound: 17
sound.Add({
	name = "wfoly_plr_lm_pkilo_raise_first_01",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_plr_lm_pkilo_raise_first_lift.ogg",
		}
})
sound.Add({
	name = "wfoly_plr_lm_pkilo_raise_first_02",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_plr_lm_pkilo_raise_first_handle.ogg",
		}
})
sound.Add({
	name = "wfoly_plr_lm_pkilo_raise_first_03",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_plr_lm_pkilo_raise_first_charge.ogg",
		}
})
sound.Add({
	name = "wfoly_plr_lm_pkilo_raise_first_04",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_plr_lm_pkilo_raise_first_end.ogg",
		}
})
-- Sound: 18
sound.Add({
	name = "wfoly_plr_lm_pkilo_drop_empty_01",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_plr_lm_pkilo_drop_empty.ogg",
		}
})
-- Sound: 19
sound.Add({
	name = "wfoly_plr_lm_pkilo_drop_quick_01",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_plr_lm_pkilo_drop_quick.ogg",
		}
})
-- Sound: 20
sound.Add({
	name = "wfoly_plr_lm_pkilo_gun_butt_hit_01_01",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_plr_lm_pkilo_gun_butt_hit_01.ogg",
		}
})
-- Sound: 21
sound.Add({
	name = "wfoly_plr_lm_pkilo_gun_butt_hit_02_01",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_plr_lm_pkilo_gun_butt_hit_02.ogg",
		}
})
-- Sound: 22
sound.Add({
	name = "wfoly_plr_lm_pkilo_hybrid_scope_side_off",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/hybrid_scope/wfoly_plr_lm_pkilo_hybrid_side_off.ogg",
		}
})
-- Sound: 23
sound.Add({
	name = "wfoly_plr_lm_pkilo_hybrid_scope_side_on",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/hybrid_scope/wfoly_plr_lm_pkilo_hybrid_side_on.ogg",
		}
})
-- Sound: 24
sound.Add({
	name = "wfoly_plr_lm_pkilo_hybrid_scope_snap_closed",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/hybrid_scope/wfoly_plr_ar_falpha_hybrid_scope_snap_closed.ogg",
		}
})
-- Sound: 25
sound.Add({
	name = "wfoly_plr_lm_pkilo_hybrid_scope_snap_open",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/hybrid_scope/wfoly_plr_ar_falpha_hybrid_scope_snap_open.ogg",
		}
})
-- Sound: 26
sound.Add({
	name = "wfoly_plr_lm_pkilo_hybrid_scope_top_in",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/hybrid_scope/wfoly_plr_lm_pkilo_hybrid_top_in.ogg",
		}
})
-- Sound: 27
sound.Add({
	name = "wfoly_plr_lm_pkilo_hybrid_scope_top_out",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/hybrid_scope/wfoly_plr_lm_pkilo_hybrid_top_out.ogg",
		}
})
-- Sound: 28
sound.Add({
	name = "wfoly_plr_lm_pkilo_idle_active_01",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_plr_lm_pkilo_idle_active_mvmnt_1.ogg",
		}
})
-- Sound: 29
sound.Add({
	name = "wfoly_plr_lm_pkilo_idle_active_02",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_plr_lm_pkilo_idle_active_mvmnt_2.ogg",
		}
})
-- Sound: 30
sound.Add({
	name = "wfoly_plr_lm_pkilo_idle_active_03",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_plr_lm_pkilo_idle_active_mvmnt_3.ogg",
		}
})
-- Sound: 31
sound.Add({
	name = "wfoly_plr_lm_pkilo_idle_active_04",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_plr_lm_pkilo_idle_active_mvmnt_4.ogg",
		}
})
-- Sound: 32
sound.Add({
	name = "wfoly_plr_lm_pkilo_inspect_01",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_lm_pkilo_inspect_01.ogg",
		}
})
-- Sound: 33
sound.Add({
	name = "wfoly_plr_lm_pkilo_inspect_02",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_lm_pkilo_inspect_02.ogg",
		}
})
-- Sound: 34
sound.Add({
	name = "wfoly_plr_lm_pkilo_inspect_03",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_lm_pkilo_inspect_03.ogg",
		}
})
-- Sound: 35
sound.Add({
	name = "wfoly_plr_lm_pkilo_raise_01",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_plr_lm_pkilo_raise.ogg",
		}
})
-- Sound: 36
sound.Add({
	name = "wfoly_plr_lm_pkilo_raise_empty_01",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_plr_lm_pkilo_raise_empty.ogg",
		}
})
-- Sound: 37
sound.Add({
	name = "wfoly_plr_lm_pkilo_raise_first_05",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_plr_lm_pkilo_raise_first_end.ogg",
		}
})
-- Sound: 38
sound.Add({
	name = "wfoly_plr_lm_pkilo_raise_quick_01",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_plr_lm_pkilo_raise_quick.ogg",
		}
})
-- Sound: 39
sound.Add({
	name = "wfoly_plr_lm_pkilo_reload_01",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_plr_lm_pkilo_reload_raise.ogg",
		}
})
-- Sound: 40
sound.Add({
	name = "wfoly_plr_lm_pkilo_reload_02",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_plr_lm_pkilo_reload_charge.ogg",
		}
})
-- Sound: 41
sound.Add({
	name = "wfoly_plr_lm_pkilo_reload_03",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_plr_lm_pkilo_reload_cover_open.ogg",
		}
})
-- Sound: 42
sound.Add({
	name = "wfoly_plr_lm_pkilo_reload_04",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_plr_lm_pkilo_reload_magout.ogg",
		}
})
-- Sound: 43
sound.Add({
	name = "wfoly_plr_lm_pkilo_reload_04_lift",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_plr_lm_pkilo_reload_empty_lift.ogg",
		}
})
-- Sound: 44
sound.Add({
	name = "wfoly_plr_lm_pkilo_reload_05",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_plr_lm_pkilo_reload_magin_v2_01.ogg",
		}
})
-- Sound: 45
sound.Add({
	name = "wfoly_plr_lm_pkilo_reload_055",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_plr_lm_pkilo_reload_magin_v2_02.ogg",
		}
})
-- Sound: 46
sound.Add({
	name = "wfoly_plr_lm_pkilo_reload_06",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_plr_lm_pkilo_reload_ammobelt.ogg",
		}
})
-- Sound: 47
sound.Add({
	name = "wfoly_plr_lm_pkilo_reload_07",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_plr_lm_pkilo_reload_cover_close.ogg",
		}
})
-- Sound: 48
sound.Add({
	name = "wfoly_plr_lm_pkilo_reload_08",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_plr_lm_pkilo_reload_load_charge.ogg",
		}
})
-- Sound: 49
sound.Add({
	name = "wfoly_plr_lm_pkilo_reload_09",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_plr_lm_pkilo_reload_end.ogg",
		}
})
-- Sound: 50
sound.Add({
	name = "wfoly_plr_lm_pkilo_reload_empty_01",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_plr_lm_pkilo_reload_empty_charge.ogg",
		}
})
-- Sound: 51
sound.Add({
	name = "wfoly_plr_lm_pkilo_reload_empty_02",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_plr_lm_pkilo_reload_empty_cover_open.ogg",
		}
})
-- Sound: 52
sound.Add({
	name = "wfoly_plr_lm_pkilo_reload_empty_03",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_plr_lm_pkilo_reload_empty_magout.ogg",
		}
})
-- Sound: 53
sound.Add({
	name = "wfoly_plr_lm_pkilo_reload_empty_04",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_plr_lm_pkilo_reload_empty_lift.ogg",
		}
})
-- Sound: 54
sound.Add({
	name = "wfoly_plr_lm_pkilo_reload_empty_05",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_plr_lm_pkilo_reload_empty_magin_v2_01.ogg",
		}
})
-- Sound: 55
sound.Add({
	name = "wfoly_plr_lm_pkilo_reload_empty_055",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_plr_lm_pkilo_reload_empty_magin_v2_02.ogg",
		}
})
-- Sound: 56
sound.Add({
	name = "wfoly_plr_lm_pkilo_reload_empty_06",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_plr_lm_pkilo_reload_empty_ammobelt.ogg",
		}
})
-- Sound: 57
sound.Add({
	name = "wfoly_plr_lm_pkilo_reload_empty_07",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_plr_lm_pkilo_reload_empty_cover_close.ogg",
		}
})
-- Sound: 58
sound.Add({
	name = "wfoly_plr_lm_pkilo_reload_empty_08",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_plr_lm_pkilo_reload_empty_load_charge.ogg",
		}
})
-- Sound: 59
sound.Add({
	name = "wfoly_plr_lm_pkilo_reload_empty_09",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_plr_lm_pkilo_reload_empty_end.ogg",
		}
})
-- Sound: 60
sound.Add({
	name = "wfoly_plr_lm_pkilo_reload_empty_fast_01",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_plr_lm_pkilo_reload_empty_fast_raise.ogg",
		}
})
-- Sound: 61
sound.Add({
	name = "wfoly_plr_lm_pkilo_reload_empty_fast_02",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_plr_lm_pkilo_reload_empty_fast_charge.ogg",
		}
})
-- Sound: 62
sound.Add({
	name = "wfoly_plr_lm_pkilo_reload_empty_fast_03",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_plr_lm_pkilo_reload_empty_fast_cover_open.ogg",
		}
})
-- Sound: 63
sound.Add({
	name = "wfoly_plr_lm_pkilo_reload_empty_fast_04",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_plr_lm_pkilo_reload_empty_fast_magout.ogg",
		}
})
-- Sound: 64
sound.Add({
	name = "wfoly_plr_lm_pkilo_reload_empty_fast_05",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_plr_lm_pkilo_reload_empty_fast_magin_v2_01.ogg",
		}
})
-- Sound: 65
sound.Add({
	name = "wfoly_plr_lm_pkilo_reload_empty_fast_055",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_plr_lm_pkilo_reload_empty_fast_magin_v2_02.ogg",
		}
})
-- Sound: 66
sound.Add({
	name = "wfoly_plr_lm_pkilo_reload_empty_fast_06",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_plr_lm_pkilo_reload_empty_fast_ammobelt.ogg",
		}
})
-- Sound: 67
sound.Add({
	name = "wfoly_plr_lm_pkilo_reload_empty_fast_07",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_plr_lm_pkilo_reload_empty_fast_cover_close.ogg",
		}
})
-- Sound: 68
sound.Add({
	name = "wfoly_plr_lm_pkilo_reload_empty_fast_08",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_plr_lm_pkilo_reload_empty_fast_load_charge.ogg",
		}
})
-- Sound: 69
sound.Add({
	name = "wfoly_plr_lm_pkilo_reload_empty_fast_09",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_plr_lm_pkilo_reload_empty_fast_end.ogg",
		}
})
-- Sound: 70
sound.Add({
	name = "wfoly_plr_lm_pkilo_reload_fast_01",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_plr_lm_pkilo_reload_fast_raise.ogg",
		}
})
-- Sound: 71
sound.Add({
	name = "wfoly_plr_lm_pkilo_reload_fast_02",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_plr_lm_pkilo_reload_fast_charge.ogg",
		}
})
-- Sound: 72
sound.Add({
	name = "wfoly_plr_lm_pkilo_reload_fast_03",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_plr_lm_pkilo_reload_fast_cover_open.ogg",
		}
})
-- Sound: 73
sound.Add({
	name = "wfoly_plr_lm_pkilo_reload_fast_04",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_plr_lm_pkilo_reload_fast_magout.ogg",
		}
})
-- Sound: 74
sound.Add({
	name = "wfoly_plr_lm_pkilo_reload_fast_05",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_plr_lm_pkilo_reload_fast_magin_v2_01.ogg",
		}
})
-- Sound: 75
sound.Add({
	name = "wfoly_plr_lm_pkilo_reload_fast_055",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_plr_lm_pkilo_reload_fast_magin_v2_02.ogg",
		}
})
-- Sound: 76
sound.Add({
	name = "wfoly_plr_lm_pkilo_reload_fast_06",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_plr_lm_pkilo_reload_fast_ammobelt.ogg",
		}
})
-- Sound: 77
sound.Add({
	name = "wfoly_plr_lm_pkilo_reload_fast_07",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_plr_lm_pkilo_reload_fast_cover_close.ogg",
		}
})
-- Sound: 78
sound.Add({
	name = "wfoly_plr_lm_pkilo_reload_fast_08",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_plr_lm_pkilo_reload_fast_load_charge.ogg",
		}
})
-- Sound: 79
sound.Add({
	name = "wfoly_plr_lm_pkilo_reload_fast_09",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_pkilo/wfoly_plr_lm_pkilo_reload_fast_end.ogg",
		}
})
