-- Generated by GmodSoundGen

-- File: D:\Downloads\important_stuff_v2\Tools\GmodSoundGen_0519\weapon_sn_delta.all.lua
-- Total length: 88

-- Sound: 7
sound.Add({
	name = "weap_delta_fire_plr",
	channel = CHAN_WEAPON,
	level = 140,
	volume = 1,
	pitch = {90,110},
	sound = 
		"^weapons/delta/weap_delta_fire_plr_01.wav",
		
})
sound.Add({
	name = "weap_delta_fire_first",
	channel = CHAN_WEAPON +1,
	volume = 1,
	pitch = {90,110},
	sound = {
		"weapons/delta/weap_delta_fire_first_plr_01.ogg",
		}
})
sound.Add({
	name = "weap_delta_fire_disconnector",
	channel = CHAN_WEAPON +2,
	volume = 1,
	pitch = {90,110},
	sound = {
		"weapons/delta/weap_delta_disconnector_plr_01.ogg",
		}
})
sound.Add({
	name = "weap_delta_fire_plr_sup",
	channel = CHAN_WEAPON,
	level = 140,
	volume = 1,
	pitch = {90,110},
	sound = 
		"^weapons/delta/weap_delta_sup_plr_01.wav",
		
})
-- Sound: 22
sound.Add({
	name = "weap_sn_delta_ads_down",
	channel = CHAN_WPNFOLEY + 8,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/weap_sn_delta_ads_down.ogg",
		}
})
-- Sound: 23
sound.Add({
	name = "weap_sn_delta_ads_up",
	channel = CHAN_WPNFOLEY + 9,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/weap_sn_delta_ads_up.ogg",
		}
})
-- Sound: 24
sound.Add({
	name = "wfoly_plr_sn_delta_drop_01",
	channel = CHAN_WPNFOLEY + 10,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_drop_mvmnt.ogg",
		}
})
-- Sound: 28
sound.Add({
	name = "wfoly_plr_sn_delta_inspect_01",
	channel = CHAN_WPNFOLEY + 4,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_inspect_01.ogg",
		}
})
-- Sound: 29
sound.Add({
	name = "wfoly_plr_sn_delta_inspect_02",
	channel = CHAN_WPNFOLEY + 5,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_inspect_02.ogg",
		}
})
-- Sound: 30
sound.Add({
	name = "wfoly_plr_sn_delta_inspect_03",
	channel = CHAN_WPNFOLEY + 6,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_inspect_03.ogg",
		}
})
-- Sound: 31
sound.Add({
	name = "wfoly_plr_sn_delta_raise_01",
	channel = CHAN_WPNFOLEY + 7,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_raise_mvmnt.ogg",
		}
})
sound.Add({
	name = "wfoly_plr_sn_delta_raise_first_01",
	channel = CHAN_WPNFOLEY + 1,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_raise_first_mvmnt.ogg",
		}
})
sound.Add({
	name = "wfoly_plr_sn_delta_raise_first_02",
	channel = CHAN_WPNFOLEY + 2,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_raise_first_charge_01.ogg",
		}
})
sound.Add({
	name = "wfoly_plr_sn_delta_raise_first_03",
	channel = CHAN_WPNFOLEY + 3,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_raise_first_end.ogg",
		}
})

-- Sound: 33
sound.Add({
	name = "wfoly_plr_sn_delta_reload_01",
	channel = CHAN_WPNFOLEY + 9,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_reload_raise.ogg",
		}
})
-- Sound: 34
sound.Add({
	name = "wfoly_plr_sn_delta_reload_02",
	channel = CHAN_WPNFOLEY + 10,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_reload_magout_01.ogg",
		}
})
-- Sound: 35
sound.Add({
	name = "wfoly_plr_sn_delta_reload_03",
	channel = CHAN_WPNFOLEY + 1,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_reload_cloth_01.ogg",
		}
})
-- Sound: 36
sound.Add({
	name = "wfoly_plr_sn_delta_reload_04",
	channel = CHAN_WPNFOLEY + 2,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_reload_cloth_02.ogg",
		}
})
-- Sound: 37
sound.Add({
	name = "wfoly_plr_sn_delta_reload_05",
	channel = CHAN_WPNFOLEY + 3,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_reload_magin_v2_01.ogg",
		}
})
-- Sound: 38
sound.Add({
	name = "wfoly_plr_sn_delta_reload_055",
	channel = CHAN_WPNFOLEY + 4,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_reload_magin_v2_02.ogg",
		}
})
-- Sound: 39
sound.Add({
	name = "wfoly_plr_sn_delta_reload_06",
	channel = CHAN_WPNFOLEY + 5,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_reload_end.ogg",
		}
})
-- Sound: 40
sound.Add({
	name = "wfoly_plr_sn_delta_reload_empty_01",
	channel = CHAN_WPNFOLEY + 6,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_reload_empty_raise.ogg",
		}
})
-- Sound: 41
sound.Add({
	name = "wfoly_plr_sn_delta_reload_empty_02",
	channel = CHAN_WPNFOLEY + 7,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_reload_empty_magout_01.ogg",
		}
})
-- Sound: 42
sound.Add({
	name = "wfoly_plr_sn_delta_reload_empty_03",
	channel = CHAN_WPNFOLEY + 8,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_reload_empty_throw_mag.ogg",
		}
})
-- Sound: 43
sound.Add({
	name = "wfoly_plr_sn_delta_reload_empty_04",
	channel = CHAN_WPNFOLEY + 9,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_reload_empty_magin_v2_01.ogg",
		}
})
-- Sound: 44
sound.Add({
	name = "wfoly_plr_sn_delta_reload_empty_045",
	channel = CHAN_WPNFOLEY + 10,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_reload_empty_magin_v2_02.ogg",
		}
})
-- Sound: 45
sound.Add({
	name = "wfoly_plr_sn_delta_reload_empty_05",
	channel = CHAN_WPNFOLEY + 1,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_reload_empty_end.ogg",
		}
})
-- Sound: 46
sound.Add({
	name = "wfoly_plr_sn_delta_reload_empty_06",
	channel = CHAN_WPNFOLEY + 2,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_reload_empty_charge_01.ogg",
		}
})
-- Sound: 47
sound.Add({
	name = "wfoly_plr_sn_delta_reload_empty_fast_01",
	channel = CHAN_WPNFOLEY + 3,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_reload_empty_fast_raise.ogg",
		}
})
-- Sound: 48
sound.Add({
	name = "wfoly_plr_sn_delta_reload_empty_fast_02",
	channel = CHAN_WPNFOLEY + 4,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_reload_empty_fast_maghit_01.ogg",
		}
})
-- Sound: 49
sound.Add({
	name = "wfoly_plr_sn_delta_reload_empty_fast_03",
	channel = CHAN_WPNFOLEY + 5,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_reload_empty_fast_magout_01.ogg",
		}
})
-- Sound: 50
sound.Add({
	name = "wfoly_plr_sn_delta_reload_empty_fast_04",
	channel = CHAN_WPNFOLEY + 6,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_reload_empty_fast_magin_v2_01.ogg",
		}
})
-- Sound: 51
sound.Add({
	name = "wfoly_plr_sn_delta_reload_empty_fast_045",
	channel = CHAN_WPNFOLEY + 7,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_reload_empty_fast_magin_v2_02.ogg",
		}
})
-- Sound: 52
sound.Add({
	name = "wfoly_plr_sn_delta_reload_empty_fast_05",
	channel = CHAN_WPNFOLEY + 8,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_reload_empty_fast_end.ogg",
		}
})
-- Sound: 53
sound.Add({
	name = "wfoly_plr_sn_delta_reload_empty_fast_06",
	channel = CHAN_WPNFOLEY + 9,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_reload_empty_fast_charge_01.ogg",
		}
})
-- Sound: 54
sound.Add({
	name = "wfoly_plr_sn_delta_reload_empty_fast_xmag_01",
	channel = CHAN_WPNFOLEY + 10,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_reload_empty_fast_xmag_rotate.ogg",
		}
})
-- Sound: 55
sound.Add({
	name = "wfoly_plr_sn_delta_reload_empty_fast_xmag_02",
	channel = CHAN_WPNFOLEY + 1,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_reload_empty_fast_xmag_maghit_01.ogg",
		}
})
-- Sound: 56
sound.Add({
	name = "wfoly_plr_sn_delta_reload_empty_fast_xmag_03",
	channel = CHAN_WPNFOLEY + 2,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_reload_empty_fast_xmag_magout_01.ogg",
		}
})
-- Sound: 57
sound.Add({
	name = "wfoly_plr_sn_delta_reload_empty_fast_xmag_04",
	channel = CHAN_WPNFOLEY + 3,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_reload_empty_fast_xmag_magin_v2_01.ogg",
		}
})
-- Sound: 58
sound.Add({
	name = "wfoly_plr_sn_delta_reload_empty_fast_xmag_045",
	channel = CHAN_WPNFOLEY + 4,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_reload_empty_fast_xmag_magin_v2_02.ogg",
		}
})
-- Sound: 59
sound.Add({
	name = "wfoly_plr_sn_delta_reload_empty_fast_xmag_05",
	channel = CHAN_WPNFOLEY + 5,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_reload_empty_fast_xmag_end.ogg",
		}
})
-- Sound: 60
sound.Add({
	name = "wfoly_plr_sn_delta_reload_empty_fast_xmag_06",
	channel = CHAN_WPNFOLEY + 6,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_reload_empty_fast_xmag_charge_01.ogg",
		}
})
-- Sound: 61
sound.Add({
	name = "wfoly_plr_sn_delta_reload_empty_xmag_01",
	channel = CHAN_WPNFOLEY + 7,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_reload_empty_xmag_raise.ogg",
		}
})
-- Sound: 62
sound.Add({
	name = "wfoly_plr_sn_delta_reload_empty_xmag_02",
	channel = CHAN_WPNFOLEY + 8,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_reload_empty_xmag_magout_01.ogg",
		}
})
-- Sound: 63
sound.Add({
	name = "wfoly_plr_sn_delta_reload_empty_xmag_03",
	channel = CHAN_WPNFOLEY + 9,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_reload_empty_xmag_mag_throw.ogg",
		}
})
-- Sound: 64
sound.Add({
	name = "wfoly_plr_sn_delta_reload_empty_xmag_04",
	channel = CHAN_WPNFOLEY + 10,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_reload_empty_xmag_magin_v2_01.ogg",
		}
})
-- Sound: 65
sound.Add({
	name = "wfoly_plr_sn_delta_reload_empty_xmag_045",
	channel = CHAN_WPNFOLEY + 1,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_reload_empty_xmag_magin_v2_02.ogg",
		}
})
-- Sound: 66
sound.Add({
	name = "wfoly_plr_sn_delta_reload_empty_xmag_05",
	channel = CHAN_WPNFOLEY + 2,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_reload_empty_xmag_rotate.ogg",
		}
})
-- Sound: 67
sound.Add({
	name = "wfoly_plr_sn_delta_reload_empty_xmag_06",
	channel = CHAN_WPNFOLEY + 3,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_reload_empty_xmag_end.ogg",
		}
})
-- Sound: 68
sound.Add({
	name = "wfoly_plr_sn_delta_reload_empty_xmag_07",
	channel = CHAN_WPNFOLEY + 4,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_reload_empty_xmag_charge_01.ogg",
		}
})
-- Sound: 69
sound.Add({
	name = "wfoly_plr_sn_delta_reload_fast_01",
	channel = CHAN_WPNFOLEY + 5,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_reload_fast_raise.ogg",
		}
})
-- Sound: 70
sound.Add({
	name = "wfoly_plr_sn_delta_reload_fast_02",
	channel = CHAN_WPNFOLEY + 6,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_reload_fast_magout_01.ogg",
		}
})
-- Sound: 71
sound.Add({
	name = "wfoly_plr_sn_delta_reload_fast_03",
	channel = CHAN_WPNFOLEY + 7,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_reload_fast_rotate.ogg",
		}
})
-- Sound: 72
sound.Add({
	name = "wfoly_plr_sn_delta_reload_fast_04",
	channel = CHAN_WPNFOLEY + 8,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_reload_fast_magin_v2_01.ogg",
		}
})
-- Sound: 73
sound.Add({
	name = "wfoly_plr_sn_delta_reload_fast_045",
	channel = CHAN_WPNFOLEY + 9,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_reload_fast_magin_v2_02.ogg",
		}
})
-- Sound: 74
sound.Add({
	name = "wfoly_plr_sn_delta_reload_fast_05",
	channel = CHAN_WPNFOLEY + 10,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_reload_fast_end.ogg",
		}
})
-- Sound: 75
sound.Add({
	name = "wfoly_plr_sn_delta_reload_fast_xmag_01",
	channel = CHAN_WPNFOLEY + 1,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_reload_fast_xmag_raise.ogg",
		}
})
-- Sound: 76
sound.Add({
	name = "wfoly_plr_sn_delta_reload_fast_xmag_02",
	channel = CHAN_WPNFOLEY + 2,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_reload_fast_xmag_magout_01.ogg",
		}
})
-- Sound: 77
sound.Add({
	name = "wfoly_plr_sn_delta_reload_fast_xmag_03",
	channel = CHAN_WPNFOLEY + 3,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_reload_fast_xmag_mvmnt.ogg",
		}
})
-- Sound: 78
sound.Add({
	name = "wfoly_plr_sn_delta_reload_fast_xmag_04",
	channel = CHAN_WPNFOLEY + 4,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_reload_fast_xmag_magin_v2_01.ogg",
		}
})
-- Sound: 79
sound.Add({
	name = "wfoly_plr_sn_delta_reload_fast_xmag_045",
	channel = CHAN_WPNFOLEY + 5,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_reload_fast_xmag_magin_v2_02.ogg",
		}
})
-- Sound: 80
sound.Add({
	name = "wfoly_plr_sn_delta_reload_fast_xmag_05",
	channel = CHAN_WPNFOLEY + 6,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_reload_fast_xmag_end.ogg",
		}
})
-- Sound: 81
sound.Add({
	name = "wfoly_plr_sn_delta_reload_xmag_01",
	channel = CHAN_WPNFOLEY + 7,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_reload_xmag_raise.ogg",
		}
})
-- Sound: 82
sound.Add({
	name = "wfoly_plr_sn_delta_reload_xmag_02",
	channel = CHAN_WPNFOLEY + 8,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_reload_xmag_maggrab_01.ogg",
		}
})
-- Sound: 83
sound.Add({
	name = "wfoly_plr_sn_delta_reload_xmag_03",
	channel = CHAN_WPNFOLEY + 9,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_reload_xmag_magout_01.ogg",
		}
})
-- Sound: 84
sound.Add({
	name = "wfoly_plr_sn_delta_reload_xmag_04",
	channel = CHAN_WPNFOLEY + 10,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_reload_xmag_cloth.ogg",
		}
})
-- Sound: 85
sound.Add({
	name = "wfoly_plr_sn_delta_reload_xmag_05",
	channel = CHAN_WPNFOLEY + 1,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_reload_xmag_magin_v2_01.ogg",
		}
})
-- Sound: 86
sound.Add({
	name = "wfoly_plr_sn_delta_reload_xmag_055",
	channel = CHAN_WPNFOLEY + 2,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_reload_xmag_magin_v2_02.ogg",
		}
})
-- Sound: 87
sound.Add({
	name = "wfoly_plr_sn_delta_reload_xmag_06",
	channel = CHAN_WPNFOLEY + 3,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_delta/wfoly_sn_delta_reload_xmag_end.ogg",
		}
})
