-- Generated by GmodSoundGen
sound.Add({
    name =           "wfoly_plr_sh_dpapa12_raise_first_01",
    channel =        CHAN_WPNFOLEY +1,
    volume =         1,
    sound = {"reloads/iw8_dpapa12/wfoly_sh_dpapa12_raise_first_lift.ogg"}              
})
sound.Add({
    name =           "wfoly_plr_sh_dpapa12_raise_first_02",
    channel =        CHAN_WPNFOLEY +2,
    volume =         1,
    sound = {
		"reloads/iw8_dpapa12/wfoly_sh_dpapa12_reload_empty_end_chamber_01_02.ogg",
		"reloads/iw8_dpapa12/wfoly_sh_dpapa12_reload_empty_end_chamber_01_03.ogg",
		"reloads/iw8_dpapa12/wfoly_sh_dpapa12_reload_empty_end_chamber_01_04.ogg",
		}              
})
sound.Add({
    name =           "wfoly_plr_sh_dpapa12_raise_first_03",
    channel =        CHAN_WPNFOLEY +3,
    volume =         1,
    sound = {"reloads/iw8_dpapa12/wfoly_sh_dpapa12_raise_first_end.ogg"

}              
})
-- File: D:\Downloads\important_stuff_v2\Tools\GmodSoundGen_0519\weapon_sh_dpapa12.all.lua
-- Total length: 55

-- Sound: 0
sound.Add({
	name = "mount_enter_side_dpapa12_vestlight_plr",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/mount/mount_enter_side_dpapa12_vestlight_plr.ogg",
		}
})
-- Sound: 1
sound.Add({
	name = "mount_enter_top_dpapa12_vestlight_plr",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/mount/mount_enter_top_dpapa12_vestlight_plr.ogg",
		}
})
-- Sound: 2
sound.Add({
	name = "mount_exit_side_dpapa12_vestlight_plr",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/mount/mount_exit_side_dpapa12_vestlight_plr.ogg",
		}
})
-- Sound: 3
sound.Add({
	name = "mount_exit_top_dpapa12_vestlight_plr",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/mount/mount_exit_top_dpapa12_vestlight_plr.ogg",
		}
})
-- Sound: 5
sound.Add({
	name = "weap_dpapa12_dryfire_plr",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"weapons/weap_dryfire_smg.ogg",
		}
})
-- Sound: 9
sound.Add({
	name = "weap_dpapa12_fire_plr_lfe",
	channel = CHAN_WEAPON,
	level = 140,
	volume = 1,
	pitch = {100,100},
	sound =  "^weapons/dpapa12/iw8_weap_dpapa12_fire_plr_01.wav",
		
})
-- Sound: 14
sound.Add({
	name = "weap_dpapa12_sup_plr_lfe",
	channel = CHAN_WPNFOLEY + 7,
	level = 140,
	volume = 1,
	pitch = {100,100},
	sound = 
		"^weapons/dpapa12/weap_romeo870_sup_plr_01.wav",
		
})
-- Sound: 16
sound.Add({
	name = "weap_sh_dpapa12_ads_down",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_dpapa12/wfoly_sh_dpapa12_ads_down.ogg",
		}
})
-- Sound: 17
sound.Add({
	name = "weap_sh_dpapa12_ads_up",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_dpapa12/wfoly_sh_dpapa12_ads_up.ogg",
		}
})
-- Sound: 18
sound.Add({
	name = "wfoly_plr_sh_dpapa12_drop_01",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_dpapa12/wfoly_sh_dpapa12_drop.ogg",
		}
})
-- Sound: 19
sound.Add({
	name = "wfoly_plr_sh_dpapa12_drop_quick_01",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_dpapa12/wfoly_sh_dpapa12_drop_quick.ogg",
		}
})
-- Sound: 20
sound.Add({
	name = "wfoly_plr_sh_dpapa12_inspect_01",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_dpapa12/wfoly_sh_dpapa12_inspect_01.ogg",
		}
})
-- Sound: 21
sound.Add({
	name = "wfoly_plr_sh_dpapa12_inspect_02",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_dpapa12/wfoly_sh_dpapa12_inspect_02.ogg",
		}
})
-- Sound: 22
sound.Add({
	name = "wfoly_plr_sh_dpapa12_inspect_03",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_dpapa12/wfoly_sh_dpapa12_inspect_03.ogg",
		}
})
-- Sound: 23
sound.Add({
	name = "wfoly_plr_sh_dpapa12_inspect_04",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_dpapa12/wfoly_sh_dpapa12_inspect_04.ogg",
		}
})
-- Sound: 24
sound.Add({
	name = "wfoly_plr_sh_dpapa12_inspect_05",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_dpapa12/wfoly_sh_dpapa12_inspect_05.ogg",
		}
})
-- Sound: 25
sound.Add({
	name = "wfoly_plr_sh_dpapa12_raise_01",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_dpapa12/wfoly_sh_dpapa12_raise.ogg",
		}
})
-- Sound: 26
sound.Add({
	name = "wfoly_plr_sh_dpapa12_raise_quick_01",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_dpapa12/wfoly_sh_dpapa12_raise_quick.ogg",
		}
})
-- Sound: 27
sound.Add({
	name = "wfoly_plr_sh_dpapa12_rechamber_01",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		" ",
		}
})
-- Sound: 28
sound.Add({
	name = "wfoly_plr_sh_dpapa12_rechamber_02",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_dpapa12/wfoly_sh_dpapa12_rechamber_chamber_v3_02a.ogg",
		"reloads/iw8_dpapa12/wfoly_sh_dpapa12_rechamber_chamber_v3_02b.ogg",
		"reloads/iw8_dpapa12/wfoly_sh_dpapa12_rechamber_chamber_v3_02c.ogg",
		}
})
-- Sound: 29
sound.Add({
	name = "wfoly_plr_sh_dpapa12_rechamber_025",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_dpapa12/wfoly_sh_dpapa12_rechamber_chamber_v3_01a.ogg",
		"reloads/iw8_dpapa12/wfoly_sh_dpapa12_rechamber_chamber_v3_01b.ogg",
		"reloads/iw8_dpapa12/wfoly_sh_dpapa12_rechamber_chamber_v3_01c.ogg",
		}
})
-- Sound: 30
sound.Add({
	name = "wfoly_plr_sh_dpapa12_reload_empty_end_01",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_dpapa12/wfoly_sh_dpapa12_reload_empty_end_rotate.ogg",
		}
})
sound.Add({
	name = "wfoly_plr_sh_dpapa12_reload_empty_end_02",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_dpapa12/wfoly_sh_dpapa12_reload_empty_end_chamber_01_02.ogg",
		"reloads/iw8_dpapa12/wfoly_sh_dpapa12_reload_empty_end_chamber_01_03.ogg",
		"reloads/iw8_dpapa12/wfoly_sh_dpapa12_reload_empty_end_chamber_01_04.ogg",
		}
})
-- Sound: 32
sound.Add({
	name = "wfoly_plr_sh_dpapa12_reload_empty_end_fast_01",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_dpapa12/wfoly_sh_dpapa12_reload_empty_fast_load_01.ogg",
		}
})
-- Sound: 33
sound.Add({
	name = "wfoly_plr_sh_dpapa12_reload_empty_end_fast_02",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_dpapa12/wfoly_sh_dpapa12_reload_empty_fast_rotate.ogg",
		}
})
-- Sound: 34
sound.Add({
	name = "wfoly_plr_sh_dpapa12_reload_empty_end_fast_03",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_dpapa12/wfoly_sh_dpapa12_reload_empty_fast_chamber_01_01.ogg",
		"reloads/iw8_dpapa12/wfoly_sh_dpapa12_reload_empty_fast_chamber_01_02.ogg",
		"reloads/iw8_dpapa12/wfoly_sh_dpapa12_reload_empty_fast_chamber_01_03.ogg",
		}
})
-- Sound: 35
sound.Add({
	name = "wfoly_plr_sh_dpapa12_reload_empty_end_fast_04",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_dpapa12/wfoly_sh_dpapa12_reload_empty_fast_end.ogg",
		}
})
-- Sound: 36
sound.Add({
	name = "wfoly_plr_sh_dpapa12_reload_end_01",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_dpapa12/wfoly_sh_dpapa12_reload_end_load_01.ogg",
		}
})
-- Sound: 37
sound.Add({
	name = "wfoly_plr_sh_dpapa12_reload_end_02",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_dpapa12/wfoly_sh_dpapa12_reload_end_rotate.ogg",
		}
})
-- Sound: 38
sound.Add({
	name = "wfoly_plr_sh_dpapa12_reload_end_fast_01",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_dpapa12/wfoly_sh_dpapa12_reload_end_fast_load_01.ogg",
		}
})
-- Sound: 39
sound.Add({
	name = "wfoly_plr_sh_dpapa12_reload_end_fast_02",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_dpapa12/wfoly_sh_dpapa12_reload_end_fast_rotate.ogg",
		}
})
-- Sound: 40
sound.Add({
	name = "wfoly_plr_sh_dpapa12_reload_end_fast_03",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_dpapa12/wfoly_sh_dpapa12_reload_end_fast_end.ogg",
		}
})
-- Sound: 41
sound.Add({
	name = "wfoly_plr_sh_dpapa12_reload_loop_01",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_dpapa12/wfoly_sh_dpapa12_reload_loop_cloth.ogg",
		}
})
-- Sound: 42
sound.Add({
	name = "wfoly_plr_sh_dpapa12_reload_loop_02",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_dpapa12/wfoly_sh_dpapa12_reload_loop_fast_load_01.ogg",
		"reloads/iw8_dpapa12/wfoly_sh_dpapa12_reload_loop_fast_load_02.ogg",
		"reloads/iw8_dpapa12/wfoly_sh_dpapa12_reload_loop_fast_load_03.ogg",
		}
})
-- Sound: 43
sound.Add({
	name = "wfoly_plr_sh_dpapa12_reload_loop_03",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_dpapa12/wfoly_sh_dpapa12_reload_loop_fast_clothpush.ogg",
		}
})
-- Sound: 44
sound.Add({
	name = "wfoly_plr_sh_dpapa12_reload_loop_04",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_dpapa12/wfoly_sh_dpapa12_reload_loop_fast_load_04.ogg",
		"reloads/iw8_dpapa12/wfoly_sh_dpapa12_reload_loop_fast_load_01.ogg",
		"reloads/iw8_dpapa12/wfoly_sh_dpapa12_reload_loop_fast_load_02.ogg",
		}
})
-- Sound: 45
sound.Add({
	name = "wfoly_plr_sh_dpapa12_reload_loop_fast_01",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_dpapa12/wfoly_sh_dpapa12_reload_loop_fast_load_01.ogg",
		"reloads/iw8_dpapa12/wfoly_sh_dpapa12_reload_loop_fast_load_03.ogg",
		}
})
-- Sound: 46
sound.Add({
	name = "wfoly_plr_sh_dpapa12_reload_loop_fast_02",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_dpapa12/wfoly_sh_dpapa12_reload_loop_fast_cloth.ogg",
		}
})
-- Sound: 47
sound.Add({
	name = "wfoly_plr_sh_dpapa12_reload_loop_fast_03",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_dpapa12/wfoly_sh_dpapa12_reload_loop_fast_load_02.ogg",
		"reloads/iw8_dpapa12/wfoly_sh_dpapa12_reload_loop_fast_load_04.ogg",
		}
})
-- Sound: 48
sound.Add({
	name = "wfoly_plr_sh_dpapa12_reload_loop_fast_04",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_dpapa12/wfoly_sh_dpapa12_reload_loop_fast_clothpush.ogg",
		}
})
-- Sound: 49
sound.Add({
	name = "wfoly_plr_sh_dpapa12_reload_start_01",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_dpapa12/wfoly_sh_dpapa12_reload_start_rotate.ogg",
		}
})
-- Sound: 50
sound.Add({
	name = "wfoly_plr_sh_dpapa12_reload_start_02",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_dpapa12/wfoly_sh_dpapa12_reload_start_load_01.ogg",
		"reloads/iw8_dpapa12/wfoly_sh_dpapa12_reload_start_load_02.ogg",
		}
})
-- Sound: 51
sound.Add({
	name = "wfoly_plr_sh_dpapa12_reload_start_03",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_dpapa12/wfoly_sh_dpapa12_reload_start_load_03.ogg",
		"reloads/iw8_dpapa12/wfoly_sh_dpapa12_reload_start_load_04.ogg",
		}
})
-- Sound: 52
sound.Add({
	name = "wfoly_plr_sh_dpapa12_reload_start_fast_01",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_dpapa12/wfoly_sh_dpapa12_reload_start_fast_rotate.ogg",
		}
})
-- Sound: 53
sound.Add({
	name = "wfoly_plr_sh_dpapa12_reload_start_fast_02",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_dpapa12/wfoly_sh_dpapa12_reload_start_fast_load_01.ogg",
		}
})
-- Sound: 54
sound.Add({
	name = "wfoly_plr_sh_dpapa12_reload_start_fast_03",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_dpapa12/wfoly_sh_dpapa12_reload_start_fast_load_02.ogg",
		"reloads/iw8_dpapa12/wfoly_sh_dpapa12_reload_start_fast_load_03.ogg",
		}
})
