-- Generated by GmodSoundGen

-- File: D:\Downloads\important_stuff_v2\Tools\GmodSoundGen_0519\weapon_sm_beta.all.lua
-- Total length: 88
sound.Add({
    name =           "wfoly_plr_sm_beta_raise_first_01",
    channel =        CHAN_WPNFOLEY +1,
    volume =         1,
    sound = {"reloads/iw8_beta/wfoly_plr_sm_beta_raise_first_start.ogg"}              
})
sound.Add({
    name =           "wfoly_plr_sm_beta_raise_first_02",
    channel =        CHAN_WPNFOLEY +2,
    volume =         1,
    sound = {"reloads/iw8_beta/wfoly_plr_sm_beta_raise_first_charge.ogg"}              
})
sound.Add({
    name =           "wfoly_plr_sm_beta_raise_first_03",
    channel =        CHAN_WPNFOLEY +3,
    volume =         1,
    sound = {"reloads/iw8_beta/wfoly_plr_sm_beta_raise_first_end.ogg"}              
})
sound.Add({
	name = "weap_beta_disconnector_plr",
	channel = CHAN_WPNFOLEY + 1,

	volume = 1,
	pitch = {100,100},
	sound = {
		"weapons/beta/weap_beta_disconnector_plr_01.ogg",
		}
})
-- Sound: 23
sound.Add({
	name = "weap_beta_fire_first_plr",
	channel = CHAN_WPNFOLEY + 2,

	volume = 1,
	pitch = {100,100},
	sound = {
		"weapons/beta/weap_beta_fire_first_plr_01.ogg",
		}
})
-- Sound: 9
sound.Add({
	name = "weap_beta_fire_plr_lfe",
	channel = CHAN_WEAPON +1,
	level = 140,
	volume = 1,
	pitch = {80,110},
	sound = 
		"^weapons/beta/weap_beta_fire_plr_01.wav",
		
})
-- Sound: 13
sound.Add({
	name = "weap_beta_sup_fire_plr_lfe",
	channel = CHAN_WEAPON,
	volume = 1,
	pitch = {80,110},
	sound = {
		"weapons/beta/weap_beta_sup_fire_plr_01.ogg",
		}
})
-- Sound: 16
sound.Add({
	name = "weap_sm_beta_ads_down",
	channel = CHAN_WPNFOLEY + 7,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/weap_sm_beta_ads_down.ogg",
		}
})
-- Sound: 17
sound.Add({
	name = "weap_sm_beta_ads_up",
	channel = CHAN_WPNFOLEY + 8,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/weap_sm_beta_ads_up.ogg",
		}
})
-- Sound: 18
sound.Add({
	name = "weap_sm_beta_selector_off",
	channel = CHAN_WPNFOLEY + 9,

	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/selector/weap_sm_beta_selector_off.ogg",
		}
})
-- Sound: 19
sound.Add({
	name = "weap_sm_beta_selector_on",
	channel = CHAN_WPNFOLEY + 10,

	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/selector/weap_sm_beta_selector_on.ogg",
		}
})
-- Sound: 20
sound.Add({
	name = "wfoly_plr_sm_beta_drop_01",
	channel = CHAN_WPNFOLEY + 1,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_plr_sm_beta_drop_down.ogg",
		}
})
-- Sound: 21
sound.Add({
	name = "wfoly_plr_sm_beta_drop_quick_01",
	channel = CHAN_WPNFOLEY + 2,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_plr_sm_beta_drop_quick_down.ogg",
		}
})
-- Sound: 22
sound.Add({
	name = "wfoly_plr_sm_beta_hybrid_scope_side_off",
	channel = CHAN_WPNFOLEY + 3,

	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/hybrid_scope/wfoly_plr_sm_beta_hybrid_side_out.ogg",
		}
})
-- Sound: 23
sound.Add({
	name = "wfoly_plr_sm_beta_hybrid_scope_side_on",
	channel = CHAN_WPNFOLEY + 4,

	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/hybrid_scope/wfoly_plr_sm_beta_hybrid_side_in.ogg",
		}
})
-- Sound: 24
sound.Add({
	name = "wfoly_plr_sm_beta_hybrid_scope_snap_closed",
	channel = CHAN_WPNFOLEY + 5,

	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/hybrid_scope/wfoly_plr_ar_falpha_hybrid_scope_snap_closed.ogg",
		}
})
-- Sound: 25
sound.Add({
	name = "wfoly_plr_sm_beta_hybrid_scope_snap_open",
	channel = CHAN_WPNFOLEY + 6,

	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/hybrid_scope/wfoly_plr_ar_falpha_hybrid_scope_snap_open.ogg",
		}
})
-- Sound: 26
sound.Add({
	name = "wfoly_plr_sm_beta_hybrid_scope_top_in",
	channel = CHAN_WPNFOLEY + 7,

	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/hybrid_scope/wfoly_plr_sm_beta_hybrid_top_in.ogg",
		}
})
-- Sound: 27
sound.Add({
	name = "wfoly_plr_sm_beta_hybrid_scope_top_out",
	channel = CHAN_WPNFOLEY + 8,

	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/hybrid_scope/wfoly_plr_sm_beta_hybrid_top_out.ogg",
		}
})
-- Sound: 28
sound.Add({
	name = "wfoly_plr_sm_beta_inspect_01",
	channel = CHAN_WPNFOLEY + 9,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_sm_beta_inspect_01.ogg",
		}
})
-- Sound: 29
sound.Add({
	name = "wfoly_plr_sm_beta_inspect_02",
	channel = CHAN_WPNFOLEY + 10,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_sm_beta_inspect_02.ogg",
		}
})
-- Sound: 30
sound.Add({
	name = "wfoly_plr_sm_beta_inspect_03",
	channel = CHAN_WPNFOLEY + 1,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_sm_beta_inspect_03.ogg",
		}
})
-- Sound: 31
sound.Add({
	name = "wfoly_plr_sm_beta_inspect_04",
	channel = CHAN_WPNFOLEY + 2,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_sm_beta_inspect_04.ogg",
		}
})
-- Sound: 32
sound.Add({
	name = "wfoly_plr_sm_beta_inspect_05",
	channel = CHAN_WPNFOLEY + 3,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_sm_beta_inspect_05.ogg",
		}
})
-- Sound: 33
sound.Add({
	name = "wfoly_plr_sm_beta_raise_01",
	channel = CHAN_WPNFOLEY + 4,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_plr_sm_beta_raise_up.ogg",
		}
})
-- Sound: 34
sound.Add({
	name = "wfoly_plr_sm_beta_raise_quick_01",
	channel = CHAN_WPNFOLEY + 5,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_plr_sm_beta_raise_quick_up.ogg",
		}
})
-- Sound: 35
sound.Add({
	name = "wfoly_plr_sm_beta_reload_01",
	channel = CHAN_WPNFOLEY + 6,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_plr_sm_beta_reload_start.ogg",
		}
})
-- Sound: 36
sound.Add({
	name = "wfoly_plr_sm_beta_reload_02",
	channel = CHAN_WPNFOLEY + 7,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_plr_sm_beta_reload_magout_01.ogg",
		}
})
-- Sound: 37
sound.Add({
	name = "wfoly_plr_sm_beta_reload_03",
	channel = CHAN_WPNFOLEY + 8,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_plr_sm_beta_reload_rotate.ogg",
		}
})
-- Sound: 38
sound.Add({
	name = "wfoly_plr_sm_beta_reload_04",
	channel = CHAN_WPNFOLEY + 9,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_plr_sm_beta_reload_magin_v2_01.ogg",
		}
})
-- Sound: 39
sound.Add({
	name = "wfoly_plr_sm_beta_reload_045",
	channel = CHAN_WPNFOLEY + 10,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_plr_sm_beta_reload_magin_v2_02.ogg",
		}
})
-- Sound: 40
sound.Add({
	name = "wfoly_plr_sm_beta_reload_05",
	channel = CHAN_WPNFOLEY + 1,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_plr_sm_beta_reload_end.ogg",
		}
})
-- Sound: 41
sound.Add({
	name = "wfoly_plr_sm_beta_reload_empty_01",
	channel = CHAN_WPNFOLEY + 2,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_plr_sm_beta_reload_empty_start.ogg",
		}
})
-- Sound: 42
sound.Add({
	name = "wfoly_plr_sm_beta_reload_empty_02",
	channel = CHAN_WPNFOLEY + 3,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_plr_sm_beta_reload_empty_magout_01.ogg",
		}
})
-- Sound: 43
sound.Add({
	name = "wfoly_plr_sm_beta_reload_empty_03",
	channel = CHAN_WPNFOLEY + 4,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_plr_sm_beta_reload_empty_rotate.ogg",
		}
})
-- Sound: 44
sound.Add({
	name = "wfoly_plr_sm_beta_reload_empty_04",
	channel = CHAN_WPNFOLEY + 5,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_plr_sm_beta_reload_empty_magin_v2_01.ogg",
		}
})
-- Sound: 45
sound.Add({
	name = "wfoly_plr_sm_beta_reload_empty_045",
	channel = CHAN_WPNFOLEY + 6,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_plr_sm_beta_reload_empty_magin_v2_02.ogg",
		}
})
-- Sound: 46
sound.Add({
	name = "wfoly_plr_sm_beta_reload_empty_05",
	channel = CHAN_WPNFOLEY + 7,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_plr_sm_beta_reload_empty_charge_01.ogg",
		}
})
-- Sound: 47
sound.Add({
	name = "wfoly_plr_sm_beta_reload_empty_06",
	channel = CHAN_WPNFOLEY + 8,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_plr_sm_beta_reload_empty_end.ogg",
		}
})
-- Sound: 48
sound.Add({
	name = "wfoly_plr_sm_beta_reload_empty_fast_01",
	channel = CHAN_WPNFOLEY + 9,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_plr_sm_beta_reload_empty_fast_start.ogg",
		}
})
-- Sound: 49
sound.Add({
	name = "wfoly_plr_sm_beta_reload_empty_fast_02",
	channel = CHAN_WPNFOLEY + 10,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_plr_sm_beta_reload_empty_fast_magout_01.ogg",
		}
})
-- Sound: 50
sound.Add({
	name = "wfoly_plr_sm_beta_reload_empty_fast_03",
	channel = CHAN_WPNFOLEY + 1,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_plr_sm_beta_reload_empty_fast_rotate.ogg",
		}
})
-- Sound: 51
sound.Add({
	name = "wfoly_plr_sm_beta_reload_empty_fast_04",
	channel = CHAN_WPNFOLEY + 2,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_plr_sm_beta_reload_empty_fast_magin_v2_01.ogg",
		}
})
-- Sound: 52
sound.Add({
	name = "wfoly_plr_sm_beta_reload_empty_fast_045",
	channel = CHAN_WPNFOLEY + 3,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_plr_sm_beta_reload_empty_fast_magin_v2_02.ogg",
		}
})
-- Sound: 53
sound.Add({
	name = "wfoly_plr_sm_beta_reload_empty_fast_05",
	channel = CHAN_WPNFOLEY + 4,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_plr_sm_beta_reload_empty_fast_charge_01.ogg",
		}
})
-- Sound: 54
sound.Add({
	name = "wfoly_plr_sm_beta_reload_empty_fast_06",
	channel = CHAN_WPNFOLEY + 5,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_plr_sm_beta_reload_empty_fast_end.ogg",
		}
})
-- Sound: 55
sound.Add({
	name = "wfoly_plr_sm_beta_reload_empty_fast_xmag_01",
	channel = CHAN_WPNFOLEY + 6,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_plr_sm_beta_reload_empty_fast_xmag_start.ogg",
		}
})
-- Sound: 56
sound.Add({
	name = "wfoly_plr_sm_beta_reload_empty_fast_xmag_02",
	channel = CHAN_WPNFOLEY + 7,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_plr_sm_beta_reload_empty_fast_xmag_magout_01.ogg",
		}
})
-- Sound: 57
sound.Add({
	name = "wfoly_plr_sm_beta_reload_empty_fast_xmag_03",
	channel = CHAN_WPNFOLEY + 8,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_plr_sm_beta_reload_empty_fast_xmag_rotate.ogg",
		}
})
-- Sound: 58
sound.Add({
	name = "wfoly_plr_sm_beta_reload_empty_fast_xmag_04",
	channel = CHAN_WPNFOLEY + 9,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_plr_sm_beta_reload_empty_fast_xmag_magin_v2_01.ogg",
		}
})
-- Sound: 59
sound.Add({
	name = "wfoly_plr_sm_beta_reload_empty_fast_xmag_045",
	channel = CHAN_WPNFOLEY + 10,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_plr_sm_beta_reload_empty_fast_xmag_magin_v2_02.ogg",
		}
})
-- Sound: 60
sound.Add({
	name = "wfoly_plr_sm_beta_reload_empty_fast_xmag_05",
	channel = CHAN_WPNFOLEY + 1,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_plr_sm_beta_reload_empty_fast_xmag_charge_01.ogg",
		}
})
-- Sound: 61
sound.Add({
	name = "wfoly_plr_sm_beta_reload_empty_fast_xmag_06",
	channel = CHAN_WPNFOLEY + 2,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_plr_sm_beta_reload_empty_fast_xmag_end.ogg",
		}
})
-- Sound: 62
sound.Add({
	name = "wfoly_plr_sm_beta_reload_empty_xmag_01",
	channel = CHAN_WPNFOLEY + 3,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_plr_sm_beta_reload_empty_xmag_start.ogg",
		}
})
-- Sound: 63
sound.Add({
	name = "wfoly_plr_sm_beta_reload_empty_xmag_02",
	channel = CHAN_WPNFOLEY + 4,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_plr_sm_beta_reload_empty_xmag_magout_01.ogg",
		}
})
-- Sound: 64
sound.Add({
	name = "wfoly_plr_sm_beta_reload_empty_xmag_03",
	channel = CHAN_WPNFOLEY + 5,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_plr_sm_beta_reload_empty_xmag_rotate.ogg",
		}
})
-- Sound: 65
sound.Add({
	name = "wfoly_plr_sm_beta_reload_empty_xmag_04",
	channel = CHAN_WPNFOLEY + 6,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_plr_sm_beta_reload_empty_xmag_magin_v2_01.ogg",
		}
})
-- Sound: 66
sound.Add({
	name = "wfoly_plr_sm_beta_reload_empty_xmag_045",
	channel = CHAN_WPNFOLEY + 7,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_plr_sm_beta_reload_empty_xmag_magin_v2_02.ogg",
		}
})
-- Sound: 67
sound.Add({
	name = "wfoly_plr_sm_beta_reload_empty_xmag_05",
	channel = CHAN_WPNFOLEY + 8,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_plr_sm_beta_reload_empty_xmag_charge_01.ogg",
		}
})
-- Sound: 68
sound.Add({
	name = "wfoly_plr_sm_beta_reload_empty_xmag_06",
	channel = CHAN_WPNFOLEY + 9,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_plr_sm_beta_reload_empty_xmag_end.ogg",
		}
})
-- Sound: 69
sound.Add({
	name = "wfoly_plr_sm_beta_reload_fast_01",
	channel = CHAN_WPNFOLEY + 10,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_plr_sm_beta_reload_fast_start.ogg",
		}
})
-- Sound: 70
sound.Add({
	name = "wfoly_plr_sm_beta_reload_fast_02",
	channel = CHAN_WPNFOLEY + 1,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_plr_sm_beta_reload_fast_magout_01.ogg",
		}
})
-- Sound: 71
sound.Add({
	name = "wfoly_plr_sm_beta_reload_fast_03",
	channel = CHAN_WPNFOLEY + 2,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_plr_sm_beta_reload_fast_rotate.ogg",
		}
})
-- Sound: 72
sound.Add({
	name = "wfoly_plr_sm_beta_reload_fast_04",
	channel = CHAN_WPNFOLEY + 3,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_plr_sm_beta_reload_fast_magin_v2_01.ogg",
		}
})
-- Sound: 73
sound.Add({
	name = "wfoly_plr_sm_beta_reload_fast_045",
	channel = CHAN_WPNFOLEY + 4,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_plr_sm_beta_reload_fast_magin_v2_02.ogg",
		}
})
-- Sound: 74
sound.Add({
	name = "wfoly_plr_sm_beta_reload_fast_05",
	channel = CHAN_WPNFOLEY + 5,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_plr_sm_beta_reload_fast_end.ogg",
		}
})
-- Sound: 75
sound.Add({
	name = "wfoly_plr_sm_beta_reload_fast_xmag_01",
	channel = CHAN_WPNFOLEY + 6,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_plr_sm_beta_reload_fast_xmag_start.ogg",
		}
})
-- Sound: 76
sound.Add({
	name = "wfoly_plr_sm_beta_reload_fast_xmag_02",
	channel = CHAN_WPNFOLEY + 7,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_plr_sm_beta_reload_fast_xmag_magout_01.ogg",
		}
})
-- Sound: 77
sound.Add({
	name = "wfoly_plr_sm_beta_reload_fast_xmag_03",
	channel = CHAN_WPNFOLEY + 8,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_plr_sm_beta_reload_fast_xmag_rotate.ogg",
		}
})
-- Sound: 78
sound.Add({
	name = "wfoly_plr_sm_beta_reload_fast_xmag_04",
	channel = CHAN_WPNFOLEY + 9,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_plr_sm_beta_reload_fast_xmag_magin_v2_01.ogg",
		}
})
-- Sound: 79
sound.Add({
	name = "wfoly_plr_sm_beta_reload_fast_xmag_045",
	channel = CHAN_WPNFOLEY + 10,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_plr_sm_beta_reload_fast_xmag_magin_v2_02.ogg",
		}
})
-- Sound: 80
sound.Add({
	name = "wfoly_plr_sm_beta_reload_fast_xmag_05",
	channel = CHAN_WPNFOLEY + 1,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_plr_sm_beta_reload_end.ogg",
		}
})
-- Sound: 81
sound.Add({
	name = "wfoly_plr_sm_beta_reload_xmag_01",
	channel = CHAN_WPNFOLEY + 2,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_plr_sm_beta_reload_xmag_start.ogg",
		}
})
-- Sound: 82
sound.Add({
	name = "wfoly_plr_sm_beta_reload_xmag_02",
	channel = CHAN_WPNFOLEY + 3,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_plr_sm_beta_reload_xmag_magout_01.ogg",
		}
})
-- Sound: 83
sound.Add({
	name = "wfoly_plr_sm_beta_reload_xmag_03",
	channel = CHAN_WPNFOLEY + 4,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_plr_sm_beta_reload_xmag_arm.ogg",
		}
})
-- Sound: 84
sound.Add({
	name = "wfoly_plr_sm_beta_reload_xmag_04",
	channel = CHAN_WPNFOLEY + 5,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_plr_sm_beta_reload_xmag_rotate.ogg",
		}
})
-- Sound: 85
sound.Add({
	name = "wfoly_plr_sm_beta_reload_xmag_05",
	channel = CHAN_WPNFOLEY + 6,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_plr_sm_beta_reload_xmag_magin_v2_01.ogg",
		}
})
-- Sound: 86
sound.Add({
	name = "wfoly_plr_sm_beta_reload_xmag_055",
	channel = CHAN_WPNFOLEY + 7,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_plr_sm_beta_reload_xmag_magin_v2_02.ogg",
		}
})
-- Sound: 87
sound.Add({
	name = "wfoly_plr_sm_beta_reload_xmag_06",
	channel = CHAN_WPNFOLEY + 8,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_beta/wfoly_plr_sm_beta_reload_xmag_end.ogg",
		}
})
