-- Generated by GmodSoundGen

-- File: D:\Downloads\important_stuff_v2\Tools\GmodSoundGen_0519\weapon_sm_victor.all.lua
-- Total length: 127

sound.Add({
    name =           "wfoly_plr_sm_victor_raise_first_01",
    channel =        CHAN_WPNFOLEY +1,
    volume =         1,
    sound = {"reloads/iw8_victor/wfoly_sm_victor_raise_first_up.ogg"}              
})
sound.Add({
    name =           "wfoly_plr_sm_victor_raise_first_02",
    channel =        CHAN_WPNFOLEY +2,
    volume =         1,
    sound = {"reloads/iw8_victor/wfoly_sm_victor_raise_first_charge.ogg"}              
})
sound.Add({
    name =           "wfoly_plr_sm_victor_raise_first_03",
    channel =        CHAN_WPNFOLEY +3,
    volume =         1,
    sound = {"reloads/iw8_victor/wfoly_sm_victor_raise_first_end.ogg"}              
})


-- Sound: 4
sound.Add({
	name = "weap_sm_victor_ads_down",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"weapons/victor/weap_sm_uzulu_ads_down.ogg",
		}
})
-- Sound: 5
sound.Add({
	name = "weap_sm_victor_ads_up",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"weapons/victor/weap_sm_uzulu_ads_up.ogg",
		}
})
-- Sound: 14
sound.Add({
	name = "weap_victor_fire_plr",
	channel = CHAN_WEAPON,
	level = 140,
	volume = 1,
	pitch = {80,110},
	sound = 
		"^weapons/victor/weap_victor_fire_plr_01.wav",
		
})
-- Sound: 17
sound.Add({
	name = "weap_victor_sup_fire_plr",
	channel = CHAN_WEAPON,
	volume = 1,
	pitch = {80,110},
	sound = {
		"weapons/victor/weap_victor_sup_fire_plr_01.ogg",
		}
})
sound.Add({
    name =           "weap_victor_fire_first_plr",
    channel =        CHAN_WPNFOLEY +20,
    volume =         1,
    sound = {"weapons/victor/weap_mpapa7_fire_first_plr_01.ogg"}              
})        
sound.Add({
    name =           "weap_victor_disconnector_plr",
    channel =        CHAN_WPNFOLEY +21,
    volume =         1,
    sound = {"weapons/victor/weap_victor_disconnector_plr_01.ogg"}              
})
-- Sound: 24
sound.Add({
	name = "wfoly_plr_sm_victor_drop_01",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_drop.ogg",
		}
})
-- Sound: 25
sound.Add({
	name = "wfoly_plr_sm_victor_drop_quick_01",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_drop_quick.ogg",
		}
})
-- Sound: 26
sound.Add({
	name = "wfoly_plr_sm_victor_hybrid_scope_side_off",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/hybrid_scope/wfoly_plr_sm_uzulu_hybrid_scope_side_off.ogg",
		}
})
-- Sound: 27
sound.Add({
	name = "wfoly_plr_sm_victor_hybrid_scope_side_on",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/hybrid_scope/wfoly_plr_sm_uzulu_hybrid_scope_side_on.ogg",
		}
})
-- Sound: 28
sound.Add({
	name = "wfoly_plr_sm_victor_hybrid_scope_snap_closed",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/hybrid_scope/wfoly_plr_ar_falpha_hybrid_scope_snap_closed.ogg",
		}
})
-- Sound: 29
sound.Add({
	name = "wfoly_plr_sm_victor_hybrid_scope_snap_open",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/hybrid_scope/wfoly_plr_ar_falpha_hybrid_scope_snap_open.ogg",
		}
})
-- Sound: 30
sound.Add({
	name = "wfoly_plr_sm_victor_hybrid_scope_top_in",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/hybrid_scope/wfoly_plr_sm_uzulu_hybrid_scope_top_in.ogg",
		}
})
-- Sound: 31
sound.Add({
	name = "wfoly_plr_sm_victor_hybrid_scope_top_out",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/hybrid_scope/wfoly_plr_sm_uzulu_hybrid_scope_top_out.ogg",
		}
})
-- Sound: 32
sound.Add({
	name = "wfoly_plr_sm_victor_inspect_01",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_plr_sm_victor_inspect_01.ogg",
		}
})
-- Sound: 33
sound.Add({
	name = "wfoly_plr_sm_victor_inspect_02",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_plr_sm_victor_inspect_02.ogg",
		}
})
-- Sound: 34
sound.Add({
	name = "wfoly_plr_sm_victor_inspect_03",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_plr_sm_victor_inspect_03.ogg",
		}
})
-- Sound: 35
sound.Add({
	name = "wfoly_plr_sm_victor_inspect_04",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_plr_sm_victor_inspect_04.ogg",
		}
})
-- Sound: 36
sound.Add({
	name = "wfoly_plr_sm_victor_inspect_05",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_plr_sm_victor_inspect_05.ogg",
		}
})
-- Sound: 37
sound.Add({
	name = "wfoly_plr_sm_victor_raise_01",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_raise.ogg",
		}
})
-- Sound: 38
sound.Add({
	name = "wfoly_plr_sm_victor_raise_quick_01",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_raise_quick.ogg",
		}
})
-- Sound: 39
sound.Add({
	name = "wfoly_plr_sm_victor_reload_01",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_up.ogg",
		}
})
-- Sound: 40
sound.Add({
	name = "wfoly_plr_sm_victor_reload_02",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_mag_release.ogg",
		}
})
-- Sound: 41
sound.Add({
	name = "wfoly_plr_sm_victor_reload_03",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_magout.ogg",
		}
})
-- Sound: 42
sound.Add({
	name = "wfoly_plr_sm_victor_reload_04",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_arm.ogg",
		}
})
-- Sound: 43
sound.Add({
	name = "wfoly_plr_sm_victor_reload_05",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_maghit.ogg",
		}
})
-- Sound: 44
sound.Add({
	name = "wfoly_plr_sm_victor_reload_06",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_magin.ogg",
		}
})
-- Sound: 45
sound.Add({
	name = "wfoly_plr_sm_victor_reload_07",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_end.ogg",
		}
})
-- Sound: 46
sound.Add({
	name = "wfoly_plr_sm_victor_reload_drum_01",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_drum_up.ogg",
		}
})
-- Sound: 47
sound.Add({
	name = "wfoly_plr_sm_victor_reload_drum_02",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_drum_magrelease.ogg",
		}
})
-- Sound: 48
sound.Add({
	name = "wfoly_plr_sm_victor_reload_drum_03",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_drum_drumout.ogg",
		}
})
-- Sound: 49
sound.Add({
	name = "wfoly_plr_sm_victor_reload_drum_04",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_drum_arm.ogg",
		}
})
-- Sound: 50
sound.Add({
	name = "wfoly_plr_sm_victor_reload_drum_05",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_drum_drumhit.ogg",
		}
})
-- Sound: 51
sound.Add({
	name = "wfoly_plr_sm_victor_reload_drum_06",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_drum_drumin.ogg",
		}
})
-- Sound: 52
sound.Add({
	name = "wfoly_plr_sm_victor_reload_drum_07",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_drum_end.ogg",
		}
})
-- Sound: 53
sound.Add({
	name = "wfoly_plr_sm_victor_reload_empty_01",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_empty_up.ogg",
		}
})
-- Sound: 54
sound.Add({
	name = "wfoly_plr_sm_victor_reload_empty_02",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_empty_magout.ogg",
		}
})
-- Sound: 55
sound.Add({
	name = "wfoly_plr_sm_victor_reload_empty_03",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_empty_arm.ogg",
		}
})
-- Sound: 56
sound.Add({
	name = "wfoly_plr_sm_victor_reload_empty_04",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_empty_rotate.ogg",
		}
})
-- Sound: 57
sound.Add({
	name = "wfoly_plr_sm_victor_reload_empty_05",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_empty_maghit.ogg",
		}
})
-- Sound: 58
sound.Add({
	name = "wfoly_plr_sm_victor_reload_empty_06",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_empty_magin_01.ogg",
		}
})
-- Sound: 59
sound.Add({
	name = "wfoly_plr_sm_victor_reload_empty_065",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_empty_magin_02.ogg",
		}
})
-- Sound: 60
sound.Add({
	name = "wfoly_plr_sm_victor_reload_empty_07",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_empty_charge.ogg",
		}
})
-- Sound: 61
sound.Add({
	name = "wfoly_plr_sm_victor_reload_empty_08",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_empty_end.ogg",
		}
})
-- Sound: 62
sound.Add({
	name = "wfoly_plr_sm_victor_reload_empty_drum_01",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_empty_drum_up.ogg",
		}
})
-- Sound: 63
sound.Add({
	name = "wfoly_plr_sm_victor_reload_empty_drum_02",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_empty_drum_drumout.ogg",
		}
})
-- Sound: 64
sound.Add({
	name = "wfoly_plr_sm_victor_reload_empty_drum_03",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_empty_drum_arm.ogg",
		}
})
-- Sound: 65
sound.Add({
	name = "wfoly_plr_sm_victor_reload_empty_drum_04",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_empty_drum_drumhit.ogg",
		}
})
-- Sound: 66
sound.Add({
	name = "wfoly_plr_sm_victor_reload_empty_drum_05",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_empty_drum_drumin.ogg",
		}
})
-- Sound: 67
sound.Add({
	name = "wfoly_plr_sm_victor_reload_empty_drum_06",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_empty_drum_charge.ogg",
		}
})
-- Sound: 68
sound.Add({
	name = "wfoly_plr_sm_victor_reload_empty_drum_07",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_empty_drum_end.ogg",
		}
})
-- Sound: 69
sound.Add({
	name = "wfoly_plr_sm_victor_reload_empty_fast_01",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_empty_fast_up.ogg",
		}
})
-- Sound: 70
sound.Add({
	name = "wfoly_plr_sm_victor_reload_empty_fast_02",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_empty_fast_magout.ogg",
		}
})
-- Sound: 71
sound.Add({
	name = "wfoly_plr_sm_victor_reload_empty_fast_03",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_empty_fast_arm.ogg",
		}
})
-- Sound: 72
sound.Add({
	name = "wfoly_plr_sm_victor_reload_empty_fast_04",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_empty_fast_maghit.ogg",
		}
})
-- Sound: 73
sound.Add({
	name = "wfoly_plr_sm_victor_reload_empty_fast_05",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_empty_fast_magin.ogg",
		}
})
-- Sound: 74
sound.Add({
	name = "wfoly_plr_sm_victor_reload_empty_fast_06",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_empty_fast_hit.ogg",
		}
})
-- Sound: 75
sound.Add({
	name = "wfoly_plr_sm_victor_reload_empty_fast_07",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_empty_fast_bolt.ogg",
		}
})
-- Sound: 76
sound.Add({
	name = "wfoly_plr_sm_victor_reload_empty_fast_08",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_empty_fast_end.ogg",
		}
})
-- Sound: 77
sound.Add({
	name = "wfoly_plr_sm_victor_reload_empty_fast_drum_01",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_empty_fast_drum_up.ogg",
		}
})
-- Sound: 78
sound.Add({
	name = "wfoly_plr_sm_victor_reload_empty_fast_drum_02",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_empty_fast_drum_drumout.ogg",
		}
})
-- Sound: 79
sound.Add({
	name = "wfoly_plr_sm_victor_reload_empty_fast_drum_03",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_empty_fast_drum_arm.ogg",
		}
})
-- Sound: 80
sound.Add({
	name = "wfoly_plr_sm_victor_reload_empty_fast_drum_04",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_empty_fast_drum_drumhit.ogg",
		}
})
-- Sound: 81
sound.Add({
	name = "wfoly_plr_sm_victor_reload_empty_fast_drum_05",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_empty_fast_drum_drumin.ogg",
		}
})
-- Sound: 82
sound.Add({
	name = "wfoly_plr_sm_victor_reload_empty_fast_drum_06",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_empty_fast_drum_hit.ogg",
		}
})
-- Sound: 83
sound.Add({
	name = "wfoly_plr_sm_victor_reload_empty_fast_drum_07",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_empty_fast_drum_charge.ogg",
		}
})
-- Sound: 84
sound.Add({
	name = "wfoly_plr_sm_victor_reload_empty_fast_drum_08",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_empty_fast_drum_end.ogg",
		}
})
-- Sound: 85
sound.Add({
	name = "wfoly_plr_sm_victor_reload_empty_fast_smag_01",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_empty_fast_smag_up.ogg",
		}
})
-- Sound: 86
sound.Add({
	name = "wfoly_plr_sm_victor_reload_empty_fast_smag_02",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_empty_fast_smag_magout.ogg",
		}
})
-- Sound: 87
sound.Add({
	name = "wfoly_plr_sm_victor_reload_empty_fast_smag_03",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_empty_fast_smag_arm.ogg",
		}
})
-- Sound: 88
sound.Add({
	name = "wfoly_plr_sm_victor_reload_empty_fast_smag_04",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_empty_fast_smag_maghit.ogg",
		}
})
-- Sound: 89
sound.Add({
	name = "wfoly_plr_sm_victor_reload_empty_fast_smag_05",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_empty_fast_smag_magin.ogg",
		}
})
-- Sound: 90
sound.Add({
	name = "wfoly_plr_sm_victor_reload_empty_fast_smag_06",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_empty_fast_smag_hit.ogg",
		}
})
-- Sound: 91
sound.Add({
	name = "wfoly_plr_sm_victor_reload_empty_fast_smag_07",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_empty_fast_smag_charge.ogg",
		}
})
-- Sound: 92
sound.Add({
	name = "wfoly_plr_sm_victor_reload_empty_fast_smag_08",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_empty_fast_smag_end.ogg",
		}
})
-- Sound: 93
sound.Add({
	name = "wfoly_plr_sm_victor_reload_empty_smag_01",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_empty_smag_up.ogg",
		}
})
-- Sound: 94
sound.Add({
	name = "wfoly_plr_sm_victor_reload_empty_smag_02",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_empty_smag_magout.ogg",
		}
})
-- Sound: 95
sound.Add({
	name = "wfoly_plr_sm_victor_reload_empty_smag_03",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_empty_smag_arm.ogg",
		}
})
-- Sound: 96
sound.Add({
	name = "wfoly_plr_sm_victor_reload_empty_smag_04",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_empty_smag_maghit.ogg",
		}
})
-- Sound: 97
sound.Add({
	name = "wfoly_plr_sm_victor_reload_empty_smag_05",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_empty_smag_magin.ogg",
		}
})
-- Sound: 98
sound.Add({
	name = "wfoly_plr_sm_victor_reload_empty_smag_06",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_empty_smag_charge.ogg",
		}
})
-- Sound: 99
sound.Add({
	name = "wfoly_plr_sm_victor_reload_empty_smag_07",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_empty_smag_end.ogg",
		}
})
-- Sound: 100
sound.Add({
	name = "wfoly_plr_sm_victor_reload_fast_01",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_fast_up.ogg",
		}
})
-- Sound: 101
sound.Add({
	name = "wfoly_plr_sm_victor_reload_fast_02",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_fast_magout.ogg",
		}
})
-- Sound: 102
sound.Add({
	name = "wfoly_plr_sm_victor_reload_fast_03",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_fast_arm.ogg",
		}
})
-- Sound: 103
sound.Add({
	name = "wfoly_plr_sm_victor_reload_fast_04",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_fast_maghit.ogg",
		}
})
-- Sound: 104
sound.Add({
	name = "wfoly_plr_sm_victor_reload_fast_05",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_fast_magin.ogg",
		}
})
-- Sound: 105
sound.Add({
	name = "wfoly_plr_sm_victor_reload_fast_06",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_fast_end.ogg",
		}
})
-- Sound: 106
sound.Add({
	name = "wfoly_plr_sm_victor_reload_fast_drum_01",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_fast_drum_up.ogg",
		}
})
-- Sound: 107
sound.Add({
	name = "wfoly_plr_sm_victor_reload_fast_drum_02",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_fast_drum_drumout.ogg",
		}
})
-- Sound: 108
sound.Add({
	name = "wfoly_plr_sm_victor_reload_fast_drum_03",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_fast_drum_arm.ogg",
		}
})
-- Sound: 109
sound.Add({
	name = "wfoly_plr_sm_victor_reload_fast_drum_04",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_fast_drum_drumhit.ogg",
		}
})
-- Sound: 110
sound.Add({
	name = "wfoly_plr_sm_victor_reload_fast_drum_05",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_fast_drum_drumin.ogg",
		}
})
-- Sound: 111
sound.Add({
	name = "wfoly_plr_sm_victor_reload_fast_drum_06",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_fast_drum_end.ogg",
		}
})
-- Sound: 112
sound.Add({
	name = "wfoly_plr_sm_victor_reload_fast_smag_01",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_fast_smag_up.ogg",
		}
})
-- Sound: 113
sound.Add({
	name = "wfoly_plr_sm_victor_reload_fast_smag_02",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_fast_smag_magout.ogg",
		}
})
-- Sound: 114
sound.Add({
	name = "wfoly_plr_sm_victor_reload_fast_smag_03",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_fast_smag_arm.ogg",
		}
})
-- Sound: 115
sound.Add({
	name = "wfoly_plr_sm_victor_reload_fast_smag_04",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_fast_smag_maghit.ogg",
		}
})
-- Sound: 116
sound.Add({
	name = "wfoly_plr_sm_victor_reload_fast_smag_05",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_fast_smag_magin.ogg",
		}
})
-- Sound: 117
sound.Add({
	name = "wfoly_plr_sm_victor_reload_fast_smag_06",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_fast_smag_end.ogg",
		}
})
-- Sound: 118
sound.Add({
	name = "wfoly_plr_sm_victor_reload_smag_01",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_smag_up.ogg",
		}
})
-- Sound: 119
sound.Add({
	name = "wfoly_plr_sm_victor_reload_smag_02",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_smag_magrelease.ogg",
		}
})
-- Sound: 120
sound.Add({
	name = "wfoly_plr_sm_victor_reload_smag_03",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_smag_magout.ogg",
		}
})
-- Sound: 121
sound.Add({
	name = "wfoly_plr_sm_victor_reload_smag_04",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_smag_arm.ogg",
		}
})
-- Sound: 122
sound.Add({
	name = "wfoly_plr_sm_victor_reload_smag_05",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_smag_maghit.ogg",
		}
})
-- Sound: 123
sound.Add({
	name = "wfoly_plr_sm_victor_reload_smag_06",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_smag_magin.ogg",
		}
})
-- Sound: 124
sound.Add({
	name = "wfoly_plr_sm_victor_reload_smag_07",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_victor/wfoly_sm_victor_reload_smag_end.ogg",
		}
})
-- Sound: 125
sound.Add({
	name = "wfoly_plr_sm_victor_selectsemi_switch_off_01",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/wfoly_sm_victor_selectsemi_switch_off.ogg",
		}
})
-- Sound: 126
sound.Add({
	name = "wfoly_plr_sm_victor_selectsemi_switch_on_01",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/wfoly_sm_victor_selectsemi_switch_on.ogg",
		}
})
