-- Generated by GmodSoundGen

-- File: D:\Downloads\important_stuff_v2\Tools\GmodSoundGen_0519\weapon_sh_oscar12.all.lua
-- Total length: 109
sound.Add({
    name =           "wfoly_plr_sh_oscar12_raise_first_01",
    channel =        CHAN_WPNFOLEY +1,
    volume =         1,
    sound = {"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_raise_first_start.ogg"}              
})
sound.Add({
    name =           "wfoly_plr_sh_oscar12_raise_first_02",
    channel =        CHAN_WPNFOLEY +2,
    volume =         1,
    sound = {"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_raise_first_magin_01.ogg"}              
})
sound.Add({
    name =           "wfoly_plr_sh_oscar12_raise_first_03",
    channel =        CHAN_WPNFOLEY +3,
    volume =         1,
    sound = {"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_raise_first_end_hit.ogg"}              
})
sound.Add({
    name =           "wfoly_plr_sh_oscar12_raise_first_04",
    channel =        CHAN_WPNFOLEY +4,
    volume =         1,
    sound = {"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_raise_first_end.ogg"}              
})
-- Sound: 0
sound.Add({
	name = "mount_enter_side_oscar12_vestlight_plr",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"foley/mount/mount_enter_side_oscar12_vestlight_plr.ogg",
		}
})

-- Sound: 12
sound.Add({
	name = "weap_oscar12_fire_plr",
	channel = CHAN_WEAPON,
	level = 140,
	volume = 1,
	pitch = {100,100},
	sound = 
		"^weapons/oscar12/weap_oscar12_fire_plr_01.wav",
		
})
sound.Add({
	name = "weap_oscar12_fire_plr_first",
	channel = CHAN_TRIGGER,
	volume = 1,
	pitch = {100,100},
	sound = {
		"weapons/oscar12/weap_oscar12_fire_first_plr_01.ogg",
		}
})
-- Sound: 20
sound.Add({
	name = "weap_oscar12_sup_plr",
	channel = CHAN_WEAPON,
	level = 140,
	volume = 1,
	pitch = {100,100},
	sound = 
		"^weapons/oscar12/weap_oscar12_sup_plr_01.wav",
		
})
-- Sound: 22
sound.Add({
	name = "weap_sh_oscar12_ads_down",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/weap_sh_oscar12_ads_down.ogg",
		}
})
-- Sound: 23
sound.Add({
	name = "weap_sh_oscar12_ads_up",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/weap_sh_oscar12_ads_up.ogg",
		}
})
sound.Add({
	name = "weap_sh_oscar12_ads_down",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/weap_sh_oscar12_ads_down.ogg",
		}
})
-- Sound: 24
sound.Add({
	name = "wfoly_plr_sh_oscar12_ads_down_01",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_ads_down_start.ogg",
		}
})
-- Sound: 25
sound.Add({
	name = "wfoly_plr_sh_oscar12_ads_down_02",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_ads_down_cloth.ogg",
		}
})
-- Sound: 26
sound.Add({
	name = "wfoly_plr_sh_oscar12_ads_down_nvg_01",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_ads_down_nvg_up.ogg",
		}
})
-- Sound: 27
sound.Add({
	name = "wfoly_plr_sh_oscar12_ads_down_nvg_02",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_ads_down_nvg_cloth.ogg",
		}
})
-- Sound: 28
sound.Add({
	name = "wfoly_plr_sh_oscar12_drop_01",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_drop_down.ogg",
		}
})
-- Sound: 29
sound.Add({
	name = "wfoly_plr_sh_oscar12_drop_quick_01",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_drop_quick_down.ogg",
		}
})
-- Sound: 30
sound.Add({
	name = "wfoly_plr_sh_oscar12_inspect_01",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_sh_oscar12_inspect_01.ogg",
		}
})
-- Sound: 31
sound.Add({
	name = "wfoly_plr_sh_oscar12_inspect_02",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_sh_oscar12_inspect_02.ogg",
		}
})
-- Sound: 32
sound.Add({
	name = "wfoly_plr_sh_oscar12_inspect_03",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_sh_oscar12_inspect_03.ogg",
		}
})
-- Sound: 33
sound.Add({
	name = "wfoly_plr_sh_oscar12_inspect_04",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_sh_oscar12_inspect_04.ogg",
		}
})
-- Sound: 34
sound.Add({
	name = "wfoly_plr_sh_oscar12_inspect_05",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_sh_oscar12_inspect_05.ogg",
		}
})
-- Sound: 35
sound.Add({
	name = "wfoly_plr_sh_oscar12_raise_01",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_raise_up.ogg",
		}
})
-- Sound: 36
sound.Add({
	name = "wfoly_plr_sh_oscar12_raise_quick_01",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_raise_quick_up.ogg",
		}
})
-- Sound: 37
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_01",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_start.ogg",
		}
})
-- Sound: 38
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_02",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_pull.ogg",
		}
})
-- Sound: 39
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_03",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_magout_01.ogg",
		}
})
-- Sound: 40
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_04",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_magin_v2_01.ogg",
		}
})
-- Sound: 41
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_045",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_magin_v2_02.ogg",
		}
})
-- Sound: 42
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_05",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_end.ogg",
		}
})
-- Sound: 43
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_drum_01",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_drum_start.ogg",
		}
})
-- Sound: 44
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_drum_02",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_drum_drumout_01.ogg",
		}
})
-- Sound: 45
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_drum_03",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_drum_tilt.ogg",
		}
})
-- Sound: 46
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_drum_04",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_drum_drumin_01.ogg",
		}
})
-- Sound: 47
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_drum_05",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_drum_end.ogg",
		}
})
-- Sound: 48
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_empty_01",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_empty_start.ogg",
		}
})
-- Sound: 49
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_empty_02",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_empty_magout_01.ogg",
		}
})
-- Sound: 50
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_empty_03",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_empty_tilt.ogg",
		}
})
-- Sound: 51
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_empty_04",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_empty_magin_v2_01.ogg",
		}
})
-- Sound: 52
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_empty_045",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_empty_magin_v2_02.ogg",
		}
})
-- Sound: 53
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_empty_05",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_empty_hands.ogg",
		}
})
-- Sound: 54
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_empty_06",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_empty_xmag_charge_01.ogg",
		}
})
-- Sound: 55
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_empty_07",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_empty_end.ogg",
		}
})
-- Sound: 56
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_empty_drum_01",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_empty_drum_start.ogg",
		}
})
-- Sound: 57
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_empty_drum_02",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_empty_drum_drumout_01.ogg",
		}
})
-- Sound: 58
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_empty_drum_03",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_empty_drum_tilt.ogg",
		}
})
-- Sound: 59
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_empty_drum_04",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_empty_drum_drumin_01.ogg",
		}
})
-- Sound: 60
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_empty_drum_05",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_empty_drum_arm.ogg",
		}
})
-- Sound: 61
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_empty_drum_06",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_empty_drum_grip.ogg",
		}
})
-- Sound: 62
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_empty_drum_07",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_empty_drum_charge_01.ogg",
		}
})
-- Sound: 63
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_empty_drum_08",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_empty_drum_end.ogg",
		}
})
-- Sound: 64
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_empty_fast_01",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_empty_fast_start.ogg",
		}
})
-- Sound: 65
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_empty_fast_02",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_empty_fast_magout_01.ogg",
		}
})
-- Sound: 66
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_empty_fast_03",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_empty_fast_arm.ogg",
		}
})
-- Sound: 67
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_empty_fast_04",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_empty_fast_magin_v2_01.ogg",
		}
})
-- Sound: 68
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_empty_fast_045",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_empty_fast_magin_v2_02.ogg",
		}
})
-- Sound: 69
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_empty_fast_05",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_empty_fast_xmag_charge_01.ogg",
		}
})
-- Sound: 70
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_empty_fast_06",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_empty_fast_end.ogg",
		}
})
-- Sound: 71
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_empty_fast_drum_01",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_empty_fast_drum_start.ogg",
		}
})
-- Sound: 72
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_empty_fast_drum_02",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_empty_fast_drum_drumout_01.ogg",
		}
})
-- Sound: 73
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_empty_fast_drum_03",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_empty_fast_drum_tilt.ogg",
		}
})
-- Sound: 74
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_empty_fast_drum_04",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_empty_fast_drum_drumin_01.ogg",
		}
})
-- Sound: 75
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_empty_fast_drum_05",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_empty_fast_drum_charge_01.ogg",
		}
})
-- Sound: 76
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_empty_fast_drum_06",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_empty_fast_drum_end.ogg",
		}
})
-- Sound: 77
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_empty_fast_xmag_01",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_empty_fast_xmag_start.ogg",
		}
})
-- Sound: 78
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_empty_fast_xmag_02",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_empty_fast_xmag_magout_01.ogg",
		}
})
-- Sound: 79
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_empty_fast_xmag_03",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_empty_fast_xmag_arm.ogg",
		}
})
-- Sound: 80
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_empty_fast_xmag_04",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_empty_fast_xmag_magin_01.ogg",
		}
})
-- Sound: 81
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_empty_fast_xmag_05",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_empty_fast_xmag_charge_01.ogg",
		}
})
-- Sound: 82
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_empty_fast_xmag_06",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_empty_fast_xmag_end.ogg",
		}
})
-- Sound: 83
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_empty_xmag_01",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_empty_xmag_start.ogg",
		}
})
-- Sound: 84
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_empty_xmag_02",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_empty_xmag_magout_01.ogg",
		}
})
-- Sound: 85
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_empty_xmag_03",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_empty_xmag_tilt.ogg",
		}
})
-- Sound: 86
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_empty_xmag_04",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_empty_xmag_magin_01.ogg",
		}
})
-- Sound: 87
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_empty_xmag_05",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_empty_xmag_arm.ogg",
		}
})
-- Sound: 88
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_empty_xmag_06",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_empty_xmag_grab.ogg",
		}
})
-- Sound: 89
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_empty_xmag_07",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_empty_xmag_charge_01.ogg",
		}
})
-- Sound: 90
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_empty_xmag_08",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_empty_xmag_end.ogg",
		}
})
-- Sound: 91
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_fast_01",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_fast_start.ogg",
		}
})
-- Sound: 92
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_fast_02",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_fast_magout_01.ogg",
		}
})
-- Sound: 93
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_fast_03",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_fast_magin_01.ogg",
		}
})
-- Sound: 94
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_fast_04",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_fast_end.ogg",
		}
})
-- Sound: 95
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_fast_drum_01",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_fast_drum_start.ogg",
		}
})
-- Sound: 96
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_fast_drum_02",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_fast_drum_drumout_01.ogg",
		}
})
-- Sound: 97
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_fast_drum_03",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_fast_drum_tilt.ogg",
		}
})
-- Sound: 98
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_fast_drum_04",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_fast_drum_drumin_01.ogg",
		}
})
-- Sound: 99
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_fast_drum_05",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_fast_drum_end.ogg",
		}
})
-- Sound: 100
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_fast_xmag_01",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_fast_xmag_start.ogg",
		}
})
-- Sound: 101
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_fast_xmag_02",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_fast_xmag_magout_01.ogg",
		}
})
-- Sound: 102
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_fast_xmag_03",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_fast_xmag_magin_01.ogg",
		}
})
-- Sound: 103
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_fast_xmag_04",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_fast_xmag_end.ogg",
		}
})
-- Sound: 104
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_xmag_01",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_xmag_start.ogg",
		}
})
-- Sound: 105
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_xmag_02",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_xmag_magout_01.ogg",
		}
})
-- Sound: 106
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_xmag_03",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_xmag_magin_01.ogg",
		}
})
-- Sound: 107
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_xmag_04",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_xmag_arm.ogg",
		}
})
-- Sound: 108
sound.Add({
	name = "wfoly_plr_sh_oscar12_reload_xmag_05",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_oscar12/wfoly_plr_sh_oscar12_reload_xmag_end.ogg",
		}
})
