-- Generated by GmodSoundGen

-- File: D:\Downloads\important_stuff_v2\Tools\GmodSoundGen_0519\weapon_pi_mike.all.sabs.lua
-- Total length: 288

-- Sound: 26
sound.Add({
	name = "weap_mike_fire_plr",
	channel = CHAN_WEAPON,
	level = 140,
	volume = 1,
	pitch = {100,100},
	sound = "^weapons/mike/weap_mike_fire_plr.wav"
		
})
sound.Add({
	name = "weap_mike_fire_first",
	channel = CHAN_WPNFOLEY,
	volume = 1,
	pitch = {100,100},
	sound = "weapons/mike/weap_mike_hammer_plr_01.ogg",
		
})
sound.Add({
	name = "weap_mike_fire_disconnector",
	channel = CHAN_WPNFOLEY +1,
	volume = 1,
	pitch = {100,100},
	sound = {
		"weapons/mike/weap_mike_disconnector_plr_01.ogg",
		}
})
-- Sound: 42
sound.Add({
	name = "weap_mike_sup_plr",
	channel = CHAN_WEAPON,
	level = 140,
	volume = 1,
	pitch = {100,100},
	sound = {
		"weapons/mike/weap_mike_sup_fire_plr_01.ogg",
		}
})
-- Sound: 60
sound.Add({
	name = "weap_pi_mike_ads_down",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike1911/wfoly_pi_mike1911_ads_down.ogg",
		}
})
-- Sound: 61
sound.Add({
	name = "weap_pi_mike_ads_up",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike1911/wfoly_pi_mike1911_ads_up.ogg",
		}
})
-- Sound: 62
sound.Add({
	name = "wfoly_plr_pi_mike_drop_01",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_drop.ogg",
		}
})
-- Sound: 63
sound.Add({
	name = "wfoly_plr_pi_mike_drop_quick_01",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_drop_quick.ogg",
		}
})
-- Sound: 64
sound.Add({
	name = "wfoly_plr_pi_mike_drop_quick_stock_01",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_drop_quick_stock.ogg",
		}
})
-- Sound: 65
sound.Add({
	name = "wfoly_plr_pi_mike_drop_singleaction_01",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_drop_singleaction.ogg",
		}
})
-- Sound: 66
sound.Add({
	name = "wfoly_plr_pi_mike_drop_singleaction_stock_01",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_drop_singleaction_stock.ogg",
		}
})
-- Sound: 67
sound.Add({
	name = "wfoly_plr_pi_mike_drop_stock_01",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_drop_stock.ogg",
		}
})
-- Sound: 68
sound.Add({
	name = "wfoly_plr_pi_mike_inspect_01",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_inspect_up.ogg",
		}
})
-- Sound: 69
sound.Add({
	name = "wfoly_plr_pi_mike_inspect_02",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_inspect_magin.ogg",
		}
})
-- Sound: 70
sound.Add({
	name = "wfoly_plr_pi_mike_inspect_03",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_inspect_rotate.ogg",
		}
})
-- Sound: 71
sound.Add({
	name = "wfoly_plr_pi_mike_inspect_04",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_inspect_end.ogg",
		}
})
-- Sound: 72
sound.Add({
	name = "wfoly_plr_pi_mike_inspect_drum_01",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_inspect_drum_drumout.ogg",
		}
})
-- Sound: 73
sound.Add({
	name = "wfoly_plr_pi_mike_inspect_drum_02",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_inspect_drum_drumin.ogg",
		}
})
-- Sound: 74
sound.Add({
	name = "wfoly_plr_pi_mike_inspect_drum_03",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_inspect_drum_rotate.ogg",
		}
})
-- Sound: 75
sound.Add({
	name = "wfoly_plr_pi_mike_inspect_drum_04",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_inspect_drum_mvmnt.ogg",
		}
})
-- Sound: 76
sound.Add({
	name = "wfoly_plr_pi_mike_inspect_drum_05",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_inspect_drum_end.ogg",
		}
})
-- Sound: 77
sound.Add({
	name = "wfoly_plr_pi_mike_inspect_drum_stock_01",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_inspect_drum_magout.ogg",
		}
})
-- Sound: 78
sound.Add({
	name = "wfoly_plr_pi_mike_inspect_drum_stock_02",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_inspect_drum_stock_drumin.ogg",
		}
})
-- Sound: 79
sound.Add({
	name = "wfoly_plr_pi_mike_inspect_drum_stock_03",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_inspect_drum_stock_rotate.ogg",
		}
})
-- Sound: 80
sound.Add({
	name = "wfoly_plr_pi_mike_inspect_drum_stock_04",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_inspect_drum_stock_mvmnt.ogg",
		}
})
-- Sound: 81
sound.Add({
	name = "wfoly_plr_pi_mike_inspect_drum_stock_05",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_inspect_drum_stock_end.ogg",
		}
})
-- Sound: 82
sound.Add({
	name = "wfoly_plr_pi_mike_inspect_stock_01",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_inspect_stock_magout.ogg",
		}
})
-- Sound: 83
sound.Add({
	name = "wfoly_plr_pi_mike_inspect_stock_02",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_inspect_stock_drumin.ogg",
		}
})
-- Sound: 84
sound.Add({
	name = "wfoly_plr_pi_mike_inspect_stock_03",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_inspect_stock_mvmnt.ogg",
		}
})
-- Sound: 85
sound.Add({
	name = "wfoly_plr_pi_mike_inspect_stock_04",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_inspect_stock_end.ogg",
		}
})
-- Sound: 86
sound.Add({
	name = "wfoly_plr_pi_mike_inspect_xmag_01",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_inspect_xmag_magout.ogg",
		}
})
-- Sound: 87
sound.Add({
	name = "wfoly_plr_pi_mike_inspect_xmag_02",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_inspect_xmag_magin.ogg",
		}
})
-- Sound: 88
sound.Add({
	name = "wfoly_plr_pi_mike_inspect_xmag_03",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_inspect_xmag_mvmnt.ogg",
		}
})
-- Sound: 89
sound.Add({
	name = "wfoly_plr_pi_mike_inspect_xmag_04",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_inspect_xmag_end.ogg",
		}
})
-- Sound: 90
sound.Add({
	name = "wfoly_plr_pi_mike_inspect_xmag_stock_01",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_inspect_xmag_stock_magout.ogg",
		}
})
-- Sound: 91
sound.Add({
	name = "wfoly_plr_pi_mike_inspect_xmag_stock_02",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_inspect_xmag_stock_magin.ogg",
		}
})
-- Sound: 92
sound.Add({
	name = "wfoly_plr_pi_mike_inspect_xmag_stock_03",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_inspect_xmag_stock_rotate.ogg",
		}
})
-- Sound: 93
sound.Add({
	name = "wfoly_plr_pi_mike_inspect_xmag_stock_04",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_inspect_xmag_stock_mvmnt.ogg",
		}
})
-- Sound: 94
sound.Add({
	name = "wfoly_plr_pi_mike_inspect_xmag_stock_05",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_inspect_xmag_stock_end.ogg",
		}
})
-- Sound: 95
sound.Add({
	name = "wfoly_plr_pi_mike_l_drop_01",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_i_drop.ogg",
		}
})
-- Sound: 96
sound.Add({
	name = "wfoly_plr_pi_mike_l_drop_quick_01",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_i_drop_quick.ogg",
		}
})
-- Sound: 97
sound.Add({
	name = "wfoly_plr_pi_mike_l_inspect_01",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_i_inspect_up.ogg",
		}
})
-- Sound: 98
sound.Add({
	name = "wfoly_plr_pi_mike_l_inspect_02",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_i_inspect_rotate.ogg",
		}
})
-- Sound: 99
sound.Add({
	name = "wfoly_plr_pi_mike_l_inspect_03",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_i_inspect_end.ogg",
		}
})
-- Sound: 100
sound.Add({
	name = "wfoly_plr_pi_mike_l_raise_01",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_i_raise.ogg",
		}
})
-- Sound: 101
sound.Add({
	name = "wfoly_plr_pi_mike_l_reload_01",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_i_reload_down.ogg",
		}
})
-- Sound: 102
sound.Add({
	name = "wfoly_plr_pi_mike_l_reload_02",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_i_reload_magout.ogg",
		}
})
-- Sound: 103
sound.Add({
	name = "wfoly_plr_pi_mike_l_reload_03",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_i_reload_magin.ogg",
		}
})
-- Sound: 104
sound.Add({
	name = "wfoly_plr_pi_mike_l_reload_04",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_i_reload_end.ogg",
		}
})
-- Sound: 105
sound.Add({
	name = "wfoly_plr_pi_mike_l_reload_empty_01",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_i_reload_empty_down.ogg",
		}
})
-- Sound: 106
sound.Add({
	name = "wfoly_plr_pi_mike_l_reload_empty_02",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_i_reload_empty_magout.ogg",
		}
})
-- Sound: 107
sound.Add({
	name = "wfoly_plr_pi_mike_l_reload_empty_03",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_i_reload_empty_mvmnt.ogg",
		}
})
-- Sound: 108
sound.Add({
	name = "wfoly_plr_pi_mike_l_reload_empty_04",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_i_reload_empty_magin.ogg",
		}
})
-- Sound: 109
sound.Add({
	name = "wfoly_plr_pi_mike_l_reload_empty_05",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_i_reload_empty_up.ogg",
		}
})
-- Sound: 110
sound.Add({
	name = "wfoly_plr_pi_mike_l_reload_empty_06",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_i_reload_empty_charge.ogg",
		}
})
-- Sound: 111
sound.Add({
	name = "wfoly_plr_pi_mike_l_reload_empty_07",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_i_reload_empty_end.ogg",
		}
})
-- Sound: 112
sound.Add({
	name = "wfoly_plr_pi_mike_l_reload_empty_fast_01",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_i_reload_empty_fast_down.ogg",
		}
})
-- Sound: 113
sound.Add({
	name = "wfoly_plr_pi_mike_l_reload_empty_fast_02",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_i_reload_empty_fast_magout.ogg",
		}
})
-- Sound: 114
sound.Add({
	name = "wfoly_plr_pi_mike_l_reload_empty_fast_03",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_i_reload_empty_fast_magin.ogg",
		}
})
-- Sound: 115
sound.Add({
	name = "wfoly_plr_pi_mike_l_reload_empty_fast_04",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_i_reload_empty_fast_up.ogg",
		}
})
-- Sound: 116
sound.Add({
	name = "wfoly_plr_pi_mike_l_reload_empty_fast_05",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_i_reload_empty_fast_charge.ogg",
		}
})
-- Sound: 117
sound.Add({
	name = "wfoly_plr_pi_mike_l_reload_empty_fast_06",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_i_reload_empty_fast_end.ogg",
		}
})
-- Sound: 118
sound.Add({
	name = "wfoly_plr_pi_mike_l_reload_fast_01",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_i_reload_fast_down.ogg",
		}
})
-- Sound: 119
sound.Add({
	name = "wfoly_plr_pi_mike_l_reload_fast_02",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_i_reload_fast_magout.ogg",
		}
})
-- Sound: 120
sound.Add({
	name = "wfoly_plr_pi_mike_l_reload_fast_03",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_i_reload_fast_magin.ogg",
		}
})
-- Sound: 121
sound.Add({
	name = "wfoly_plr_pi_mike_l_reload_fast_04",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_i_reload_fast_end.ogg",
		}
})
-- Sound: 122
sound.Add({
	name = "wfoly_plr_pi_mike_r_drop_01",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_r_drop.ogg",
		}
})
-- Sound: 123
sound.Add({
	name = "wfoly_plr_pi_mike_r_drop_quick_01",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_r_drop_quick.ogg",
		}
})
-- Sound: 124
sound.Add({
	name = "wfoly_plr_pi_mike_r_inspect_01",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_r_inspect_up.ogg",
		}
})
-- Sound: 125
sound.Add({
	name = "wfoly_plr_pi_mike_r_inspect_02",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_r_inspect_rotate.ogg",
		}
})
-- Sound: 126
sound.Add({
	name = "wfoly_plr_pi_mike_r_inspect_03",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_r_inspect_end.ogg",
		}
})
-- Sound: 127
sound.Add({
	name = "wfoly_plr_pi_mike_r_raise_01",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_r_raise.ogg",
		}
})
-- Sound: 128
sound.Add({
	name = "wfoly_plr_pi_mike_r_reload_01",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike'/wfoly_pi_mike_r_reload_down.ogg",
		}
})
-- Sound: 129
sound.Add({
	name = "wfoly_plr_pi_mike_r_reload_02",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike'/wfoly_pi_mike_r_reload_mvmnt.ogg",
		}
})
-- Sound: 130
sound.Add({
	name = "wfoly_plr_pi_mike_r_reload_03",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike'/wfoly_pi_mike_r_reload_magout.ogg",
		}
})
-- Sound: 131
sound.Add({
	name = "wfoly_plr_pi_mike_r_reload_04",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike'/wfoly_pi_mike_r_reload_magin.ogg",
		}
})
-- Sound: 132
sound.Add({
	name = "wfoly_plr_pi_mike_r_reload_05",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike'/wfoly_pi_mike_r_reload_end.ogg",
		}
})
-- Sound: 133
sound.Add({
	name = "wfoly_plr_pi_mike_r_reload_empty_01",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_r_reload_empty_down.ogg",
		}
})
-- Sound: 134
sound.Add({
	name = "wfoly_plr_pi_mike_r_reload_empty_02",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_r_reload_empty_magout.ogg",
		}
})
-- Sound: 135
sound.Add({
	name = "wfoly_plr_pi_mike_r_reload_empty_03",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_r_reload_empty_mvmnt.ogg",
		}
})
-- Sound: 136
sound.Add({
	name = "wfoly_plr_pi_mike_r_reload_empty_04",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_r_reload_empty_magin.ogg",
		}
})
-- Sound: 137
sound.Add({
	name = "wfoly_plr_pi_mike_r_reload_empty_05",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_r_reload_empty_up.ogg",
		}
})
-- Sound: 138
sound.Add({
	name = "wfoly_plr_pi_mike_r_reload_empty_06",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_r_reload_empty_charge.ogg",
		}
})
-- Sound: 139
sound.Add({
	name = "wfoly_plr_pi_mike_r_reload_empty_07",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_r_reload_empty_end.ogg",
		}
})
-- Sound: 140
sound.Add({
	name = "wfoly_plr_pi_mike_r_reload_empty_fast_01",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_r_reload_empty_fast_down.ogg",
		}
})
-- Sound: 141
sound.Add({
	name = "wfoly_plr_pi_mike_r_reload_empty_fast_02",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_r_reload_empty_fast_magout.ogg",
		}
})
-- Sound: 142
sound.Add({
	name = "wfoly_plr_pi_mike_r_reload_empty_fast_03",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_r_reload_empty_fast_magin.ogg",
		}
})
-- Sound: 143
sound.Add({
	name = "wfoly_plr_pi_mike_r_reload_empty_fast_04",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_r_reload_empty_fast_up.ogg",
		}
})
-- Sound: 144
sound.Add({
	name = "wfoly_plr_pi_mike_r_reload_empty_fast_05",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_r_reload_empty_fast_charge.ogg",
		}
})
-- Sound: 145
sound.Add({
	name = "wfoly_plr_pi_mike_r_reload_empty_fast_06",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_r_reload_empty_fast_end.ogg",
		}
})
-- Sound: 146
sound.Add({
	name = "wfoly_plr_pi_mike_r_reload_fast_01",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_r_reload_fast_down.ogg",
		}
})
-- Sound: 147
sound.Add({
	name = "wfoly_plr_pi_mike_r_reload_fast_02",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_r_reload_fast_magout.ogg",
		}
})
-- Sound: 148
sound.Add({
	name = "wfoly_plr_pi_mike_r_reload_fast_03",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_r_reload_fast_magin.ogg",
		}
})
-- Sound: 149
sound.Add({
	name = "wfoly_plr_pi_mike_r_reload_fast_04",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_r_reload_fast_end.ogg",
		}
})
-- Sound: 150
sound.Add({
	name = "wfoly_plr_pi_mike_raise_01",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_raise.ogg",
		}
})
-- Sound: 150
sound.Add({
	name = "wfoly_plr_pi_mike_raise_first_01",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_first_raise_up.ogg",
		}
})
sound.Add({
	name = "wfoly_plr_pi_mike_raise_first_02",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_first_raise_magout.ogg",
		}
})
sound.Add({
	name = "wfoly_plr_pi_mike_raise_first_03",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_first_raise_magin.ogg",
		}
})
sound.Add({
	name = "wfoly_plr_pi_mike_raise_first_04",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_first_raise_end.ogg",
		}
})

-- Sound: 150
sound.Add({
	name = "wfoly_plr_pi_mike_raise_first_drum_01",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_raise_first_drum_drumout.ogg",
		}
})
sound.Add({
	name = "wfoly_plr_pi_mike_raise_first_drum_02",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_raise_first_drum_drumin.ogg",
		}
})
sound.Add({
	name = "wfoly_plr_pi_mike_raise_first_drum_03",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_raise_first_drum_end.ogg",
		}
})
-- Sound: 151
sound.Add({
	name = "wfoly_plr_pi_mike_raise_singleaction_01",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_raise_singleaction.ogg",
		}
})
-- Sound: 152
sound.Add({
	name = "wfoly_plr_pi_mike_raise_singleaction_stock_01",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_raise_singleaction_stock.ogg",
		}
})
-- Sound: 153
sound.Add({
	name = "wfoly_plr_pi_mike_raise_stock_01",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_raise_stock.ogg",
		}
})
-- Sound: 154
sound.Add({
	name = "wfoly_plr_pi_mike_reload_01",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_up.ogg",
		}
})
-- Sound: 155
sound.Add({
	name = "wfoly_plr_pi_mike_reload_02",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_magout.ogg",
		}
})
-- Sound: 156
sound.Add({
	name = "wfoly_plr_pi_mike_reload_03",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_mvmnt.ogg",
		}
})
-- Sound: 157
sound.Add({
	name = "wfoly_plr_pi_mike_reload_04",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_magin.ogg",
		}
})
-- Sound: 158
sound.Add({
	name = "wfoly_plr_pi_mike_reload_05",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_end.ogg",
		}
})
-- Sound: 159
sound.Add({
	name = "wfoly_plr_pi_mike_reload_drum_01",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_drum_up.ogg",
		}
})
-- Sound: 160
sound.Add({
	name = "wfoly_plr_pi_mike_reload_drum_02",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_drum_grab_drum.ogg",
		}
})
-- Sound: 161
sound.Add({
	name = "wfoly_plr_pi_mike_reload_drum_03",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_drum_drumout.ogg",
		}
})
-- Sound: 162
sound.Add({
	name = "wfoly_plr_pi_mike_reload_drum_04",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_drum_drumhit.ogg",
		}
})
-- Sound: 163
sound.Add({
	name = "wfoly_plr_pi_mike_reload_drum_05",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_drum_drumin.ogg",
		}
})
-- Sound: 164
sound.Add({
	name = "wfoly_plr_pi_mike_reload_drum_06",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_drum_end.ogg",
		}
})
-- Sound: 165
sound.Add({
	name = "wfoly_plr_pi_mike_reload_drum_stock_01",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_drum_stock_up.ogg",
		}
})
-- Sound: 166
sound.Add({
	name = "wfoly_plr_pi_mike_reload_drum_stock_02",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_drum_stock_grabdrum.ogg",
		}
})
-- Sound: 167
sound.Add({
	name = "wfoly_plr_pi_mike_reload_drum_stock_03",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_drum_stock_drumout.ogg",
		}
})
-- Sound: 168
sound.Add({
	name = "wfoly_plr_pi_mike_reload_drum_stock_04",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_drum_stock_mvmnt.ogg",
		}
})
-- Sound: 169
sound.Add({
	name = "wfoly_plr_pi_mike_reload_drum_stock_05",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_drum_stock_drumhit.ogg",
		}
})
-- Sound: 170
sound.Add({
	name = "wfoly_plr_pi_mike_reload_drum_stock_06",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_drum_stock_drumin.ogg",
		}
})
-- Sound: 171
sound.Add({
	name = "wfoly_plr_pi_mike_reload_drum_stock_07",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_drum_stock_end.ogg",
		}
})
-- Sound: 172
sound.Add({
	name = "wfoly_plr_pi_mike_reload_empty_01",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_empty_up.ogg",
		}
})
-- Sound: 173
sound.Add({
	name = "wfoly_plr_pi_mike_reload_empty_02",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_empty_magout.ogg",
		}
})
-- Sound: 174
sound.Add({
	name = "wfoly_plr_pi_mike_reload_empty_03",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_empty_maghit.ogg",
		}
})
-- Sound: 175
sound.Add({
	name = "wfoly_plr_pi_mike_reload_empty_04",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_empty_magin.ogg",
		}
})
-- Sound: 176
sound.Add({
	name = "wfoly_plr_pi_mike_reload_empty_05",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_empty_charge.ogg",
		}
})
-- Sound: 177
sound.Add({
	name = "wfoly_plr_pi_mike_reload_empty_06",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_empty_end.ogg",
		}
})
-- Sound: 178
sound.Add({
	name = "wfoly_plr_pi_mike_reload_empty_drum_01",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_empty_drum_up.ogg",
		}
})
-- Sound: 179
sound.Add({
	name = "wfoly_plr_pi_mike_reload_empty_drum_02",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_empty_drum_grabdrum.ogg",
		}
})
-- Sound: 180
sound.Add({
	name = "wfoly_plr_pi_mike_reload_empty_drum_03",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_empty_drum_drumout.ogg",
		}
})
-- Sound: 181
sound.Add({
	name = "wfoly_plr_pi_mike_reload_empty_drum_04",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_empty_drum_drumhit.ogg",
		}
})
-- Sound: 182
sound.Add({
	name = "wfoly_plr_pi_mike_reload_empty_drum_05",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_empty_drum_drumin.ogg",
		}
})
-- Sound: 183
sound.Add({
	name = "wfoly_plr_pi_mike_reload_empty_drum_06",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_empty_drum_charge.ogg",
		}
})
-- Sound: 184
sound.Add({
	name = "wfoly_plr_pi_mike_reload_empty_drum_07",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_empty_drum_end.ogg",
		}
})
-- Sound: 185
sound.Add({
	name = "wfoly_plr_pi_mike_reload_empty_drum_stock_01",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_empty_drum_stock_up.ogg",
		}
})
-- Sound: 186
sound.Add({
	name = "wfoly_plr_pi_mike_reload_empty_drum_stock_02",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_empty_drum_stock_grabdrum.ogg",
		}
})
-- Sound: 187
sound.Add({
	name = "wfoly_plr_pi_mike_reload_empty_drum_stock_03",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_empty_drum_stock_drumout.ogg",
		}
})
-- Sound: 188
sound.Add({
	name = "wfoly_plr_pi_mike_reload_empty_drum_stock_04",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_empty_drum_stock_maghit.ogg",
		}
})
-- Sound: 189
sound.Add({
	name = "wfoly_plr_pi_mike_reload_empty_drum_stock_05",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_empty_drum_stock_drumin.ogg",
		}
})
-- Sound: 190
sound.Add({
	name = "wfoly_plr_pi_mike_reload_empty_drum_stock_06",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_empty_drum_stock_mvmnt.ogg",
		}
})
-- Sound: 191
sound.Add({
	name = "wfoly_plr_pi_mike_reload_empty_drum_stock_07",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_empty_drum_stock_charge.ogg",
		}
})
-- Sound: 192
sound.Add({
	name = "wfoly_plr_pi_mike_reload_empty_drum_stock_08",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_empty_drum_stock_end.ogg",
		}
})
-- Sound: 193
sound.Add({
	name = "wfoly_plr_pi_mike_reload_empty_stock_01",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_empty_stock_up.ogg",
		}
})
-- Sound: 194
sound.Add({
	name = "wfoly_plr_pi_mike_reload_empty_stock_02",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_empty_stock_magout.ogg",
		}
})
-- Sound: 195
sound.Add({
	name = "wfoly_plr_pi_mike_reload_empty_stock_03",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_empty_stock_maghit.ogg",
		}
})
-- Sound: 196
sound.Add({
	name = "wfoly_plr_pi_mike_reload_empty_stock_04",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_empty_stock_magin.ogg",
		}
})
-- Sound: 197
sound.Add({
	name = "wfoly_plr_pi_mike_reload_empty_stock_05",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_empty_stock_charge.ogg",
		}
})
-- Sound: 198
sound.Add({
	name = "wfoly_plr_pi_mike_reload_empty_stock_06",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_empty_stock_end.ogg",
		}
})
-- Sound: 199
sound.Add({
	name = "wfoly_plr_pi_mike_reload_empty_xmag_01",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_empty_xmag_up.ogg",
		}
})
-- Sound: 200
sound.Add({
	name = "wfoly_plr_pi_mike_reload_empty_xmag_02",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_empty_xmag_magout.ogg",
		}
})
-- Sound: 201
sound.Add({
	name = "wfoly_plr_pi_mike_reload_empty_xmag_03",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_empty_xmag_magin.ogg",
		}
})
-- Sound: 202
sound.Add({
	name = "wfoly_plr_pi_mike_reload_empty_xmag_04",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_empty_xmag_charge.ogg",
		}
})
-- Sound: 203
sound.Add({
	name = "wfoly_plr_pi_mike_reload_empty_xmag_05",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_empty_xmag_end.ogg",
		}
})
-- Sound: 204
sound.Add({
	name = "wfoly_plr_pi_mike_reload_empty_xmag_stock_01",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_empty_xmag_stock_up.ogg",
		}
})
-- Sound: 205
sound.Add({
	name = "wfoly_plr_pi_mike_reload_empty_xmag_stock_02",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_empty_xmag_stock_magout.ogg",
		}
})
-- Sound: 206
sound.Add({
	name = "wfoly_plr_pi_mike_reload_empty_xmag_stock_03",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_empty_xmag_stock_maghit.ogg",
		}
})
-- Sound: 207
sound.Add({
	name = "wfoly_plr_pi_mike_reload_empty_xmag_stock_04",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_empty_xmag_stock_magin.ogg",
		}
})
-- Sound: 208
sound.Add({
	name = "wfoly_plr_pi_mike_reload_empty_xmag_stock_05",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_empty_xmag_stock_charge.ogg",
		}
})
-- Sound: 209
sound.Add({
	name = "wfoly_plr_pi_mike_reload_empty_xmag_stock_06",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_empty_xmag_stock_end.ogg",
		}
})
-- Sound: 210
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_01",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_up.ogg",
		}
})
-- Sound: 211
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_02",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_magout.ogg",
		}
})
-- Sound: 212
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_03",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_magin.ogg",
		}
})
-- Sound: 213
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_04",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_end.ogg",
		}
})
-- Sound: 214
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_drum_01",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_drum_up.ogg",
		}
})
-- Sound: 215
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_drum_02",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_drum_grabdrum.ogg",
		}
})
-- Sound: 216
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_drum_03",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_drum_drumout.ogg",
		}
})
-- Sound: 217
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_drum_04",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_drum_drumhit.ogg",
		}
})
-- Sound: 218
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_drum_05",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_drum_drumin.ogg",
		}
})
-- Sound: 219
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_drum_06",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_drum_end.ogg",
		}
})
-- Sound: 220
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_drum_stock_01",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_drum_stock_up.ogg",
		}
})
-- Sound: 221
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_drum_stock_02",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_drum_stock_drumout.ogg",
		}
})
-- Sound: 222
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_drum_stock_03",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_drum_stock_mvmnt.ogg",
		}
})
-- Sound: 223
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_drum_stock_04",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_drum_stock_drumhit.ogg",
		}
})
-- Sound: 224
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_drum_stock_05",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_drum_stock_drumin.ogg",
		}
})
-- Sound: 225
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_drum_stock_06",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_drum_stock_end.ogg",
		}
})
-- Sound: 226
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_empty_01",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_empty_up.ogg",
		}
})
-- Sound: 227
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_empty_02",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_empty_magout.ogg",
		}
})
-- Sound: 228
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_empty_03",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_empty_magin.ogg",
		}
})
-- Sound: 229
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_empty_04",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_empty_charge.ogg",
		}
})
-- Sound: 230
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_empty_05",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_empty_end.ogg",
		}
})
-- Sound: 231
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_empty_drum_01",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_empty_drum_up.ogg",
		}
})
-- Sound: 232
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_empty_drum_02",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_empty_drum_grabdrum.ogg",
		}
})
-- Sound: 233
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_empty_drum_03",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_empty_drum_drumout.ogg",
		}
})
-- Sound: 234
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_empty_drum_04",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_empty_drum_mvmnt.ogg",
		}
})
-- Sound: 235
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_empty_drum_05",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_empty_drum_drumin.ogg",
		}
})
-- Sound: 236
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_empty_drum_06",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_empty_drum_end.ogg",
		}
})
-- Sound: 237
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_empty_drum_07",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_empty_drum_charge.ogg",
		}
})
-- Sound: 238
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_empty_drum_stock_01",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_empty_drum_stock_up.ogg",
		}
})
-- Sound: 239
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_empty_drum_stock_02",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_empty_drum_stock_grabdrum.ogg",
		}
})
-- Sound: 240
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_empty_drum_stock_03",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_empty_drum_stock_drumout.ogg",
		}
})
-- Sound: 241
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_empty_drum_stock_04",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_empty_drum_stock_drumhit.ogg",
		}
})
-- Sound: 242
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_empty_drum_stock_05",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_empty_drum_stock_drumin.ogg",
		}
})
-- Sound: 243
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_empty_drum_stock_06",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_empty_drum_stock_charge.ogg",
		}
})
-- Sound: 244
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_empty_drum_stock_07",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_empty_drum_stock_end.ogg",
		}
})
-- Sound: 245
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_empty_stock_01",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_empty_stock_up.ogg",
		}
})
-- Sound: 246
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_empty_stock_02",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_empty_stock_magout.ogg",
		}
})
-- Sound: 247
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_empty_stock_03",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_empty_stock_magin.ogg",
		}
})
-- Sound: 248
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_empty_stock_04",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_empty_stock_charge.ogg",
		}
})
-- Sound: 249
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_empty_stock_05",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_empty_stock_end1.ogg",
		}
})
-- Sound: 250
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_empty_xmag_01",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_empty_xmag_up.ogg",
		}
})
-- Sound: 251
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_empty_xmag_02",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_empty_xmag_magout.ogg",
		}
})
-- Sound: 252
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_empty_xmag_03",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_empty_xmag_maghit.ogg",
		}
})
-- Sound: 253
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_empty_xmag_04",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_empty_xmag_magin.ogg",
		}
})
-- Sound: 254
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_empty_xmag_05",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_empty_xmag_charge.ogg",
		}
})
-- Sound: 255
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_empty_xmag_06",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_empty_xmag_end.ogg",
		}
})
-- Sound: 256
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_empty_xmag_stock_01",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_empty_xmag_stock_up.ogg",
		}
})
-- Sound: 257
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_empty_xmag_stock_02",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_empty_xmag_stock_magout.ogg",
		}
})
-- Sound: 258
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_empty_xmag_stock_03",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_empty_xmag_stock_magin.ogg",
		}
})
-- Sound: 259
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_empty_xmag_stock_04",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_empty_xmag_stock_charge.ogg",
		}
})
-- Sound: 260
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_empty_xmag_stock_05",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_empty_xmag_stock_end.ogg",
		}
})
-- Sound: 261
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_stock_01",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_stock_up.ogg",
		}
})
-- Sound: 262
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_stock_02",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_stock_magout.ogg",
		}
})
-- Sound: 263
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_stock_03",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_stock_magin.ogg",
		}
})
-- Sound: 264
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_stock_04",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_stock_end.ogg",
		}
})
-- Sound: 265
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_xmag_01",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_xmag_up.ogg",
		}
})
-- Sound: 266
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_xmag_02",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_xmag_magout.ogg",
		}
})
-- Sound: 267
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_xmag_03",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_xmag_magin.ogg",
		}
})
-- Sound: 268
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_xmag_04",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_xmag_end.ogg",
		}
})
-- Sound: 269
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_xmag_stock_01",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_xmag_stock_up.ogg",
		}
})
-- Sound: 270
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_xmag_stock_02",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_xmag_stock_magout.ogg",
		}
})
-- Sound: 271
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_xmag_stock_03",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_xmag_stock_magin.ogg",
		}
})
-- Sound: 272
sound.Add({
	name = "wfoly_plr_pi_mike_reload_fast_xmag_stock_04",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_fast_xmag_stock_end.ogg",
		}
})
-- Sound: 273
sound.Add({
	name = "wfoly_plr_pi_mike_reload_stock_01",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_stock_up.ogg",
		}
})
-- Sound: 274
sound.Add({
	name = "wfoly_plr_pi_mike_reload_stock_02",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_stock_magout.ogg",
		}
})
-- Sound: 275
sound.Add({
	name = "wfoly_plr_pi_mike_reload_stock_03",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_stock_maghit.ogg",
		}
})
-- Sound: 276
sound.Add({
	name = "wfoly_plr_pi_mike_reload_stock_04",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_stock_magin.ogg",
		}
})
-- Sound: 277
sound.Add({
	name = "wfoly_plr_pi_mike_reload_stock_05",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_stock_end.ogg",
		}
})
-- Sound: 278
sound.Add({
	name = "wfoly_plr_pi_mike_reload_xmag_01",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_xmag_up.ogg",
		}
})
-- Sound: 279
sound.Add({
	name = "wfoly_plr_pi_mike_reload_xmag_02",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_xmag_magout.ogg",
		}
})
-- Sound: 280
sound.Add({
	name = "wfoly_plr_pi_mike_reload_xmag_03",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_xmag_maghit.ogg",
		}
})
-- Sound: 281
sound.Add({
	name = "wfoly_plr_pi_mike_reload_xmag_04",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_xmag_magin.ogg",
		}
})
-- Sound: 282
sound.Add({
	name = "wfoly_plr_pi_mike_reload_xmag_05",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_xmag_end.ogg",
		}
})
-- Sound: 283
sound.Add({
	name = "wfoly_plr_pi_mike_reload_xmag_stock_01",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_xmag_stock_up.ogg",
		}
})
-- Sound: 284
sound.Add({
	name = "wfoly_plr_pi_mike_reload_xmag_stock_02",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_xmag_stock_magout.ogg",
		}
})
-- Sound: 285
sound.Add({
	name = "wfoly_plr_pi_mike_reload_xmag_stock_03",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_xmag_stock_maghit.ogg",
		}
})
-- Sound: 286
sound.Add({
	name = "wfoly_plr_pi_mike_reload_xmag_stock_04",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_xmag_stock_magin.ogg",
		}
})
-- Sound: 287
sound.Add({
	name = "wfoly_plr_pi_mike_reload_xmag_stock_05",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike/wfoly_pi_mike_reload_xmag_stock_end.ogg",
		}
})
